Repository zeldaret/mm, pull requests merged in 2021-11, with the labels that each got.

#372 Update diff-init to be dependent on just the uncompressed rom
  Makefile
Labels: Tooling

#383 padsetup OK
  include/functions.h
  src/boot_O2/padsetup.c
  tools/disasm/functions.txt
Labels: boot

#389 sp.c OK
  src/libultra/io/sp.c
Labels: boot

#286 Rename yDistTo variables
  include/z64actor.h
  src/code/z_en_item00.c
  src/overlays/actors/ovl_Door_Ana/z_door_ana.c
  src/overlays/actors/ovl_En_Bji_01/z_en_bji_01.c
  src/overlays/actors/ovl_En_Dekunuts/z_en_dekunuts.c
  src/overlays/actors/ovl_En_Dg/z_en_dg.c
  src/overlays/actors/ovl_En_Dinofos/z_en_dinofos.c
  src/overlays/actors/ovl_En_Dno/z_en_dno.c
  src/overlays/actors/ovl_En_Dnq/z_en_dnq.c
  src/overlays/actors/ovl_En_Dodongo/z_en_dodongo.c
  src/overlays/actors/ovl_En_Elforg/z_en_elforg.c
  src/overlays/actors/ovl_En_Firefly/z_en_firefly.c
  src/overlays/actors/ovl_En_Hg/z_en_hg.c
  src/overlays/actors/ovl_En_Holl/z_en_holl.c
  src/overlays/actors/ovl_En_Minislime/z_en_minislime.c
  src/overlays/actors/ovl_En_Mushi2/z_en_mushi2.c
  src/overlays/actors/ovl_En_Niw/z_en_niw.c
  src/overlays/actors/ovl_En_Ot/z_en_ot.c
  src/overlays/actors/ovl_En_Pametfrog/z_en_pametfrog.c
  src/overlays/actors/ovl_En_Po_Sisters/z_en_po_sisters.c
  src/overlays/actors/ovl_En_Sb/z_en_sb.c
  src/overlays/actors/ovl_En_Sellnuts/z_en_sellnuts.c
  src/overlays/actors/ovl_En_Skb/z_en_skb.c
  src/overlays/actors/ovl_En_Suttari/z_en_suttari.c
  src/overlays/actors/ovl_En_Thiefbird/z_en_thiefbird.c
  src/overlays/actors/ovl_En_Tite/z_en_tite.c
  src/overlays/actors/ovl_En_Torch2/z_en_torch2.c
  src/overlays/actors/ovl_En_Tubo_Trap/z_en_tubo_trap.c
  src/overlays/actors/ovl_En_Wf/z_en_wf.c
  src/overlays/actors/ovl_Obj_Aqua/z_obj_aqua.c
  src/overlays/actors/ovl_Obj_Etcetera/z_obj_etcetera.c
  src/overlays/actors/ovl_Obj_Hgdoor/z_obj_hgdoor.c
  src/overlays/actors/ovl_Obj_Kibako/z_obj_kibako.c
  src/overlays/actors/ovl_TG_Sw/z_tg_sw.c
  tools/actorfixer.py
Labels: Clean up

#398 Common data OK
  include/functions.h
  spec
  src/code/title_setup.c
  src/code/z_common_data.c
  tools/disasm/functions.txt
Labels: code

#399 Debug display mostly OK
  assets/xml/code/debug_display.xml
  include/functions.h
  include/variables.h
  include/z64.h
  spec
  src/code/z_debug_display.c
  src/code/z_lights.c
  src/code/z_skin_matrix.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: code

#380 Demo_Kankyo (Lost Woods Sparkles)
  include/variables.h
  include/z64.h
  spec
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo.h
Labels: Overlay

#392 Match `SkelAnime_GetFrameDataLegacy`
  include/functions.h
  src/code/z_skelanime.c
  tools/disasm/functions.txt
Labels: code

#390 epirawread OK
  src/libultra/io/epirawread.c
Labels: boot

#391 epirawdma OK
  include/ultra64/hardware.h
  src/libultra/io/epirawdma.c
  src/libultra/io/epirawwrite.c
Labels: boot

#388 pfssearchfile OK
  include/functions.h
  src/libultra/io/pfssearchfile.c
Labels: boot

#381 Match EnItem00_Update
  src/code/z_en_item00.c
Labels: code

#400 Fireobj Kinda OK
  include/functions.h
  include/variables.h
  include/z64.h
  include/z64player.h
  spec
  src/code/z_fireobj.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: code

#387 pfsallocatefile OK
  include/functions.h
  src/libultra/io/pfsallocatefile.c
Labels: boot

#384 osspsetpc OK
  include/functions.h
  src/libultra/io/spsetpc.c
Labels: boot

#158 osFlash
  Makefile
  include/functions.h
  include/macros.h
  include/ultra64/hardware.h
  include/variables.h
  include/z64.h
  spec
  src/code/osFlash.c
  src/libultra/flash/osFlash.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: code

#375 En_Goroiwa (3 non-matching)
  include/functions.h
  spec
  src/overlays/actors/ovl_En_Goroiwa/z_en_goroiwa.c
  src/overlays/actors/ovl_En_Goroiwa/z_en_goroiwa.h
  undefined_syms.txt
Labels: Overlay

#307 En_Floormas
  include/functions.h
  spec
  src/overlays/actors/ovl_En_Floormas/z_en_floormas.c
  src/overlays/actors/ovl_En_Floormas/z_en_floormas.h
  tools/disasm/functions.txt
Labels: Overlay

#284 Texture alignment macros
  include/command_macros_base.h
  include/macros.h
Labels: Clean up

#324 Boss_02 (3 non-matching)
  include/functions.h
  include/variables.h
  spec
  src/overlays/actors/ovl_Boss_02/z_boss_02.c
  src/overlays/actors/ovl_Boss_02/z_boss_02.h
  src/overlays/actors/ovl_Door_Warp1/z_door_warp1.h
  tools/actorfixer.py
  tools/disasm/variables.txt
  undefined_syms.txt
Labels: Overlay

#351 En_Baguo (Nejiron) OK and mostly documented
  spec
  src/overlays/actors/ovl_En_Baguo/z_en_baguo.c
  src/overlays/actors/ovl_En_Baguo/z_en_baguo.h
  tools/disasm/functions.txt
  undefined_syms.txt
Labels: Overlay

#417 xlitob.c OK
  include/variables.h
  include/xstdio.h
  include/z64.h
  spec
  src/libultra/rmon/xlitob.c
  src/libultra/rmon/xprintf.c
  tools/disasm/variables.txt
Labels: boot

#404 EnvFlags OK
  include/functions.h
  spec
  src/code/code_800F12D0.c
  src/code/z_env_flags.c
  src/overlays/actors/ovl_Door_Ana/z_door_ana.c
  tools/disasm/files.txt
  tools/disasm/functions.txt
Labels: code

#396 Add `stddef.h` and libc headers cleanup
  Makefile
  include/assert.h
  include/convert.h
  include/functions.h
  include/ichain.h
  include/libc/alloca.h
  include/libc/assert.h
  include/libc/math.h
  include/libc/stdarg.h
  include/libc/stdbool.h
  include/libc/stddef.h
  include/libc/stdint.h
  include/libc/stdlib.h
  include/macros.h
  include/os.h
  include/osint.h
  include/xstdio.h
  include/z64.h
  src/libultra/gu/cosf.c
  src/libultra/gu/sinf.c
  src/libultra/gu/sins.c
  src/libultra/os/virtualtophysical.c
  src/overlays/gamestates/ovl_select/z_select.c
Labels: Clean up

#397 `motor.c` OK
  include/functions.h
  include/io/controller.h
  include/ultra64/motor.h
  include/variables.h
  spec
  src/boot_O1/viextendvstart.c
  src/code/padmgr.c
  src/libultra/io/motor.c
  src/libultra/io/rumblepak.c
  tools/disasm/files.txt
  tools/disasm/functions.txt
  tools/sizes/boot_functions.csv
Labels: boot

#355 En_hakurock rOcK
  spec
  src/overlays/actors/ovl_Boss_Hakugin/z_boss_hakugin.h
  src/overlays/actors/ovl_En_Hakurock/z_en_hakurock.c
  src/overlays/actors/ovl_En_Hakurock/z_en_hakurock.h
  tools/disasm/functions.txt
Labels: Overlay

#386 vigetcurrframebuf OK
  include/functions.h
  include/viint.h
  src/libultra/io/vigetcurrframebuf.c
Labels: boot

#430 pfsisplug OK
  include/io/controller.h
  src/libultra/io/contquery.c
  src/libultra/io/contreaddata.c
  src/libultra/io/controller.c
  src/libultra/io/contsetch.c
  src/libultra/io/motor.c
  src/libultra/io/pfsisplug.c
  src/libultra/voice/voicegetstatus.c
  tools/disasm/variables.txt
Labels: boot

#438 Transfer osViModes to C files
  include/variables.h
  spec
  src/libultra/io/osViModeMpalLan1.c
  src/libultra/io/osViModeNtscHpf1.c
  src/libultra/io/osViModeNtscLan1.c
  src/libultra/io/osViModePalLan1.c
  src/libultra/io/vi.c
  tools/disasm/files.txt
Labels: boot

#426 guS2DInitBg OK
  include/ultra64/gs2dex.h
  include/z64.h
  src/boot_O2_g3/idle.c
  src/libultra/gu/guS2DInitBg.c
Labels: boot

#429 pfschecker OK
  include/PR/pfs.h
  include/functions.h
  src/libultra/io/contpfs.c
  src/libultra/io/pfschecker.c
Labels: boot

#424 pfsdeletefile OK
  src/libultra/io/pfsdeletefile.c
Labels: boot

#422 pfsfilestate OK
  src/libultra/io/pfsfilestate.c
Labels: boot

#409 CRC files OK and documented
  include/functions.h
  src/libultra/io/crc.c
  src/libultra/voice/voicecrc.c
  tools/calc_bss.sh
Labels: boot

#421 vimgr OK
  include/functions.h
  include/os.h
  include/osint.h
  include/variables.h
  spec
  src/libultra/io/vimgr.c
  src/libultra/voice/voicecontrolgain.c
  tools/disasm/files.txt
Labels: boot

#420 pfsselectbank OK
  src/libultra/io/pfsselectbank.c
Labels: boot

#411 epiwrite.c OK
  src/libultra/io/epirawwrite.c
  src/libultra/io/epiwrite.c
Labels: boot

#410 epiread.c OK
  src/libultra/io/epirawread.c
  src/libultra/io/epiread.c
Labels: boot

#425 pfsinitpak OK
  include/PR/pfs.h
  src/libultra/io/pfsinitpak.c
Labels: boot

#451 Use ITEM_MASK_GIBDO enum in En_Hg
  src/overlays/actors/ovl_En_Hg/z_en_hg.c
Labels: Clean up

#309 En_Pm
  include/functions.h
  include/variables.h
  spec
  src/overlays/actors/ovl_En_Dno/z_en_dno.h
  src/overlays/actors/ovl_En_Pm/z_en_pm.c
  src/overlays/actors/ovl_En_Pm/z_en_pm.h
  src/overlays/actors/ovl_En_Suttari/z_en_suttari.c
  undefined_syms.txt
Labels: Overlay

#341 sched.h
  include/PR/sched.h
  include/irqmgr.h
  include/macros.h
  include/scheduler.h
  include/ultra64/vi.h
  include/variables.h
  include/z64.h
  src/code/sched.c
Labels: Clean up

#407 Moves func_800CB000 to z_bg_item, decompiles func_800CB000, and documents z_bg_item and a few DynaPolyActor struct members.
  include/functions.h
  include/z64actor.h
  spec
  src/code/code_800CB000.c
  src/code/z_actor.c
  src/code/z_bg_collect.c
  src/code/z_bg_item.c
  src/overlays/actors/ovl_Bg_Ctower_Gear/z_bg_ctower_gear.c
  src/overlays/actors/ovl_Bg_Ctower_Rot/z_bg_ctower_rot.c
  src/overlays/actors/ovl_Bg_Fu_Kaiten/z_bg_fu_kaiten.c
  src/overlays/actors/ovl_Bg_Haka_Curtain/z_bg_haka_curtain.c
  src/overlays/actors/ovl_Bg_Haka_Tomb/z_bg_haka_tomb.c
  src/overlays/actors/ovl_Bg_Hakugin_Post/z_bg_hakugin_post.c
  src/overlays/actors/ovl_Bg_Icicle/z_bg_icicle.c
  src/overlays/actors/ovl_Bg_Ikana_Shutter/z_bg_ikana_shutter.c
  src/overlays/actors/ovl_Bg_Iknin_Susceil/z_bg_iknin_susceil.c
  src/overlays/actors/ovl_Bg_Iknv_Obj/z_bg_iknv_obj.c
  src/overlays/actors/ovl_Bg_Kin2_Fence/z_bg_kin2_fence.c
  src/overlays/actors/ovl_Bg_Ladder/z_bg_ladder.c
  src/overlays/actors/ovl_Bg_Lbfshot/z_bg_lbfshot.c
  src/overlays/actors/ovl_Bg_Lotus/z_bg_lotus.c
  src/overlays/actors/ovl_Bg_Mbar_Chair/z_bg_mbar_chair.c
  src/overlays/actors/ovl_Bg_Tobira01/z_bg_tobira01.c
  src/overlays/actors/ovl_Dm_Char07/z_dm_char07.c
  src/overlays/actors/ovl_En_Dnb/z_en_dnb.c
  src/overlays/actors/ovl_En_Encount2/z_en_encount2.c
  src/overlays/actors/ovl_En_Fu/z_en_fu.c
  src/overlays/actors/ovl_Obj_Bell/z_obj_bell.c
  src/overlays/actors/ovl_Obj_Etcetera/z_obj_etcetera.c
  src/overlays/actors/ovl_Obj_Ghaka/z_obj_ghaka.c
  src/overlays/actors/ovl_Obj_Hgdoor/z_obj_hgdoor.c
  src/overlays/actors/ovl_Obj_HsStump/z_obj_hsstump.c
  src/overlays/actors/ovl_Obj_Kepn_Koya/z_obj_kepn_koya.c
  src/overlays/actors/ovl_Obj_Kibako2/z_obj_kibako2.c
  src/overlays/actors/ovl_Obj_Lightblock/z_obj_lightblock.c
  src/overlays/actors/ovl_Obj_Raillift/z_obj_raillift.c
  src/overlays/actors/ovl_Obj_Tokei_Step/z_obj_tokei_step.c
  src/overlays/actors/ovl_Obj_Visiblock/z_obj_visiblock.c
  tools/disasm/files.txt
  tools/disasm/functions.txt
  tools/sizes/code_functions.csv
Labels: code

#439 xldtob OK
  src/libultra/rmon/xldtob.c
Labels: boot

#452 EnMm OK
  spec
  src/overlays/actors/ovl_En_Mm/z_en_mm.c
  src/overlays/actors/ovl_En_Mm/z_en_mm.h
Labels: Overlay

#279 En_Kakasi (Scarecrow)
  include/functions.h
  include/z64.h
  spec
  src/overlays/actors/ovl_En_Kakasi/z_en_kakasi.c
  src/overlays/actors/ovl_En_Kakasi/z_en_kakasi.h
  tools/disasm/functions.txt
  undefined_syms.txt
Labels: Overlay

#416 aisetfreq OK, some libultra improvements
  include/ultra64.h
  include/ultra64/hardware.h
  include/ultra64/rdp.h
  include/variables.h
  spec
  src/libultra/gu/normalize.c
  src/libultra/io/aigetlen.c
  src/libultra/io/aisetfreq.c
  src/libultra/io/crc.c
  src/libultra/io/dpgetstat.c
  src/libultra/io/dpsetstat.c
  src/libultra/io/pirawdma.c
  src/libultra/io/si.c
  src/libultra/io/sirawdma.c
  src/libultra/io/sp.c
  src/libultra/io/spgetstat.c
  src/libultra/io/sprawdma.c
  src/libultra/io/spsetstat.c
  src/libultra/io/vi.c
Labels: boot

#456 Audio Files & Data: Fix File/Data Splits and Compiler Flags
  Makefile
  spec
  src/code/audio/audio_effects.c
  src/code/audio/audio_heap.c
  src/code/audio/audio_load.c
  src/code/audio/audio_playback.c
  src/code/audio/audio_seqplayer.c
  src/code/audio/audio_synthesis.c
  src/code/audio/code_80192BE0.c
  src/code/audio/code_80194710.c
  src/code/audio/code_80194790.c
  src/code/audio/code_8019AF00.c
  src/code/audio/code_801A4EB0.c
  src/code/audio/code_801A51F0.c
  src/code/audio/code_801A5BD0.c
  src/code/audio/code_801A7B10.c
  src/code/code_80194710.c
  src/code/code_801AA020.c
  src/code/jpegutils.c
  tools/disasm/files.txt
  tools/disasm/variables.txt
Labels: Clean up, Audio

#408 Sub_S Prototypes and approriate header stuff
  include/functions.h
  include/z64.h
  include/z64actor.h
  include/z64animation.h
  src/code/z_skelanime.c
  src/overlays/actors/ovl_En_Dno/z_en_dno.c
  src/overlays/actors/ovl_En_Dno/z_en_dno.h
  src/overlays/actors/ovl_En_In/z_en_in.c
  src/overlays/actors/ovl_En_In/z_en_in.h
  src/overlays/actors/ovl_En_Ot/z_en_ot.c
  src/overlays/actors/ovl_En_Ot/z_en_ot.h
  src/overlays/actors/ovl_En_Pm/z_en_pm.c
  src/overlays/actors/ovl_En_Pm/z_en_pm.h
  src/overlays/actors/ovl_En_Suttari/z_en_suttari.c
  src/overlays/actors/ovl_En_Suttari/z_en_suttari.h
  src/overlays/actors/ovl_En_Sw/z_en_sw.c
  src/overlays/actors/ovl_En_Sw/z_en_sw.h
Labels: documentation

#414 Add ability to warnings script to just check building (not setup or disasm)
  tools/warnings_count/check_new_warnings.sh
Labels: Tooling

#466 Import Audio Binary Interface (abi.h) Commands from OoT
  include/PR/abi.h
Labels: documentation, Audio

#459 Introducing z64audio.h
  include/variables.h
  include/z64.h
  include/z64audio.h
  tools/disasm/variables.txt
Labels: documentation, Audio

#322 `z_jpeg`, `jpegutils` and `jpegdecoder` OK
  Makefile
  include/functions.h
  include/macros.h
  include/variables.h
  include/z64jpeg.h
  spec
  src/code/code_8010C1B0.c
  src/code/code_801AA020.c
  src/code/jpegdecoder.c
  src/code/jpegutils.c
  src/code/z_jpeg.c
  tools/disasm/files.txt
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/sizes/code_functions.csv
Labels: code

#412 cartrominit OK
  include/os.h
  include/variables.h
  spec
  src/libultra/io/cartrominit.c
  tools/disasm/variables.txt
Labels: boot

#446 m2ctx: Optionally return Player* for Player accesses
  tools/m2ctx.py
Labels: Tooling

#460 Audio BGM Macros
  include/bgm.h
  include/functions.h
  src/code/audio/code_8019AF00.c
  src/code/z_common_data.c
  src/code/z_game_over.c
  src/code/z_scene.c
  src/overlays/actors/ovl_Boss_02/z_boss_02.c
  src/overlays/actors/ovl_En_Bigpo/z_en_bigpo.c
  src/overlays/actors/ovl_En_Dinofos/z_en_dinofos.c
  src/overlays/actors/ovl_En_Elforg/z_en_elforg.c
  src/overlays/actors/ovl_En_Fu/z_en_fu.c
  src/overlays/actors/ovl_En_Guruguru/z_en_guruguru.c
  src/overlays/actors/ovl_En_In/z_en_in.c
  src/overlays/actors/ovl_En_Invadepoh/z_en_invadepoh.c
  src/overlays/actors/ovl_En_Kakasi/z_en_kakasi.c
  src/overlays/actors/ovl_En_Ma4/z_en_ma4.c
  src/overlays/actors/ovl_En_Ma_Yto/z_en_ma_yto.c
  src/overlays/actors/ovl_En_Minifrog/z_en_minifrog.c
  src/overlays/actors/ovl_En_Owl/z_en_owl.c
  src/overlays/actors/ovl_En_Pamera/z_en_pamera.c
  src/overlays/actors/ovl_En_Pametfrog/z_en_pametfrog.c
  src/overlays/actors/ovl_En_Suttari/z_en_suttari.c
  src/overlays/actors/ovl_En_Syateki_Man/z_en_syateki_man.c
  src/overlays/actors/ovl_En_Toto/z_en_toto.c
  src/overlays/gamestates/ovl_select/z_select.c
  src/overlays/gamestates/ovl_title/z_title.c
  tools/disasm/functions.txt
  tools/sizes/code_functions.csv
Labels: documentation, Audio

#338 En_Tk
  include/functions.h
  include/z64.h
  spec
  src/code/z_en_item00.c
  src/overlays/actors/ovl_Bg_Danpei_Movebg/z_bg_danpei_movebg.h
  src/overlays/actors/ovl_En_Door/z_en_door.h
  src/overlays/actors/ovl_En_Fish2/z_en_fish2.c
  src/overlays/actors/ovl_En_Invadepoh/z_en_invadepoh.c
  src/overlays/actors/ovl_En_Pamera/z_en_pamera.c
  src/overlays/actors/ovl_En_Pametfrog/z_en_pametfrog.c
  src/overlays/actors/ovl_En_Pm/z_en_pm.c
  src/overlays/actors/ovl_En_Suttari/z_en_suttari.c
  src/overlays/actors/ovl_En_Tk/z_en_tk.c
  src/overlays/actors/ovl_En_Tk/z_en_tk.h
  undefined_syms.txt
Labels: Overlay
