Repository zeldaret/mm, pull requests merged in 2023-07, with the labels that each got.

#1313 Some partial objects cleanup
  assets/xml/objects/object_dkjail_obj.xml
  assets/xml/objects/object_dor02.xml
  assets/xml/objects/object_dor04.xml
  assets/xml/objects/object_gm.xml
  assets/xml/objects/object_sekihig.xml
  assets/xml/objects/object_sekihil.xml
  assets/xml/objects/object_sekihin.xml
  assets/xml/objects/object_sekihiz.xml
  assets/xml/objects/object_tanron1.xml
  assets/xml/objects/object_tanron4.xml
  assets/xml/objects/object_zog.xml
  src/overlays/actors/ovl_Bg_Dkjail_Ivy/z_bg_dkjail_ivy.c
  src/overlays/actors/ovl_En_Sekihi/z_en_sekihi.c
  src/overlays/actors/ovl_En_Tanron4/z_en_tanron4.c
  src/overlays/actors/ovl_En_Tanron4/z_en_tanron4.h
Labels: Clean up, Asset, Merge-ready

#1314 fix: wrong offset-comments in GraphicsContext
  include/gfx.h
Labels: Clean up, Merge-ready

#1282 Object names rename/comments from the OoT equivalent
  assets/xml/objects/object_bombf.xml
  assets/xml/objects/object_fu.xml
  assets/xml/objects/object_hata.xml
  assets/xml/objects/object_lightswitch.xml
  assets/xml/objects/object_ms.xml
  assets/xml/objects/object_rr.xml
  assets/xml/objects/object_vm.xml
  assets/xml/objects/object_zg.xml
  src/overlays/actors/ovl_En_Bombf/z_en_bombf.c
  src/overlays/actors/ovl_En_Guruguru/z_en_guruguru.c
  src/overlays/actors/ovl_En_Hata/z_en_hata.c
  src/overlays/actors/ovl_En_Hata/z_en_hata.h
  src/overlays/actors/ovl_En_Ms/z_en_ms.c
  src/overlays/actors/ovl_En_Rr/z_en_rr.c
  src/overlays/actors/ovl_En_Vm/z_en_vm.c
Labels: Clean up, Asset, Merge-ready

#1298 `map_static_name` docs
  assets/xml/archives/map_name_static.xml
  include/z64item.h
  include/z64scene.h
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_map.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_scope_NES.c
Labels: Asset, Merge-ready

#1304 `item_name_static` documented and `ItemId` updates
  assets/xml/archives/icon_item_static.xml
  assets/xml/archives/item_name_static.xml
  include/z64actor.h
  include/z64item.h
  include/z64player.h
  src/code/code_8012EC80.c
  src/code/z_draw.c
  src/code/z_elf_message.c
  src/code/z_en_item00.c
  src/code/z_fireobj.c
  src/code/z_parameter.c
  src/code/z_play.c
  src/code/z_player_lib.c
  src/code/z_sram_NES.c
  src/overlays/actors/ovl_Bg_Spdweb/z_bg_spdweb.c
  src/overlays/actors/ovl_Dm_Char02/z_dm_char02.c
  src/overlays/actors/ovl_Elf_Msg6/z_elf_msg6.c
  src/overlays/actors/ovl_En_Bigslime/z_en_bigslime.c
  src/overlays/actors/ovl_En_Butte/z_en_butte.c
  src/overlays/actors/ovl_En_Dekubaba/z_en_dekubaba.c
  src/overlays/actors/ovl_En_GirlA/z_en_girla.c
  src/overlays/actors/ovl_En_Karebaba/z_en_karebaba.c
  src/overlays/actors/ovl_En_Nb/z_en_nb.c
  src/overlays/actors/ovl_En_Owl/z_en_owl.c
  src/overlays/actors/ovl_En_Scopenuts/z_en_scopenuts.c
  src/overlays/actors/ovl_En_Shn/z_en_shn.c
  src/overlays/actors/ovl_En_Slime/z_en_slime.c
  src/overlays/actors/ovl_En_Talk_Gibud/z_en_talk_gibud.c
  src/overlays/actors/ovl_En_Tanron1/z_en_tanron1.c
  src/overlays/actors/ovl_En_Tanron5/z_en_tanron5.c
  src/overlays/actors/ovl_En_Test3/z_en_test3.c
  src/overlays/actors/ovl_En_Tsn/z_en_tsn.c
  src/overlays/actors/ovl_En_Zot/z_en_zot.c
  src/overlays/actors/ovl_Obj_Spidertent/z_obj_spidertent.c
  src/overlays/actors/ovl_Obj_Syokudai/z_obj_syokudai.c
  src/overlays/actors/ovl_Obj_Yasi/z_obj_yasi.c
  src/overlays/actors/ovl_Shot_Sun/z_shot_sun.c
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_debug.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_item.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_mask.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_scope_NES.c
  tools/gitable.py
  tools/namefixer.py
Labels: Asset, Merge-ready

#1315 RequiredScopeTemp Cleanup
  src/code/game.c
  src/overlays/actors/ovl_Bg_Hakugin_Bombwall/z_bg_hakugin_bombwall.c
  src/overlays/actors/ovl_En_In/z_en_in.c
  src/overlays/actors/ovl_En_Minislime/z_en_minislime.c
  src/overlays/actors/ovl_En_Railgibud/z_en_railgibud.c
  src/overlays/actors/ovl_En_Talk_Gibud/z_en_talk_gibud.c
  src/overlays/actors/ovl_En_Zot/z_en_zot.c
  src/overlays/actors/ovl_Obj_Raillift/z_obj_raillift.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Clean up, Merge-ready

#1316 Fidget Tables Docs
  include/z64subs.h
  include/z_en_hy_code.h
  src/code/z_actor.c
  src/code/z_sub_s.c
  src/overlays/actors/ovl_En_Aob_01/z_en_aob_01.c
  src/overlays/actors/ovl_En_Aob_01/z_en_aob_01.h
  src/overlays/actors/ovl_En_Baba/z_en_baba.c
  src/overlays/actors/ovl_En_Baba/z_en_baba.h
  src/overlays/actors/ovl_En_Bba_01/z_en_bba_01.c
  src/overlays/actors/ovl_En_Cne_01/z_en_cne_01.c
  src/overlays/actors/ovl_En_Ds2n/z_en_ds2n.c
  src/overlays/actors/ovl_En_Ds2n/z_en_ds2n.h
  src/overlays/actors/ovl_En_Fsn/z_en_fsn.c
  src/overlays/actors/ovl_En_Fsn/z_en_fsn.h
  src/overlays/actors/ovl_En_Geg/z_en_geg.c
  src/overlays/actors/ovl_En_Geg/z_en_geg.h
  src/overlays/actors/ovl_En_Gm/z_en_gm.c
  src/overlays/actors/ovl_En_Gm/z_en_gm.h
  src/overlays/actors/ovl_En_Go/z_en_go.c
  src/overlays/actors/ovl_En_Go/z_en_go.h
  src/overlays/actors/ovl_En_In/z_en_in.c
  src/overlays/actors/ovl_En_In/z_en_in.h
  src/overlays/actors/ovl_En_Ossan/z_en_ossan.c
  src/overlays/actors/ovl_En_Ossan/z_en_ossan.h
  src/overlays/actors/ovl_En_Rg/z_en_rg.c
  src/overlays/actors/ovl_En_Rg/z_en_rg.h
  src/overlays/actors/ovl_En_Ru/z_en_ru.c
  src/overlays/actors/ovl_En_Ru/z_en_ru.h
  src/overlays/actors/ovl_En_Suttari/z_en_suttari.c
  src/overlays/actors/ovl_En_Suttari/z_en_suttari.h
  src/overlays/actors/ovl_En_Zo/z_en_zo.c
  src/overlays/actors/ovl_En_Zo/z_en_zo.h
  tools/disasm/functions.txt
  tools/namefixer.py
  tools/sizes/code_functions.csv
Labels: documentation, Clean up, Merge-ready

#1199 Port OoT's docs for `fault.c` and `fault_drawer.c`
  include/fault.h
  include/fault_internal.h
  include/functions.h
  include/ultra64/convert.h
  include/ultra64/thread.h
  include/variables.h
  include/z64.h
  include/z64thread.h
  spec
  src/boot_O2/assert.c
  src/boot_O2_g3/CIC6105.c
  src/boot_O2_g3/fault.c
  src/boot_O2_g3/fault_drawer.c
  src/boot_O2_g3/yaz0.c
  src/boot_O2_g3/z_std_dma.c
  src/code/graph.c
  src/code/main.c
  src/code/padmgr.c
  src/code/sched.c
  src/code/sys_flashrom.c
  src/code/sys_initial_check.c
  src/code/sys_matrix.c
  src/code/z_actor.c
  src/code/z_actor_dlftbls.c
  src/code/z_bgcheck.c
  src/code/z_collision_check.c
  src/code/z_demo.c
  src/code/z_kaleido_manager.c
  src/code/z_play.c
  src/code/z_player_lib.c
  src/libultra/os/createthread.c
  src/libultra/os/setthreadpri.c
  src/overlays/actors/ovl_Boss_02/z_boss_02.c
  src/overlays/actors/ovl_En_Ot/z_en_ot.c
  src/overlays/actors/ovl_Obj_Hunsui/z_obj_hunsui.c
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_scope_NES.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/namefixer.py
  tools/sizes/boot_functions.csv
Labels: documentation, Clean up, Merge-ready

#1290 Animation Cleanup Part 1: Dm Actors
  include/functions.h
  src/code/z_actor.c
  src/overlays/actors/ovl_Dm_Ah/z_dm_ah.c
  src/overlays/actors/ovl_Dm_Ah/z_dm_ah.h
  src/overlays/actors/ovl_Dm_Al/z_dm_al.c
  src/overlays/actors/ovl_Dm_Al/z_dm_al.h
  src/overlays/actors/ovl_Dm_An/z_dm_an.c
  src/overlays/actors/ovl_Dm_An/z_dm_an.h
  src/overlays/actors/ovl_Dm_Bal/z_dm_bal.c
  src/overlays/actors/ovl_Dm_Char00/z_dm_char00.c
  src/overlays/actors/ovl_Dm_Char00/z_dm_char00.h
  src/overlays/actors/ovl_Dm_Char02/z_dm_char02.c
  src/overlays/actors/ovl_Dm_Char03/z_dm_char03.c
  src/overlays/actors/ovl_Dm_Char04/z_dm_char04.c
  src/overlays/actors/ovl_Dm_Char04/z_dm_char04.h
  src/overlays/actors/ovl_Dm_Char05/z_dm_char05.c
  src/overlays/actors/ovl_Dm_Char05/z_dm_char05.h
  src/overlays/actors/ovl_Dm_Char06/z_dm_char06.c
  src/overlays/actors/ovl_Dm_Char07/z_dm_char07.c
  src/overlays/actors/ovl_Dm_Char08/z_dm_char08.c
  src/overlays/actors/ovl_Dm_Char08/z_dm_char08.h
  src/overlays/actors/ovl_Dm_Char09/z_dm_char09.c
  src/overlays/actors/ovl_Dm_Gm/z_dm_gm.c
  src/overlays/actors/ovl_Dm_Gm/z_dm_gm.h
  src/overlays/actors/ovl_Dm_Nb/z_dm_nb.c
  src/overlays/actors/ovl_Dm_Nb/z_dm_nb.h
  src/overlays/actors/ovl_Dm_Opstage/z_dm_opstage.c
  src/overlays/actors/ovl_Dm_Ravine/z_dm_ravine.c
  src/overlays/actors/ovl_Dm_Sa/z_dm_sa.c
  src/overlays/actors/ovl_Dm_Stk/z_dm_stk.c
  src/overlays/actors/ovl_Dm_Tag/z_dm_tag.c
  src/overlays/actors/ovl_Dm_Zl/z_dm_zl.c
  tools/disasm/functions.txt
Labels: documentation, Clean up, Merge-ready

#1319 Document EnTanron5 (destructible props, fragments, and item drops in Twinmold's arena)
  assets/xml/objects/object_boss02.xml
  src/overlays/actors/ovl_Boss_02/z_boss_02.c
  src/overlays/actors/ovl_Boss_02/z_boss_02.h
  src/overlays/actors/ovl_En_Tanron5/z_en_tanron5.c
  src/overlays/actors/ovl_En_Tanron5/z_en_tanron5.h
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: documentation, Merge-ready

#1311 Provide original sequence names for all BGM and rename some sequences
  include/sequence.h
  src/audio/code_8019AF00.c
Labels: Clean up, Merge-ready

#1279 Template Docs For Player Action
  include/z64player.h
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: documentation, Merge-ready

#1318 Deku Playground Docs
  assets/xml/objects/object_dnt.xml
  include/functions.h
  include/z64actor.h
  include/z64save.h
  src/code/z_actor.c
  src/code/z_sram_NES.c
  src/overlays/actors/ovl_En_Akindonuts/z_en_akindonuts.c
  src/overlays/actors/ovl_En_Gamelupy/z_en_gamelupy.c
  src/overlays/actors/ovl_En_Gamelupy/z_en_gamelupy.h
  src/overlays/actors/ovl_En_Lift_Nuts/z_en_lift_nuts.c
  src/overlays/actors/ovl_En_Lift_Nuts/z_en_lift_nuts.h
  src/overlays/actors/ovl_En_Scopenuts/z_en_scopenuts.c
  src/overlays/actors/ovl_En_Sellnuts/z_en_sellnuts.c
  tools/disasm/functions.txt
  tools/sizes/code_functions.csv
  tools/weekeventregconvert.py
Labels: documentation, Merge-ready

#1323 Add original asset names to all `object_g*` files
  assets/xml/objects/object_ge1.xml
  assets/xml/objects/object_geldb.xml
  assets/xml/objects/object_gg.xml
  assets/xml/objects/object_ghaka.xml
  assets/xml/objects/object_gk.xml
  assets/xml/objects/object_gla.xml
  assets/xml/objects/object_goroiwa.xml
  assets/xml/objects/object_goronswitch.xml
Labels: Asset, Merge-ready

#1324 schedule_static docs
  assets/xml/interface/schedule_static.xml
  src/code/z_play_hireso.c
Labels: Asset, Merge-ready

#1308 ClearTag Params Cleanup
  include/z64actor.h
  src/overlays/actors/ovl_Boss_04/z_boss_04.c
  src/overlays/actors/ovl_En_Am/z_en_am.c
  src/overlays/actors/ovl_En_Baguo/z_en_baguo.c
  src/overlays/actors/ovl_En_Bat/z_en_bat.c
  src/overlays/actors/ovl_En_Bb/z_en_bb.c
  src/overlays/actors/ovl_En_Bbfall/z_en_bbfall.c
  src/overlays/actors/ovl_En_Bigokuta/z_en_bigokuta.c
  src/overlays/actors/ovl_En_Bigpo/z_en_bigpo.c
  src/overlays/actors/ovl_En_Bigslime/z_en_bigslime.c
  src/overlays/actors/ovl_En_Bom/z_en_bom.c
  src/overlays/actors/ovl_En_Bombal/z_en_bombal.c
  src/overlays/actors/ovl_En_Bombf/z_en_bombf.c
  src/overlays/actors/ovl_En_Clear_Tag/z_en_clear_tag.c
  src/overlays/actors/ovl_En_Clear_Tag/z_en_clear_tag.h
  src/overlays/actors/ovl_En_Col_Man/z_en_col_man.c
  src/overlays/actors/ovl_En_Crow/z_en_crow.c
  src/overlays/actors/ovl_En_Dekubaba/z_en_dekubaba.c
  src/overlays/actors/ovl_En_Dekunuts/z_en_dekunuts.c
  src/overlays/actors/ovl_En_Dinofos/z_en_dinofos.c
  src/overlays/actors/ovl_En_Dodongo/z_en_dodongo.c
  src/overlays/actors/ovl_En_Egol/z_en_egol.c
  src/overlays/actors/ovl_En_Encount2/z_en_encount2.c
  src/overlays/actors/ovl_En_Fall/z_en_fall.c
  src/overlays/actors/ovl_En_Firefly/z_en_firefly.c
  src/overlays/actors/ovl_En_Floormas/z_en_floormas.c
  src/overlays/actors/ovl_En_Grasshopper/z_en_grasshopper.c
  src/overlays/actors/ovl_En_Ik/z_en_ik.c
  src/overlays/actors/ovl_En_Kaizoku/z_en_kaizoku.c
  src/overlays/actors/ovl_En_Kame/z_en_kame.c
  src/overlays/actors/ovl_En_Karebaba/z_en_karebaba.c
  src/overlays/actors/ovl_En_Pametfrog/z_en_pametfrog.c
  src/overlays/actors/ovl_En_Peehat/z_en_peehat.c
  src/overlays/actors/ovl_En_Po_Fusen/z_en_po_fusen.c
  src/overlays/actors/ovl_En_Po_Sisters/z_en_po_sisters.c
  src/overlays/actors/ovl_En_Poh/z_en_poh.c
  src/overlays/actors/ovl_En_Pp/z_en_pp.c
  src/overlays/actors/ovl_En_Pr/z_en_pr.c
  src/overlays/actors/ovl_En_Raf/z_en_raf.c
  src/overlays/actors/ovl_En_Rr/z_en_rr.c
  src/overlays/actors/ovl_En_Slime/z_en_slime.c
  src/overlays/actors/ovl_En_Snowman/z_en_snowman.c
  src/overlays/actors/ovl_En_St/z_en_st.c
  src/overlays/actors/ovl_En_Suttari/z_en_suttari.c
  src/overlays/actors/ovl_En_Sw/z_en_sw.c
  src/overlays/actors/ovl_En_Thiefbird/z_en_thiefbird.c
  src/overlays/actors/ovl_En_Tite/z_en_tite.c
  src/overlays/actors/ovl_En_Wallmas/z_en_wallmas.c
  src/overlays/actors/ovl_En_Wf/z_en_wf.c
  src/overlays/actors/ovl_En_Wiz/z_en_wiz.c
Labels: Clean up, Merge-ready

#1326 Animation Cleanup: En_B* Actors
  assets/xml/objects/object_ani.xml
  assets/xml/objects/object_bigpo.xml
  assets/xml/objects/object_ds2n.xml
  assets/xml/objects/object_hs.xml
  assets/xml/objects/object_po_sisters.xml
  assets/xml/objects/object_ru2.xml
  assets/xml/objects/object_yb.xml
  src/overlays/actors/ovl_En_Baba/z_en_baba.c
  src/overlays/actors/ovl_En_Baguo/z_en_baguo.c
  src/overlays/actors/ovl_En_Baguo/z_en_baguo.h
  src/overlays/actors/ovl_En_Baisen/z_en_baisen.c
  src/overlays/actors/ovl_En_Baisen/z_en_baisen.h
  src/overlays/actors/ovl_En_Bb/z_en_bb.c
  src/overlays/actors/ovl_En_Bba_01/z_en_bba_01.c
  src/overlays/actors/ovl_En_Bbfall/z_en_bbfall.c
  src/overlays/actors/ovl_En_Bee/z_en_bee.c
  src/overlays/actors/ovl_En_Bee/z_en_bee.h
  src/overlays/actors/ovl_En_Bh/z_en_bh.c
  src/overlays/actors/ovl_En_Bh/z_en_bh.h
  src/overlays/actors/ovl_En_Bigokuta/z_en_bigokuta.c
  src/overlays/actors/ovl_En_Bigpo/z_en_bigpo.c
  src/overlays/actors/ovl_En_Bigpo/z_en_bigpo.h
  src/overlays/actors/ovl_En_Bigslime/z_en_bigslime.c
  src/overlays/actors/ovl_En_Bigslime/z_en_bigslime.h
  src/overlays/actors/ovl_En_Bji_01/z_en_bji_01.c
  src/overlays/actors/ovl_En_Bjt/z_en_bjt.c
  src/overlays/actors/ovl_En_Boj_01/z_en_boj_01.c
  src/overlays/actors/ovl_En_Boj_02/z_en_boj_02.c
  src/overlays/actors/ovl_En_Boj_03/z_en_boj_03.c
  src/overlays/actors/ovl_En_Boj_04/z_en_boj_04.c
  src/overlays/actors/ovl_En_Boj_05/z_en_boj_05.c
  src/overlays/actors/ovl_En_Bom_Bowl_Man/z_en_bom_bowl_man.c
  src/overlays/actors/ovl_En_Bom_Bowl_Man/z_en_bom_bowl_man.h
  src/overlays/actors/ovl_En_Bombers/z_en_bombers.c
  src/overlays/actors/ovl_En_Bombers/z_en_bombers.h
  src/overlays/actors/ovl_En_Bombers2/z_en_bombers2.c
  src/overlays/actors/ovl_En_Bombers2/z_en_bombers2.h
  src/overlays/actors/ovl_En_Bomjima/z_en_bomjima.c
  src/overlays/actors/ovl_En_Bomjima/z_en_bomjima.h
  src/overlays/actors/ovl_En_Bomjimb/z_en_bomjimb.c
  src/overlays/actors/ovl_En_Bomjimb/z_en_bomjimb.h
  src/overlays/actors/ovl_En_Box/z_en_box.c
  src/overlays/actors/ovl_En_Butte/z_en_butte.c
  src/overlays/actors/ovl_En_Butte/z_en_butte.h
  src/overlays/actors/ovl_En_Famos/z_en_famos.c
  src/overlays/actors/ovl_En_Famos/z_en_famos.h
  src/overlays/actors/ovl_En_Kakasi/z_en_kakasi.c
  src/overlays/actors/ovl_En_Kakasi/z_en_kakasi.h
  src/overlays/actors/ovl_En_Niw/z_en_niw.c
  src/overlays/actors/ovl_En_Niw/z_en_niw.h
  src/overlays/actors/ovl_En_Po_Sisters/z_en_po_sisters.c
  src/overlays/actors/ovl_En_Raf/z_en_raf.c
  src/overlays/actors/ovl_En_Raf/z_en_raf.h
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: Clean up, Merge-ready

#1330 Add original asset names to all `object_h*` files
  assets/xml/objects/object_ha.xml
  assets/xml/objects/object_haka_obj.xml
  assets/xml/objects/object_hakaisi.xml
  assets/xml/objects/object_hakugin_demo.xml
  assets/xml/objects/object_hakugin_obj.xml
  assets/xml/objects/object_hana.xml
  assets/xml/objects/object_harfgibud.xml
  assets/xml/objects/object_hariko.xml
  assets/xml/objects/object_hata.xml
  assets/xml/objects/object_hgdoor.xml
  assets/xml/objects/object_hintnuts.xml
  assets/xml/objects/object_horse_game_check.xml
  assets/xml/objects/object_horse_link_child.xml
  assets/xml/objects/object_hs.xml
  assets/xml/objects/object_hsstump.xml
  assets/xml/objects/object_hunsui.xml
Labels: Asset, Merge-ready

#1325 Shopkeeper weekeventregs
  assets/xml/objects/object_tro.xml
  include/z64save.h
  src/code/z_sram_NES.c
  src/overlays/actors/ovl_En_Baba/z_en_baba.c
  src/overlays/actors/ovl_En_Dnh/z_en_dnh.c
  src/overlays/actors/ovl_En_Dnh/z_en_dnh.h
  src/overlays/actors/ovl_En_Fsn/z_en_fsn.c
  src/overlays/actors/ovl_En_GirlA/z_en_girla.c
  src/overlays/actors/ovl_En_Ossan/z_en_ossan.c
  src/overlays/actors/ovl_En_Sob1/z_en_sob1.c
  src/overlays/actors/ovl_En_Suttari/z_en_suttari.c
  src/overlays/actors/ovl_En_Test3/z_en_test3.c
  src/overlays/actors/ovl_En_Trt/z_en_trt.c
  src/overlays/actors/ovl_En_Trt2/z_en_trt2.c
  src/overlays/actors/ovl_En_Tru/z_en_tru.c
  tools/disasm/functions.txt
  tools/weekeventregconvert.py
Labels: documentation, Merge-ready

#1321 Clang-Format 14
  Dockerfile
  docs/BUILDING_MACOS.md
  docs/CONTRIBUTING.md
  docs/REVIEWING.md
  docs/tools.md
  docs/tutorial/merging.md
  format.py
  src/code/z_DLF.c
  src/code/z_actor.c
  src/code/z_effect_soft_sprite.c
  src/overlays/actors/ovl_En_Bigslime/z_en_bigslime.c
Labels: Tooling, Merge-ready

#1340 document object_ishi
  assets/xml/objects/object_ishi.xml
  src/overlays/actors/ovl_En_Ishi/z_en_ishi.c
Labels: Asset, Merge-ready

#1344 Remove plural "Limbs" from object decomp example
  docs/tutorial/object_decomp_example.md
Labels: documentation, Merge-ready
