Repository zeldaret/mm, pull requests merged in 2023-06, with the labels that each got.

#1245 `z_horse.c` OK
  include/functions.h
  include/variables.h
  include/z64horse.h
  spec
  src/code/z_actor.c
  src/code/z_horse.c
  src/code/z_sram_NES.c
  src/overlays/actors/ovl_Bg_Umajump/z_bg_umajump.c
  src/overlays/actors/ovl_Bg_Umajump/z_bg_umajump.h
  src/overlays/actors/ovl_En_Cow/z_en_cow.c
  src/overlays/actors/ovl_En_Horse/z_en_horse.c
  src/overlays/actors/ovl_En_Horse/z_en_horse.h
  src/overlays/actors/ovl_En_Horse_Game_Check/z_en_horse_game_check.c
  src/overlays/actors/ovl_En_Horse_Link_Child/z_en_horse_link_child.c
  src/overlays/actors/ovl_En_In/z_en_in.c
  src/overlays/actors/ovl_En_Test4/z_en_test4.c
  src/overlays/actors/ovl_Obj_Um/z_obj_um.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/namefixer.py
  tools/sizes/code_functions.csv
Labels: code, Merge-ready

#1228 ovl_Bg_Keikoku_Spr
  spec
  src/overlays/actors/ovl_Bg_Keikoku_Spr/z_bg_keikoku_spr.c
Labels: Overlay, Merge-ready, Waiting-for-author

#1080 ovl_En_Go OK and documented (Decomp was mostly done already)
  assets/xml/objects/object_hakugin_demo.xml
  assets/xml/objects/object_taisou.xml
  include/z64save.h
  spec
  src/overlays/actors/ovl_Bg_Tobira01/z_bg_tobira01.c
  src/overlays/actors/ovl_En_Geg/z_en_geg.c
  src/overlays/actors/ovl_En_Gk/z_en_gk.c
  src/overlays/actors/ovl_En_Go/z_en_go.c
  src/overlays/actors/ovl_En_Go/z_en_go.h
  src/overlays/actors/ovl_En_S_Goro/z_en_s_goro.c
  tools/disasm/functions.txt
  tools/weekeventregconvert.py
Labels: Overlay, Asset, Merge-ready

#1171 ovl_Bg_F40_Swlift OK and documented. obj_f40_obj documented.
  assets/xml/objects/object_f40_obj.xml
  spec
  src/overlays/actors/ovl_Bg_F40_Block/z_bg_f40_block.c
  src/overlays/actors/ovl_Bg_F40_Flift/z_bg_f40_flift.c
  src/overlays/actors/ovl_Bg_F40_Swlift/z_bg_f40_swlift.c
  src/overlays/actors/ovl_Bg_F40_Swlift/z_bg_f40_swlift.h
Labels: Overlay, Merge-ready

#1261 Match Interface_DrawClock
  src/code/z_parameter.c
  tools/disasm/variables.txt
Labels: code, Merge-ready

#1265 ovl_Eff_Stk decompiled
  spec
  src/overlays/actors/ovl_Eff_Stk/z_eff_stk.c
  src/overlays/actors/ovl_Eff_Stk/z_eff_stk.h
Labels: Overlay, Merge-ready

#1273 Misc cleanup
  include/z64.h
  src/boot_O2/sleep.c
  src/overlays/actors/ovl_En_Al/z_en_al.c
  src/overlays/actors/ovl_En_Encount1/z_en_encount1.c
  src/overlays/actors/ovl_En_Encount1/z_en_encount1.h
  src/overlays/actors/ovl_En_In/z_en_in.c
  src/overlays/actors/ovl_En_Kusa2/z_en_kusa2.c
  src/overlays/actors/ovl_En_Mushi2/z_en_mushi2.c
  src/overlays/actors/ovl_En_Time_Tag/z_en_time_tag.c
  src/overlays/actors/ovl_En_Tru/z_en_tru.c
  src/overlays/actors/ovl_En_Tsn/z_en_tsn.c
  src/overlays/actors/ovl_En_Zos/z_en_zos.c
  src/overlays/actors/ovl_Obj_Chan/z_obj_chan.c
  src/overlays/actors/ovl_Obj_Dhouse/z_obj_dhouse.c
  src/overlays/actors/ovl_Obj_Fireshield/z_obj_fireshield.c
  src/overlays/actors/ovl_Obj_Flowerpot/z_obj_flowerpot.c
  src/overlays/actors/ovl_Obj_Grass_Carry/z_obj_grass_carry.c
  src/overlays/actors/ovl_Obj_Iceblock/z_obj_iceblock.c
  src/overlays/actors/ovl_Obj_Tokei_Step/z_obj_tokei_step.c
Labels: Clean up, Merge-ready

#1250 `z64game.h`
  include/functions.h
  include/macros.h
  include/variables.h
  include/z64.h
  include/z64game.h
  include/z_prenmi.h
  include/z_title_setup.h
  src/code/game.c
  src/code/z_prenmi.c
  src/overlays/gamestates/ovl_daytelop/z_daytelop.c
  src/overlays/gamestates/ovl_daytelop/z_daytelop.h
  src/overlays/gamestates/ovl_file_choose/z_file_select.h
  src/overlays/gamestates/ovl_opening/z_opening.c
  src/overlays/gamestates/ovl_opening/z_opening.h
  src/overlays/gamestates/ovl_select/z_select.h
  src/overlays/gamestates/ovl_title/z_title.h
Labels: Clean up, Merge-ready

#1235 Play_Hireso (Bombers Notebook) OK w/ Docs
  assets/xml/interface/schedule_static.xml
  include/PR/gbi.h
  include/functions.h
  include/macros.h
  include/segment_symbols.h
  include/tables/bombers_notebook/event_table.h
  include/tables/bombers_notebook/person_table.h
  include/variables.h
  include/z64.h
  include/z64bombers_notebook.h
  include/z64message.h
  include/z64save.h
  spec
  src/code/z_kaleido_scope_call.c
  src/code/z_message.c
  src/code/z_play.c
  src/code/z_play_hireso.c
  src/code/z_quake.c
  src/code/z_skelanime.c
  src/overlays/actors/ovl_Bg_Breakwall/z_bg_breakwall.c
  src/overlays/actors/ovl_Bg_Umajump/z_bg_umajump.c
  src/overlays/actors/ovl_En_Ah/z_en_ah.c
  src/overlays/actors/ovl_En_Baba/z_en_baba.c
  src/overlays/actors/ovl_En_Bom_Bowl_Man/z_en_bom_bowl_man.c
  src/overlays/actors/ovl_En_Cow/z_en_cow.c
  src/overlays/actors/ovl_En_Fsn/z_en_fsn.c
  src/overlays/actors/ovl_En_Guruguru/z_en_guruguru.c
  src/overlays/actors/ovl_En_Hs/z_en_hs.c
  src/overlays/actors/ovl_En_Ig/z_en_ig.c
  src/overlays/actors/ovl_En_In/z_en_in.c
  src/overlays/actors/ovl_En_Ma4/z_en_ma4.c
  src/overlays/actors/ovl_En_Ma_Yto/z_en_ma_yto.c
  src/overlays/actors/ovl_En_Ma_Yts/z_en_ma_yts.c
  src/overlays/actors/ovl_En_Mm3/z_en_mm3.c
  src/overlays/actors/ovl_En_Nb/z_en_nb.c
  src/overlays/actors/ovl_En_Pm/z_en_pm.c
  src/overlays/actors/ovl_En_Pst/z_en_pst.c
  src/overlays/actors/ovl_En_Rz/z_en_rz.c
  src/overlays/actors/ovl_En_Stone_heishi/z_en_stone_heishi.c
  src/overlays/actors/ovl_En_Test3/z_en_test3.c
  src/overlays/actors/ovl_En_Test4/z_en_test4.c
  src/overlays/actors/ovl_En_Toto/z_en_toto.c
  src/overlays/actors/ovl_En_Yb/z_en_yb.c
  src/overlays/actors/ovl_Obj_Dinner/z_obj_dinner.c
  src/overlays/actors/ovl_Obj_Milk_Bin/z_obj_milk_bin.c
  src/overlays/actors/ovl_Obj_Um/z_obj_um.c
  src/overlays/actors/ovl_Obj_Usiyane/z_obj_usiyane.c
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_scope_NES.c
  tools/disasm/disasm.py
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/namefixer.py
  tools/permuter_settings.toml
  tools/sizes/code_functions.csv
  tools/weekeventregconvert.py
  undefined_syms.txt
Labels: code, Merge-ready

#1267 Persistent Cycle Weekeventregs
  include/macros.h
  include/z64cutscene.h
  include/z64save.h
  src/code/z_sram_NES.c
  tools/disasm/variables.txt
Labels: documentation, Merge-ready

#1278 Tree Asset Decomp for object_tree
  assets/xml/objects/object_tree.xml
  src/overlays/actors/ovl_Obj_Tree/z_obj_tree.c
Labels: Asset, Merge-ready

#1271 Misc Cleanup 4
  src/audio/lib/heap.c
  src/code/z_camera.c
  src/code/z_fireobj.c
  src/code/z_play.c
  src/code/z_sub_s.c
  src/libultra/io/contpfs.c
  src/overlays/actors/ovl_Dm_Char03/z_dm_char03.c
  src/overlays/actors/ovl_En_Am/z_en_am.c
  src/overlays/actors/ovl_En_Arrow/z_en_arrow.c
  src/overlays/actors/ovl_En_Bb/z_en_bb.c
  src/overlays/actors/ovl_En_Crow/z_en_crow.c
  src/overlays/actors/ovl_En_Dno/z_en_dno.c
  src/overlays/actors/ovl_En_Go/z_en_go.c
  src/overlays/actors/ovl_En_Guard_Nuts/z_en_guard_nuts.c
  src/overlays/actors/ovl_En_Hgo/z_en_hgo.c
  src/overlays/actors/ovl_En_Ik/z_en_ik.c
  src/overlays/actors/ovl_En_Nwc/z_en_nwc.c
  src/overlays/actors/ovl_En_Osk/z_en_osk.c
  src/overlays/actors/ovl_En_Osn/z_en_osn.c
  src/overlays/actors/ovl_En_Pp/z_en_pp.c
  src/overlays/actors/ovl_En_S_Goro/z_en_s_goro.c
  src/overlays/actors/ovl_En_Sb/z_en_sb.c
  src/overlays/actors/ovl_En_Sw/z_en_sw.c
  src/overlays/actors/ovl_En_Syateki_Okuta/z_en_syateki_okuta.c
  src/overlays/actors/ovl_En_Wallmas/z_en_wallmas.c
  src/overlays/actors/ovl_En_Wiz/z_en_wiz.c
  src/overlays/actors/ovl_En_Yb/z_en_yb.c
  src/overlays/actors/ovl_En_Zos/z_en_zos.c
  src/overlays/actors/ovl_En_Zot/z_en_zot.c
  src/overlays/actors/ovl_Obj_Jgame_Light/z_obj_jgame_light.c
  src/overlays/actors/ovl_Obj_Switch/z_obj_switch.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Clean up, Merge-ready

#1264 libultra voice OK
  include/functions.h
  include/io/controller.h
  include/os.h
  include/ultra64.h
  include/ultra64/controller_voice.h
  include/ultra64/os_voice.h
  include/variables.h
  include/z64audio.h
  spec
  src/code/graph.c
  src/code/z_message.c
  src/libultra/io/contreaddata.c
  src/libultra/io/controller.c
  src/libultra/voice/voicecheckresult.c
  src/libultra/voice/voicecheckword.c
  src/libultra/voice/voicecleardictionary.c
  src/libultra/voice/voicecontread2.c
  src/libultra/voice/voicecontread36.c
  src/libultra/voice/voicecontrolgain.c
  src/libultra/voice/voicecontwrite20.c
  src/libultra/voice/voicecontwrite4.c
  src/libultra/voice/voicecrc.c
  src/libultra/voice/voicegetreaddata.c
  src/libultra/voice/voicegetstatus.c
  src/libultra/voice/voiceinit.c
  src/libultra/voice/voicemaskdictionary.c
  src/libultra/voice/voicesetadconverter.c
  src/libultra/voice/voicesetword.c
  src/libultra/voice/voicestartreaddata.c
  src/libultra/voice/voicestopread.c
  tools/disasm/variables.txt
Labels: boot, Merge-ready

#1276 ovl_En_Snowwd decompiled
  assets/xml/objects/object_snowwd.xml
  spec
  src/overlays/actors/ovl_En_Snowwd/z_en_snowwd.c
  src/overlays/actors/ovl_En_Snowwd/z_en_snowwd.h
Labels: Overlay, Needs-lead-approval

#1283 EnSw OK
  spec
  src/overlays/actors/ovl_En_Sw/z_en_sw.c
Labels: Overlay, Merge-ready

#1294 Misc Cleanup 5
  src/audio/lib/effects.c
  src/audio/lib/load.c
  src/audio/lib/playback.c
  src/code/z_eff_tire_mark.c
  src/code/z_parameter.c
  src/overlays/actors/ovl_Bg_Dblue_Waterfall/z_bg_dblue_waterfall.c
  src/overlays/actors/ovl_Bg_Hakugin_Post/z_bg_hakugin_post.c
  src/overlays/actors/ovl_Bg_Last_Bwall/z_bg_last_bwall.c
  src/overlays/actors/ovl_En_Am/z_en_am.c
  src/overlays/actors/ovl_En_Bigpo/z_en_bigpo.c
  src/overlays/actors/ovl_En_Crow/z_en_crow.c
  src/overlays/actors/ovl_En_Elforg/z_en_elforg.c
  src/overlays/actors/ovl_En_Famos/z_en_famos.c
  src/overlays/actors/ovl_En_Fz/z_en_fz.c
  src/overlays/actors/ovl_En_Gk/z_en_gk.c
  src/overlays/actors/ovl_En_Hanabi/z_en_hanabi.c
  src/overlays/actors/ovl_En_Horse_Link_Child/z_en_horse_link_child.c
  src/overlays/actors/ovl_En_Kakasi/z_en_kakasi.c
  src/overlays/actors/ovl_En_Kanban/z_en_kanban.c
  src/overlays/actors/ovl_En_Kusa2/z_en_kusa2.c
  src/overlays/actors/ovl_En_Mkk/z_en_mkk.c
  src/overlays/actors/ovl_En_Nutsball/z_en_nutsball.c
  src/overlays/actors/ovl_En_Osk/z_en_osk.c
  src/overlays/actors/ovl_En_Ot/z_en_ot.c
  src/overlays/actors/ovl_En_Owl/z_en_owl.c
  src/overlays/actors/ovl_En_Slime/z_en_slime.c
  src/overlays/actors/ovl_En_Test7/z_en_test7.c
  src/overlays/actors/ovl_En_Wiz/z_en_wiz.c
  src/overlays/actors/ovl_En_Wiz_Fire/z_en_wiz_fire.c
  src/overlays/actors/ovl_Obj_Switch/z_obj_switch.c
  src/overlays/actors/ovl_Oceff_Wipe2/z_oceff_wipe2.c
Labels: Clean up, Merge-ready

#1293 object_snowwd
  assets/xml/objects/object_snowwd.xml
  src/overlays/actors/ovl_En_Snowwd/z_en_snowwd.c
Labels: Asset

#1288 Document a bug in EnRacedog and add some diagrams to EnRacedog_IsOverFinishLine
  src/overlays/actors/ovl_En_Racedog/z_en_racedog.c
Labels: documentation

#1287 Document EnSyatekiOkuta (Shooting Gallery Octorok)
  assets/xml/overlays/ovl_En_Syateki_Okuta.xml
  src/overlays/actors/ovl_En_Syateki_Man/z_en_syateki_man.c
  src/overlays/actors/ovl_En_Syateki_Man/z_en_syateki_man.h
  src/overlays/actors/ovl_En_Syateki_Okuta/z_en_syateki_okuta.c
  src/overlays/actors/ovl_En_Syateki_Okuta/z_en_syateki_okuta.h
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: documentation, Merge-ready

#1284 Yet another header cleanup
  include/functions.h
  include/global.h
  include/macros.h
  include/variables.h
  include/z64.h
  include/z64actor.h
  include/z64animation_legacy.h
  include/z64collision_check.h
  include/z64game.h
  include/z64interface.h
  include/z64scene.h
  include/z64sound_source.h
  include/z64thread.h
  src/boot_O2_g3/boot_main.c
  src/boot_O2_g3/idle.c
  src/boot_O2_g3/irqmgr.c
  src/boot_O2_g3/z_std_dma.c
  src/code/flg_set.c
  src/code/main.c
  src/code/sched.c
  src/code/sys_flashrom.c
  src/code/sys_slowly.c
  src/code/z_collision_check.c
  src/code/z_nmi_buff.c
  src/code/z_scene.c
  src/code/z_sound_source.c
  tools/disasm/variables.txt
Labels: Clean up, Merge-ready

#1269 Document Song of Time Cutscenes (Test6)
  include/functions.h
  include/z64cutscene.h
  include/z64ocarina.h
  include/z64player.h
  include/z64save.h
  src/code/z_kankyo.c
  src/code/z_play.c
  src/code/z_sram_NES.c
  src/overlays/actors/ovl_En_Kakasi/z_en_kakasi.c
  src/overlays/actors/ovl_En_Test4/z_en_test4.c
  src/overlays/actors/ovl_En_Test6/z_en_test6.c
  src/overlays/actors/ovl_En_Test6/z_en_test6.h
  src/overlays/actors/ovl_En_Test7/z_en_test7.c
  src/overlays/actors/ovl_En_Twig/z_en_twig.c
  src/overlays/actors/ovl_En_Warp_tag/z_en_warp_tag.c
  src/overlays/actors/ovl_Obj_Nozoki/z_obj_nozoki.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/sizes/code_functions.csv
Labels: documentation, Merge-ready

#1255 Add yar (Yaz0 ARchives) support to build system
  Makefile
  assets/xml/archives/icon_item_24_static.xml
  assets/xml/archives/icon_item_static.xml
  assets/xml/archives/item_name_static.xml
  assets/xml/archives/map_grand_static.xml
  assets/xml/archives/map_i_static.xml
  assets/xml/archives/map_name_static.xml
  assets/xml/archives/schedule_dma_static.xml
  include/segment_symbols.h
  include/tables/bombers_notebook/person_table.h
  spec
  src/code/code_8012EC80.c
  src/code/z_play_hireso.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_scope_NES.c
  tools/buildtools/.gitignore
  tools/buildtools/Makefile
  tools/buildtools/elf32.c
  tools/buildtools/elf32.h
  tools/buildtools/makeyar.c
  tools/buildtools/yaz0.h
  tools/decompress_yars.py
  tools/disasm/dma_filenames.txt
  tools/extract_baserom.py
  tools/filelists/mm.us.rev1/all.csv
  tools/filelists/mm.us.rev1/archives.csv
  tools/filelists/mm.us.rev1/deleted.csv
  tools/progress.py
  undefined_syms.txt
Labels: Tooling, Merge-ready, held

#1299 Create an enum for the various `face_reaction` reaction sets
  include/functions.h
  include/z64message.h
  src/code/z_face_reaction.c
  src/overlays/actors/ovl_En_Bombers/z_en_bombers.c
  src/overlays/actors/ovl_En_Bombers2/z_en_bombers2.c
  src/overlays/actors/ovl_En_Bomjima/z_en_bomjima.c
  src/overlays/actors/ovl_En_Ossan/z_en_ossan.c
  src/overlays/actors/ovl_En_Syateki_Man/z_en_syateki_man.c
Labels: documentation, Merge-ready

#1285 object_firefly Decomp
  assets/xml/objects/object_firefly.xml
  src/overlays/actors/ovl_En_Firefly/z_en_firefly.c
  src/overlays/actors/ovl_En_Firefly/z_en_firefly.h
Labels: Asset, Merge-ready

#1300 AudioMgr cleanup
  include/audiomgr.h
  include/functions.h
  include/variables.h
  include/z64.h
  src/code/audio_thread_manager.c
  src/code/game.c
  src/code/main.c
  src/code/z_jpeg.c
  src/libultra/io/devmgr.c
  src/libultra/io/vimgr.c
  tools/disasm/functions.txt
  tools/sizes/code_functions.csv
Labels: Clean up, Merge-ready

#1289 ovl_En_Dnh decompiled
  assets/xml/objects/object_tro.xml
  spec
  src/overlays/actors/ovl_En_Dnh/z_en_dnh.c
  src/overlays/actors/ovl_En_Dnh/z_en_dnh.h
  tools/disasm/variables.txt
Labels: Overlay, Merge-ready

#1302 Cleanup of Shooting Gallery actors
  assets/xml/objects/object_shn.xml
  include/functions.h
  include/z64save.h
  src/code/z_effect_soft_sprite_old_init.c
  src/code/z_sram_NES.c
  src/overlays/actors/ovl_En_Shn/z_en_shn.c
  src/overlays/actors/ovl_En_Syateki_Crow/z_en_syateki_crow.c
  src/overlays/actors/ovl_En_Syateki_Crow/z_en_syateki_crow.h
  src/overlays/actors/ovl_En_Syateki_Dekunuts/z_en_syateki_dekunuts.c
  src/overlays/actors/ovl_En_Syateki_Dekunuts/z_en_syateki_dekunuts.h
  src/overlays/actors/ovl_En_Syateki_Man/z_en_syateki_man.c
  src/overlays/actors/ovl_En_Syateki_Man/z_en_syateki_man.h
  src/overlays/actors/ovl_En_Syateki_Okuta/z_en_syateki_okuta.c
  src/overlays/actors/ovl_En_Syateki_Wf/z_en_syateki_wf.c
  src/overlays/actors/ovl_En_Syateki_Wf/z_en_syateki_wf.h
  src/overlays/effects/ovl_Effect_Ss_Extra/z_eff_ss_extra.c
  src/overlays/effects/ovl_Effect_Ss_Extra/z_eff_ss_extra.h
  tools/disasm/variables.txt
  tools/weekeventregconvert.py
Labels: Clean up, Merge-ready

#1303 Name the weekeventreg that corresponds with the Clock Tower opening
  include/z64save.h
  src/code/z_elf_message.c
  src/overlays/actors/ovl_Dm_Stk/z_dm_stk.c
  src/overlays/actors/ovl_Elf_Msg6/z_elf_msg6.c
  src/overlays/actors/ovl_En_Time_Tag/z_en_time_tag.c
  src/overlays/actors/ovl_Obj_Tokeidai/z_obj_tokeidai.c
  tools/weekeventregconvert.py
Labels: documentation, Merge-ready

#1297 `icon_item_static` and `icon_item_24_static` documented
  assets/xml/archives/icon_item_24_static.xml
  assets/xml/archives/icon_item_static.xml
  assets/xml/objects/object_gi_sword_4.xml
  assets/xml/objects/object_thiefbird.xml
  include/z64item.h
  include/z64player.h
  src/code/code_8012EC80.c
  src/code/z_draw.c
  src/code/z_elf_message.c
  src/code/z_parameter.c
  src/code/z_player_lib.c
  src/code/z_sram_NES.c
  src/overlays/actors/ovl_En_Fsn/z_en_fsn.c
  src/overlays/actors/ovl_En_M_Thunder/z_en_m_thunder.c
  src/overlays/actors/ovl_En_M_Thunder/z_en_m_thunder.h
  src/overlays/actors/ovl_En_Sellnuts/z_en_sellnuts.c
  src/overlays/actors/ovl_En_Thiefbird/z_en_thiefbird.c
  src/overlays/actors/ovl_Obj_Moon_Stone/z_obj_moon_stone.c
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_collect.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_debug.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_map.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_scope_NES.c
  tools/gitable.py
  tools/namefixer.py
  undefined_syms.txt
Labels: Asset, Merge-ready

#1222 Load Docs
  include/color.h
  include/loadfragment.h
  include/macros.h
  include/variables.h
  include/z64load.h
  src/boot_O2/loadfragment.c
  src/boot_O2/loadfragment2.c
  src/code/graph.c
  src/code/z_DLF.c
  src/code/z_actor.c
  src/code/z_actor_dlftbls.c
  src/code/z_effect_soft_sprite.c
  src/code/z_kaleido_manager.c
  src/code/z_lifemeter.c
  src/code/z_overlay.c
  src/overlays/actors/ovl_En_Twig/z_en_twig.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/sizes/boot_functions.csv
Labels: documentation, Clean up, Merge-ready

#1275 Document Player's bgcheck routine
  include/z64bgcheck.h
  include/z64player.h
  src/code/z_bgcheck.c
  src/overlays/actors/ovl_En_Bomjimb/z_en_bomjimb.c
  src/overlays/actors/ovl_En_Horse/z_en_horse.c
  src/overlays/actors/ovl_En_Test3/z_en_test3.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: documentation, Merge-ready

#1272 A few UB fixes
  include/ultra64/viint.h
  src/audio/lib/heap.c
  src/audio/lib/load.c
  src/code/jpegdecoder.c
  src/code/z_parameter.c
  src/code/z_vimode.c
  src/overlays/actors/ovl_En_Horse_Link_Child/z_en_horse_link_child.c
  src/overlays/actors/ovl_Obj_Driftice/z_obj_driftice.c
  src/overlays/actors/ovl_Obj_Driftice/z_obj_driftice.h
  tools/disasm/variables.txt
Labels: Clean up, Merge-ready

#1295 Audio Effects Cleanup
  include/audio/effects.h
  include/functions.h
  include/z64audio.h
  src/audio/lib/effects.c
  src/audio/lib/heap.c
  src/audio/lib/playback.c
  src/audio/lib/seqplayer.c
  src/audio/lib/thread.c
  src/code/z_sram_NES.c
  src/overlays/actors/ovl_Boss_03/z_boss_03.c
  src/overlays/actors/ovl_En_Wood02/z_en_wood02.c
  tools/disasm/functions.txt
  tools/sizes/code_functions.csv
Labels: Clean up, Audio, Merge-ready

#1270 Setup for Player Cutscene Docs
  include/z64player.h
  src/code/z_actor.c
  src/code/z_demo.c
  src/code/z_eventmgr.c
  src/code/z_player_lib.c
  src/overlays/actors/ovl_Boss_03/z_boss_03.c
  src/overlays/actors/ovl_Dm_Tag/z_dm_tag.c
  src/overlays/actors/ovl_En_Ge2/z_en_ge2.c
  src/overlays/actors/ovl_En_Horse/z_en_horse.c
  src/overlays/actors/ovl_En_Kaizoku/z_en_kaizoku.c
  src/overlays/actors/ovl_En_Test3/z_en_test3.c
  src/overlays/actors/ovl_En_Zod/z_en_zod.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: documentation, Merge-ready

#1306 Misc Cleanup 2
  assets/xml/objects/object_bba.xml
  assets/xml/objects/object_eg.xml
  src/overlays/actors/ovl_En_Ssh/z_en_ssh.c
  undefined_syms.txt
Labels: Clean up, Merge-ready

#1301 Import some bss
  include/variables.h
  spec
  src/code/flg_set.c
  src/code/pad_801DC9C0.c
  src/code/z_en_item00.c
  src/code/z_eventmgr.c
  src/overlays/actors/ovl_En_Sda/z_en_sda.c
  src/overlays/actors/ovl_En_Tanron1/z_en_tanron1.c
  tools/disasm/files.txt
  tools/disasm/variables.txt
Labels: Clean up, Merge-ready

#1292 Idle + Main bss and cleanup
  include/functions.h
  include/idle.h
  include/macros.h
  include/main.h
  include/padmgr.h
  include/ultra64/thread.h
  include/variables.h
  include/z64audio.h
  include/z64thread.h
  spec
  src/boot_O2_g3/boot_main.c
  src/boot_O2_g3/idle.c
  src/boot_O2_g3/idle_extra_bss.c
  src/boot_O2_g3/viconfig.c
  src/boot_O2_g3/z_std_dma.c
  src/code/game.c
  src/code/graph.c
  src/code/main.c
  src/code/sched.c
  src/code/sys_ucode.c
  src/code/z_play.c
  src/code/z_prenmi.c
  src/code/z_skin.c
  src/overlays/actors/ovl_Arrow_Fire/z_arrow_fire.c
  src/overlays/actors/ovl_Arrow_Ice/z_arrow_ice.c
  src/overlays/actors/ovl_Arrow_Light/z_arrow_light.c
  src/overlays/actors/ovl_Bg_Iknin_Susceil/z_bg_iknin_susceil.c
  src/overlays/actors/ovl_En_Sda/z_en_sda.c
  src/overlays/actors/ovl_En_Tanron1/z_en_tanron1.c
  src/overlays/actors/ovl_Obj_Hunsui/z_obj_hunsui.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/sizes/boot_functions.csv
Labels: Clean up, Merge-ready

#1310 Some Gameplay keep docs (starts at the top)
  assets/xml/objects/gameplay_keep.xml
  src/code/z_player_lib.c
  src/overlays/actors/ovl_Arms_Hook/z_arms_hook.c
Labels: Asset, Merge-ready
