Repository zeldaret/mm, pull requests merged in 2023-08, with the labels that each got.

#1348 Documentation addendum to `Shot_Sun`
  src/overlays/actors/ovl_Shot_Sun/z_shot_sun.c
  src/overlays/actors/ovl_Shot_Sun/z_shot_sun.h
Labels: Clean up, Merge-ready

#1345 Document the function that handles the Giant's Mask cutscene in Boss02
  src/overlays/actors/ovl_Boss_02/z_boss_02.c
  src/overlays/actors/ovl_Boss_02/z_boss_02.h
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: documentation, Overlay, Merge-ready

#1305 Fix Cutscene Bss
  include/variables.h
  include/z64cutscene.h
  src/code/z_demo.c
Labels: Clean up, Merge-ready

#1332 Animation Cleanup: En_F*
  assets/xml/objects/object_fish.xml
  include/z64save.h
  src/overlays/actors/ovl_En_Bigslime/z_en_bigslime.c
  src/overlays/actors/ovl_En_Fall/z_en_fall.c
  src/overlays/actors/ovl_En_Fall2/z_en_fall2.c
  src/overlays/actors/ovl_En_Famos/z_en_famos.c
  src/overlays/actors/ovl_En_Fg/z_en_fg.c
  src/overlays/actors/ovl_En_Fg/z_en_fg.h
  src/overlays/actors/ovl_En_Fire_Rock/z_en_fire_rock.c
  src/overlays/actors/ovl_En_Fish/z_en_fish.c
  src/overlays/actors/ovl_En_Fish/z_en_fish.h
  src/overlays/actors/ovl_En_Fish2/z_en_fish2.c
  src/overlays/actors/ovl_En_Fish2/z_en_fish2.h
  src/overlays/actors/ovl_En_Fishing/z_en_fishing.c
  src/overlays/actors/ovl_En_Floormas/z_en_floormas.c
  src/overlays/actors/ovl_En_Fsn/z_en_fsn.c
  src/overlays/actors/ovl_En_Fu/z_en_fu.c
  src/overlays/actors/ovl_En_Fu/z_en_fu.h
  src/overlays/actors/ovl_En_Fu_Kago/z_en_fu_kago.c
  src/overlays/actors/ovl_En_Minifrog/z_en_minifrog.c
  src/overlays/actors/ovl_En_Minifrog/z_en_minifrog.h
  src/overlays/actors/ovl_En_Pametfrog/z_en_pametfrog.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: Clean up, Merge-ready

#1259 `z64vi*.h` and `sys_cfb.h` headers
  include/functions.h
  include/padmgr.h
  include/prevent_bss_reordering2.h
  include/sys_cfb.h
  include/variables.h
  include/z64.h
  include/z64vimode.h
  include/z64viscvg.h
  include/z64vismono.h
  include/z64viszbuf.h
  src/boot_O2_g3/CIC6105.c
  src/boot_O2_g3/fault.c
  src/code/game.c
  src/code/graph.c
  src/code/sys_cfb.c
  src/code/z_actor.c
  src/code/z_fbdemo_circle.c
  src/code/z_lights.c
  src/code/z_parameter.c
  src/code/z_play.c
  src/code/z_play_hireso.c
  src/code/z_player_call.c
  src/code/z_rcp.c
  src/code/z_scene_proc.c
  src/code/z_skin.c
  src/code/z_vimode.c
  src/code/z_viscvg.c
  src/code/z_vismono.c
  src/code/z_viszbuf.c
  src/libultra/flash/osFlash.c
  src/overlays/actors/ovl_Boss_06/z_boss_06.c
  src/overlays/actors/ovl_En_Kusa2/z_en_kusa2.c
  src/overlays/actors/ovl_En_Test3/z_en_test3.c
  src/overlays/fbdemos/ovl_fbdemo_wipe5/z_fbdemo_wipe5.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_scope_NES.c
  tools/disasm/files.txt
  tools/disasm/variables.txt
Labels: Clean up, Merge-ready

#1339 document object_fr
  assets/xml/objects/object_fr.xml
  src/overlays/actors/ovl_En_Fg/z_en_fg.c
  src/overlays/actors/ovl_En_Fg/z_en_fg.h
  src/overlays/actors/ovl_En_Minifrog/z_en_minifrog.c
  src/overlays/actors/ovl_En_Minifrog/z_en_minifrog.h
Labels: Asset, Merge-ready

#1331 Animation Cleanup: En_E*
  src/overlays/actors/ovl_En_Bb/z_en_bb.c
  src/overlays/actors/ovl_En_Bbfall/z_en_bbfall.c
  src/overlays/actors/ovl_En_Bigokuta/z_en_bigokuta.c
  src/overlays/actors/ovl_En_Bigpo/z_en_bigpo.c
  src/overlays/actors/ovl_En_Bigslime/z_en_bigslime.c
  src/overlays/actors/ovl_En_Bombal/z_en_bombal.c
  src/overlays/actors/ovl_En_Egol/z_en_egol.c
  src/overlays/actors/ovl_En_Egol/z_en_egol.h
  src/overlays/actors/ovl_En_Elf/z_en_elf.c
  src/overlays/actors/ovl_En_Elf/z_en_elf.h
  src/overlays/actors/ovl_En_Elfgrp/z_en_elfgrp.c
  src/overlays/actors/ovl_En_Elforg/z_en_elforg.c
  src/overlays/actors/ovl_En_Encount1/z_en_encount1.c
  src/overlays/actors/ovl_En_Encount2/z_en_encount2.c
  src/overlays/actors/ovl_En_Encount4/z_en_encount4.c
  src/overlays/actors/ovl_En_Ending_Hero/z_en_ending_hero.c
  src/overlays/actors/ovl_En_Ending_Hero/z_en_ending_hero.h
  src/overlays/actors/ovl_En_Ending_Hero2/z_en_ending_hero2.c
  src/overlays/actors/ovl_En_Ending_Hero2/z_en_ending_hero2.h
  src/overlays/actors/ovl_En_Ending_Hero3/z_en_ending_hero3.c
  src/overlays/actors/ovl_En_Ending_Hero3/z_en_ending_hero3.h
  src/overlays/actors/ovl_En_Ending_Hero4/z_en_ending_hero4.c
  src/overlays/actors/ovl_En_Ending_Hero4/z_en_ending_hero4.h
  src/overlays/actors/ovl_En_Ending_Hero5/z_en_ending_hero5.c
  src/overlays/actors/ovl_En_Ending_Hero5/z_en_ending_hero5.h
  src/overlays/actors/ovl_En_Ending_Hero6/z_en_ending_hero6.c
  src/overlays/actors/ovl_En_Ending_Hero6/z_en_ending_hero6.h
  src/overlays/actors/ovl_En_Estone/z_en_estone.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: Clean up, Merge-ready

#1343 document object_dinofos
  assets/xml/objects/object_dinofos.xml
  src/overlays/actors/ovl_En_Dinofos/z_en_dinofos.c
  src/overlays/actors/ovl_En_Dinofos/z_en_dinofos.h
Labels: Asset, Merge-ready

#1352 Tools: add assets/xml folder to `rename_sym.sh` directories
  tools/rename_sym.sh
Labels: Tooling, Merge-ready

#1349 Document object_tl (Snapper)
  assets/xml/objects/object_tl.xml
  src/overlays/actors/ovl_En_Bigpamet/z_en_bigpamet.c
  src/overlays/actors/ovl_En_Bigpamet/z_en_bigpamet.h
  src/overlays/actors/ovl_En_Kame/z_en_kame.c
  src/overlays/actors/ovl_En_Kame/z_en_kame.h
Labels: Asset, Merge-ready

#1354 Gamestate table
  include/macros.h
  include/segment_symbols.h
  include/tables/gamestate_table.h
  include/variables.h
  include/z64game.h
  src/code/graph.c
  src/code/z_game_dlftbls.c
  src/overlays/actors/ovl_Dm_Char01/z_dm_char01.c
Labels: Clean up, Merge-ready

#1277 EnMnk OK and partially documented. handing off to the next ape enthusiast
  assets/xml/objects/object_mnk.xml
  spec
  src/overlays/actors/ovl_En_Mnk/z_en_mnk.c
  src/overlays/actors/ovl_En_Mnk/z_en_mnk.h
  undefined_syms.txt
Labels: Overlay, Merge-ready

#1329 Audio Load and Heap Headers
  include/audio/effects.h
  include/audio/heap.h
  include/audio/load.h
  include/audio/soundfont.h
  include/functions.h
  include/z64audio.h
Labels: Clean up, Audio, Merge-ready

#1317 object_bal & EnBal OK and documented
  assets/xml/objects/object_bal.xml
  include/z64save.h
  spec
  src/code/z_sram_NES.c
  src/overlays/actors/ovl_Dm_Bal/z_dm_bal.c
  src/overlays/actors/ovl_Dm_Bal/z_dm_bal.h
  src/overlays/actors/ovl_En_Bal/z_en_bal.c
  src/overlays/actors/ovl_En_Bal/z_en_bal.h
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/weekeventregconvert.py
Labels: Overlay, Asset, Merge-ready

#1355 document object_hana (graveyard flower)
  assets/xml/objects/object_hana.xml
  src/overlays/actors/ovl_Obj_Hana/z_obj_hana.c
Labels: Asset, Merge-ready

#1350 document object_mkk
  assets/xml/objects/object_mkk.xml
  src/overlays/actors/ovl_En_Door/z_en_door.c
  src/overlays/actors/ovl_En_Mkk/z_en_mkk.c
Labels: Asset, Merge-ready

#1358 z_bgcheck OK
  src/code/z_bgcheck.c
Labels: code, Merge-ready

#1327 Animation Cleanup: En_C* and En_D* Actors
  include/z_en_hy_code.h
  src/code/z_en_hy_code.c
  src/overlays/actors/ovl_Dm_Char08/z_dm_char08.c
  src/overlays/actors/ovl_Door_Shutter/z_door_shutter.c
  src/overlays/actors/ovl_En_Cne_01/z_en_cne_01.c
  src/overlays/actors/ovl_En_Col_Man/z_en_col_man.c
  src/overlays/actors/ovl_En_Cow/z_en_cow.c
  src/overlays/actors/ovl_En_Cow/z_en_cow.h
  src/overlays/actors/ovl_En_Crow/z_en_crow.c
  src/overlays/actors/ovl_En_Dai/z_en_dai.c
  src/overlays/actors/ovl_En_Dai/z_en_dai.h
  src/overlays/actors/ovl_En_Daiku/z_en_daiku.c
  src/overlays/actors/ovl_En_Daiku/z_en_daiku.h
  src/overlays/actors/ovl_En_Daiku2/z_en_daiku2.c
  src/overlays/actors/ovl_En_Daiku2/z_en_daiku2.h
  src/overlays/actors/ovl_En_Dekubaba/z_en_dekubaba.c
  src/overlays/actors/ovl_En_Dekunuts/z_en_dekunuts.c
  src/overlays/actors/ovl_En_Demo_heishi/z_en_demo_heishi.c
  src/overlays/actors/ovl_En_Demo_heishi/z_en_demo_heishi.h
  src/overlays/actors/ovl_En_Dg/z_en_dg.c
  src/overlays/actors/ovl_En_Dnh/z_en_dnh.c
  src/overlays/actors/ovl_En_Dnk/z_en_dnk.c
  src/overlays/actors/ovl_En_Dnk/z_en_dnk.h
  src/overlays/actors/ovl_En_Dno/z_en_dno.c
  src/overlays/actors/ovl_En_Dnp/z_en_dnp.c
  src/overlays/actors/ovl_En_Dnq/z_en_dnq.c
  src/overlays/actors/ovl_En_Dnq/z_en_dnq.h
  src/overlays/actors/ovl_En_Dns/z_en_dns.c
  src/overlays/actors/ovl_En_Dns/z_en_dns.h
  src/overlays/actors/ovl_En_Dodongo/z_en_dodongo.c
  src/overlays/actors/ovl_En_Dodongo/z_en_dodongo.h
  src/overlays/actors/ovl_En_Door/z_en_door.c
  src/overlays/actors/ovl_En_Dragon/z_en_dragon.c
  src/overlays/actors/ovl_En_Dragon/z_en_dragon.h
  src/overlays/actors/ovl_En_Drs/z_en_drs.c
  src/overlays/actors/ovl_En_Ds2n/z_en_ds2n.c
  src/overlays/actors/ovl_En_Dy_Extra/z_en_dy_extra.c
  src/overlays/actors/ovl_En_Firefly/z_en_firefly.c
  src/overlays/actors/ovl_En_Floormas/z_en_floormas.c
  src/overlays/actors/ovl_En_Mushi2/z_en_mushi2.c
  src/overlays/actors/ovl_En_Ssh/z_en_ssh.c
  src/overlays/actors/ovl_En_Thiefbird/z_en_thiefbird.c
  src/overlays/actors/ovl_En_Tubo_Trap/z_en_tubo_trap.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: Clean up, Merge-ready

#1353 `En_Horse_Link_Child` and `object_horse_link_child` partially documented.
  assets/xml/objects/object_horse_link_child.xml
  src/overlays/actors/ovl_En_Horse/z_en_horse.c
  src/overlays/actors/ovl_En_Horse_Link_Child/z_en_horse_link_child.c
  src/overlays/actors/ovl_En_Horse_Link_Child/z_en_horse_link_child.h
  tools/disasm/functions.txt
Labels: documentation, Merge-ready

#1360 Small General cleanup
  src/code/z_rcp.c
  src/overlays/actors/ovl_En_Bom/z_en_bom.c
  src/overlays/actors/ovl_En_Bom/z_en_bom.h
  src/overlays/actors/ovl_En_Crow/z_en_crow.c
  src/overlays/actors/ovl_En_Crow/z_en_crow.h
  src/overlays/actors/ovl_En_Ik/z_en_ik.c
  src/overlays/actors/ovl_En_Ik/z_en_ik.h
  src/overlays/actors/ovl_En_Nnh/z_en_nnh.c
  src/overlays/actors/ovl_En_Ruppecrow/z_en_ruppecrow.c
  src/overlays/actors/ovl_En_Ruppecrow/z_en_ruppecrow.h
  src/overlays/actors/ovl_Obj_Comb/z_obj_comb.c
  src/overlays/actors/ovl_Obj_Comb/z_obj_comb.h
  src/overlays/actors/ovl_Obj_Ghaka/z_obj_ghaka.c
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/effects/ovl_Effect_Ss_Fhg_Flash/z_eff_ss_fhg_flash.c
  undefined_syms.txt
Labels: Clean up, Merge-ready

#1356 Game bss and cleanup
  include/functions.h
  include/variables.h
  include/z64game.h
  include/z64speed_meter.h
  spec
  src/code/game.c
  src/code/graph.c
  src/code/sched.c
  src/code/speed_meter.c
  src/code/z_kaleido_setup.c
  src/code/z_play.c
  src/code/z_prenmi.c
  src/overlays/gamestates/ovl_daytelop/z_daytelop.c
  src/overlays/gamestates/ovl_file_choose/z_file_choose_NES.c
  src/overlays/gamestates/ovl_opening/z_opening.c
  src/overlays/gamestates/ovl_select/z_select.c
  src/overlays/gamestates/ovl_title/z_title.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_scope_NES.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/namefixer.py
  tools/sizes/code_functions.csv
Labels: Clean up, Merge-ready

#1351 document remaining door assets
  assets/xml/objects/object_dor01.xml
  assets/xml/objects/object_kinsta2_obj.xml
  assets/xml/objects/object_wdor01.xml
  assets/xml/objects/object_wdor02.xml
  assets/xml/objects/object_wdor03.xml
  src/overlays/actors/ovl_En_Door/z_en_door.c
Labels: Asset, Merge-ready

#1362 ASM_PROC_FORCE
  Makefile
Labels: Tooling, Merge-ready
