Repository zeldaret/mm, pull requests merged in 2023-03, with the labels that each got.

#1174 EnSi OK
  spec
  src/overlays/actors/ovl_En_Si/z_en_si.c
  src/overlays/actors/ovl_En_Si/z_en_si.h
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: Overlay, Merge-ready

#1187 Cleanup Actor Math Helper Functions
  include/functions.h
  src/code/z_actor.c
  src/code/z_en_hy_code.c
  src/code/z_sub_s.c
  src/overlays/actors/ovl_Arms_Hook/z_arms_hook.c
  src/overlays/actors/ovl_Dm_Stk/z_dm_stk.c
  src/overlays/actors/ovl_Door_Shutter/z_door_shutter.c
  src/overlays/actors/ovl_En_Am/z_en_am.c
  src/overlays/actors/ovl_En_Az/z_en_az.c
  src/overlays/actors/ovl_En_Bat/z_en_bat.c
  src/overlays/actors/ovl_En_Bb/z_en_bb.c
  src/overlays/actors/ovl_En_Bigokuta/z_en_bigokuta.c
  src/overlays/actors/ovl_En_Bigpamet/z_en_bigpamet.c
  src/overlays/actors/ovl_En_Bigpo/z_en_bigpo.c
  src/overlays/actors/ovl_En_Bigslime/z_en_bigslime.c
  src/overlays/actors/ovl_En_Boom/z_en_boom.c
  src/overlays/actors/ovl_En_Crow/z_en_crow.c
  src/overlays/actors/ovl_En_Dekunuts/z_en_dekunuts.c
  src/overlays/actors/ovl_En_Dinofos/z_en_dinofos.c
  src/overlays/actors/ovl_En_Dno/z_en_dno.c
  src/overlays/actors/ovl_En_Dodongo/z_en_dodongo.c
  src/overlays/actors/ovl_En_Door/z_en_door.c
  src/overlays/actors/ovl_En_Fall/z_en_fall.c
  src/overlays/actors/ovl_En_Famos/z_en_famos.c
  src/overlays/actors/ovl_En_Firefly/z_en_firefly.c
  src/overlays/actors/ovl_En_Floormas/z_en_floormas.c
  src/overlays/actors/ovl_En_Horse/z_en_horse.c
  src/overlays/actors/ovl_En_Horse_Link_Child/z_en_horse_link_child.c
  src/overlays/actors/ovl_En_Invadepoh/z_en_invadepoh.c
  src/overlays/actors/ovl_En_Kaizoku/z_en_kaizoku.c
  src/overlays/actors/ovl_En_Kame/z_en_kame.c
  src/overlays/actors/ovl_En_Kusa2/z_en_kusa2.c
  src/overlays/actors/ovl_En_Minifrog/z_en_minifrog.c
  src/overlays/actors/ovl_En_Minislime/z_en_minislime.c
  src/overlays/actors/ovl_En_Mkk/z_en_mkk.c
  src/overlays/actors/ovl_En_Neo_Reeba/z_en_neo_reeba.c
  src/overlays/actors/ovl_En_Ot/z_en_ot.c
  src/overlays/actors/ovl_En_Pametfrog/z_en_pametfrog.c
  src/overlays/actors/ovl_En_Peehat/z_en_peehat.c
  src/overlays/actors/ovl_En_Po_Sisters/z_en_po_sisters.c
  src/overlays/actors/ovl_En_Poh/z_en_poh.c
  src/overlays/actors/ovl_En_Railgibud/z_en_railgibud.c
  src/overlays/actors/ovl_En_Rat/z_en_rat.c
  src/overlays/actors/ovl_En_Rd/z_en_rd.c
  src/overlays/actors/ovl_En_Rg/z_en_rg.c
  src/overlays/actors/ovl_En_Snowman/z_en_snowman.c
  src/overlays/actors/ovl_En_Talk_Gibud/z_en_talk_gibud.c
  src/overlays/actors/ovl_En_Test3/z_en_test3.c
  src/overlays/actors/ovl_En_Thiefbird/z_en_thiefbird.c
  src/overlays/actors/ovl_En_Tite/z_en_tite.c
  src/overlays/actors/ovl_En_Tk/z_en_tk.c
  src/overlays/actors/ovl_En_Warp_Uzu/z_en_warp_uzu.c
  src/overlays/actors/ovl_En_Weather_Tag/z_en_weather_tag.c
  src/overlays/actors/ovl_En_Wf/z_en_wf.c
  src/overlays/actors/ovl_Obj_Bigicicle/z_obj_bigicicle.c
  src/overlays/actors/ovl_Obj_Boyo/z_obj_boyo.c
  src/overlays/actors/ovl_Obj_Grass_Carry/z_obj_grass_carry.c
  tools/disasm/functions.txt
  tools/namefixer.py
  tools/sizes/code_functions.csv
Labels: documentation, Clean up, Merge-ready

#1179 `z_fireobj.h` header
  include/functions.h
  include/z64.h
  include/z64light.h
  include/z_fireobj.h
  src/code/graph.c
  src/code/z_fireobj.c
  src/code/z_lifemeter.c
  src/overlays/actors/ovl_Bg_Numa_Hana/z_bg_numa_hana.c
  src/overlays/actors/ovl_Bg_Numa_Hana/z_bg_numa_hana.h
  src/overlays/actors/ovl_Obj_Flowerpot/z_obj_flowerpot.c
Labels: Clean up, Needs-contributor-approval

#1169 Documented `object_sth` and `object_ahg`, both used by `EnSth` (Moon gazer who wants to buy Ocean spiderhouse)
  assets/xml/objects/object_ahg.xml
  assets/xml/objects/object_sth.xml
  assets/xml/overlays/ovl_En_Sth.xml
  include/z64save.h
  src/overlays/actors/ovl_En_Sekihi/z_en_sekihi.c
  src/overlays/actors/ovl_En_Sekihi/z_en_sekihi.h
  src/overlays/actors/ovl_En_Si/z_en_si.c
  src/overlays/actors/ovl_En_Si/z_en_si.h
  src/overlays/actors/ovl_En_Ssh/z_en_ssh.c
  src/overlays/actors/ovl_En_Ssh/z_en_ssh.h
  src/overlays/actors/ovl_En_Sth/z_en_sth.c
  src/overlays/actors/ovl_En_Sth/z_en_sth.h
  src/overlays/actors/ovl_En_Sth2/z_en_sth2.c
  src/overlays/actors/ovl_En_Sth2/z_en_sth2.h
  tools/disasm/functions.txt
  tools/weekeventregconvert.py
Labels: Asset, Merge-ready

#1184 NPC Tracking
  include/functions.h
  include/variables.h
  include/z64.h
  include/z64actor.h
  src/code/z_actor.c
  src/overlays/actors/ovl_En_Ma4/z_en_ma4.c
  src/overlays/actors/ovl_En_Ma4/z_en_ma4.h
  src/overlays/actors/ovl_En_Ma_Yto/z_en_ma_yto.c
  src/overlays/actors/ovl_En_Ma_Yto/z_en_ma_yto.h
  src/overlays/actors/ovl_En_Ma_Yts/z_en_ma_yts.c
  src/overlays/actors/ovl_En_Ma_Yts/z_en_ma_yts.h
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/sizes/code_functions.csv
Labels: documentation, code, Merge-ready

#1188 Reorganize Audio Files & Name Remaining Audio Files
  Makefile
  spec
  src/audio/code_8019AF00.c
  src/audio/lib/aisetnextbuf.c
  src/audio/lib/data.c
  src/audio/lib/dcache.c
  src/audio/lib/effects.c
  src/audio/lib/heap.c
  src/audio/lib/load.c
  src/audio/lib/playback.c
  src/audio/lib/seqplayer.c
  src/audio/lib/synthesis.c
  src/audio/lib/thread.c
  src/audio/sequence.c
  src/audio/session_config.c
  src/audio/sfx.c
  src/audio/sfx_params.c
  src/audio/voice_external.c
  src/audio/voice_internal.c
  src/code/audio/code_801A4EB0.c
  src/code/audio/code_801A51F0.c
  src/code/audio/code_801A7B10.c
  src/code/audio_stop_all_sfx.c
  src/code/audio_thread_manager.c
  tools/disasm/files.txt
  tools/sizes/code_functions.csv
Labels: Audio, Merge-ready

#1182 `z64frameadvance.h`
  include/functions.h
  include/z64.h
  include/z64frameadvance.h
  src/code/z_pause.c
Labels: Clean up, Merge-ready

#1189 Misc cleanup 13
  include/functions.h
  include/variables.h
  include/z64animation.h
  include/z64audio.h
  include/z64bgcheck.h
  include/z64collision_check.h
  include/z64curve.h
  include/z64dma.h
  include/z64effect.h
  include/z64jpeg.h
  include/z64skin.h
  include/z64skybox.h
  include/z64snap.h
  include/z_en_hy_code.h
  include/z_prenmi.h
  include/z_title_setup.h
  src/code/graph.c
  src/code/z_actor_dlftbls.c
  src/code/z_game_dlftbls.c
  src/code/z_kaleido_manager.c
  src/code/z_vr_box.c
  src/code/z_vr_box_draw.c
  src/overlays/actors/ovl_En_Fall/z_en_fall.c
  src/overlays/actors/ovl_En_Invisible_Ruppe/z_en_invisible_ruppe.c
  src/overlays/actors/ovl_En_Invisible_Ruppe/z_en_invisible_ruppe.h
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/sizes/code_functions.csv
Labels: Clean up, Merge-ready

#1185 Debug mode
  include/functions.h
  include/z64.h
  include/z64debug_display.h
  include/z64debug_text.h
  spec
  src/code/game.c
  src/code/z_debug_display.c
  src/code/z_debug_mode.c
  src/code/z_play.c
  src/overlays/actors/ovl_TG_Sw/z_tg_sw.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/sizes/code_functions.csv
Labels: code, Merge-ready

#1200 Progress Script Hotfix
  tools/progress.py
Labels: Tooling

#1193 Stack cleanups
  include/buffers.h
  include/stack.h
  include/variables.h
  src/audio/lib/load.c
  src/audio/session_config.c
  src/boot_O2_g3/boot_main.c
  src/boot_O2_g3/fault.c
  src/boot_O2_g3/idle.c
  src/boot_O2_g3/z_std_dma.c
  src/buffers/gfxpools.c
  src/buffers/gfxstack.c
  src/buffers/gfxyield.c
  src/buffers/heaps.c
  src/code/PreRender.c
  src/code/graph.c
  src/code/main.c
  src/code/sys_cfb.c
  src/code/sys_flashrom.c
  src/code/z_play.c
  src/code/z_sram_NES.c
  src/libultra/io/pimgr.c
  src/libultra/io/vimgr.c
  src/overlays/actors/ovl_En_Wood02/z_en_wood02.c
  src/overlays/actors/ovl_Obj_Grass/z_obj_grass.c
  tools/disasm/variables.txt
Labels: Clean up, Merge-ready

#1178 Rename `GameInfo` to `RegEditor`
  docs/tools.md
  include/functions.h
  include/regs.h
  include/variables.h
  include/z64.h
  src/code/main.c
  src/code/z_debug.c
  src/overlays/actors/ovl_Obj_Nozoki/z_obj_nozoki.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/regconvert.py
  tools/sizes/code_functions.csv
Labels: Clean up, Merge-ready

#1208 Subrepos update
  tools/ZAPD/.gitrepo
  tools/ZAPD/ZAPD/ZTextureAnimation.cpp
  tools/asm-differ/.gitignore
  tools/asm-differ/.gitrepo
  tools/asm-differ/.pre-commit-config.yaml
  tools/asm-differ/README.md
  tools/asm-differ/diff.py
  tools/asm-differ/diff_settings.py
  tools/asm-differ/pyproject.toml
  tools/fado/.gitrepo
  tools/fado/lib/vc_vector/vc_vector.c
  tools/fado/lib/vc_vector/vc_vector.h
  tools/fado/src/main.c
  tools/graphovl/.gitrepo
  tools/graphovl/graphovl.py
Labels: Tooling, Merge-ready

#1202 Audio `seqplayer.c`: AudioSeq_ to AudioScript_
  include/functions.h
  src/audio/lib/effects.c
  src/audio/lib/heap.c
  src/audio/lib/load.c
  src/audio/lib/playback.c
  src/audio/lib/seqplayer.c
  src/audio/lib/synthesis.c
  src/audio/lib/thread.c
  tools/disasm/functions.txt
  tools/sizes/code_functions.csv
Labels: Clean up, Audio, Merge-ready

#1212 subrepo asm-processor
  tools/asm-processor/.gitignore
  tools/asm-processor/.gitrepo
  tools/asm-processor/LICENSE
  tools/asm-processor/README.md
  tools/asm-processor/add-test.sh
  tools/asm-processor/asm_processor.py
  tools/asm-processor/build.py
  tools/asm-processor/compile-test.sh
  tools/asm-processor/run-tests.sh
  tools/asm-processor/tests/ascii.c
  tools/asm-processor/tests/ascii.objdump
  tools/asm-processor/tests/comments.c
  tools/asm-processor/tests/comments.objdump
  tools/asm-processor/tests/force.c
  tools/asm-processor/tests/force.objdump
  tools/asm-processor/tests/kpic-o1.c
  tools/asm-processor/tests/kpic-o1.objdump
  tools/asm-processor/tests/kpic-o2.c
  tools/asm-processor/tests/kpic-o2.objdump
  tools/asm-processor/tests/label-sameline.c
  tools/asm-processor/tests/label-sameline.objdump
  tools/asm-processor/tests/large.c
  tools/asm-processor/tests/large.objdump
  tools/asm-processor/tests/late_rodata_align.c
  tools/asm-processor/tests/late_rodata_align.objdump
  tools/asm-processor/tests/late_rodata_doubles.c
  tools/asm-processor/tests/late_rodata_doubles.objdump
  tools/asm-processor/tests/late_rodata_doubles_mips1.c
  tools/asm-processor/tests/late_rodata_doubles_mips1.objdump
  tools/asm-processor/tests/late_rodata_jtbl.c
  tools/asm-processor/tests/late_rodata_jtbl.objdump
  tools/asm-processor/tests/late_rodata_jtbl_mips1.c
  tools/asm-processor/tests/late_rodata_jtbl_mips1.objdump
  tools/asm-processor/tests/late_rodata_misaligned_doubles.c
  tools/asm-processor/tests/late_rodata_misaligned_doubles.objdump
  tools/asm-processor/tests/line-continuation-separate-file.s
  tools/asm-processor/tests/line-continuation.asmproc.d
  tools/asm-processor/tests/line-continuation.c
  tools/asm-processor/tests/line-continuation.objdump
  tools/asm-processor/tests/o0.c
  tools/asm-processor/tests/o0.objdump
  tools/asm-processor/tests/o2.c
  tools/asm-processor/tests/o2.objdump
  tools/asm-processor/tests/pascal.objdump
  tools/asm-processor/tests/pascal.p
  tools/asm-processor/tests/static-global.c
  tools/asm-processor/tests/static-global.objdump
  tools/asm-processor/tests/static.c
  tools/asm-processor/tests/static.objdump
  tools/asm-processor/tests/test1.c
  tools/asm-processor/tests/test1.objdump
  tools/asm-processor/tests/test2.c
  tools/asm-processor/tests/test2.objdump
  tools/asm-processor/tests/test3.c
  tools/asm-processor/tests/test3.objdump
Labels: Tooling, Merge-ready

#1215 Recomp v0.6
  tools/ido_recomp/linux/5.3/as0
  tools/ido_recomp/linux/5.3/as1
  tools/ido_recomp/linux/5.3/cc
  tools/ido_recomp/linux/5.3/cfe
  tools/ido_recomp/linux/5.3/ugen
  tools/ido_recomp/linux/5.3/ujoin
  tools/ido_recomp/linux/5.3/uld
  tools/ido_recomp/linux/5.3/umerge
  tools/ido_recomp/linux/5.3/uopt
  tools/ido_recomp/linux/5.3/usplit
  tools/ido_recomp/linux/7.1/as0
  tools/ido_recomp/linux/7.1/as1
  tools/ido_recomp/linux/7.1/cc
  tools/ido_recomp/linux/7.1/cfe
  tools/ido_recomp/linux/7.1/ugen
  tools/ido_recomp/linux/7.1/ujoin
  tools/ido_recomp/linux/7.1/uld
  tools/ido_recomp/linux/7.1/umerge
  tools/ido_recomp/linux/7.1/uopt
  tools/ido_recomp/linux/7.1/usplit
  tools/ido_recomp/macos/5.3/as0
  tools/ido_recomp/macos/5.3/as1
  tools/ido_recomp/macos/5.3/cc
  tools/ido_recomp/macos/5.3/cfe
  tools/ido_recomp/macos/5.3/ugen
  tools/ido_recomp/macos/5.3/ujoin
  tools/ido_recomp/macos/5.3/uld
  tools/ido_recomp/macos/5.3/umerge
  tools/ido_recomp/macos/5.3/uopt
  tools/ido_recomp/macos/5.3/usplit
  tools/ido_recomp/macos/7.1/as0
  tools/ido_recomp/macos/7.1/as1
  tools/ido_recomp/macos/7.1/cc
  tools/ido_recomp/macos/7.1/cfe
  tools/ido_recomp/macos/7.1/ugen
  tools/ido_recomp/macos/7.1/ujoin
  tools/ido_recomp/macos/7.1/uld
  tools/ido_recomp/macos/7.1/umerge
  tools/ido_recomp/macos/7.1/uopt
  tools/ido_recomp/macos/7.1/usplit
  tools/ido_recomp/windows/5.3/as0.exe
  tools/ido_recomp/windows/5.3/as1.exe
  tools/ido_recomp/windows/5.3/cc.exe
  tools/ido_recomp/windows/5.3/cfe.exe
  tools/ido_recomp/windows/5.3/ugen.exe
  tools/ido_recomp/windows/5.3/ujoin.exe
  tools/ido_recomp/windows/5.3/uld.exe
  tools/ido_recomp/windows/5.3/umerge.exe
  tools/ido_recomp/windows/5.3/uopt.exe
  tools/ido_recomp/windows/5.3/usplit.exe
  tools/ido_recomp/windows/7.1/as0.exe
  tools/ido_recomp/windows/7.1/as1.exe
  tools/ido_recomp/windows/7.1/cc.exe
  tools/ido_recomp/windows/7.1/cfe.exe
  tools/ido_recomp/windows/7.1/ugen.exe
  tools/ido_recomp/windows/7.1/ujoin.exe
  tools/ido_recomp/windows/7.1/uld.exe
  tools/ido_recomp/windows/7.1/umerge.exe
  tools/ido_recomp/windows/7.1/uopt.exe
  tools/ido_recomp/windows/7.1/usplit.exe
Labels: Tooling, Merge-ready

#1213 Slowly Cleanup
  include/functions.h
  include/slowly.h
  include/z64.h
  src/code/PreRender.c
  src/code/sys_slowly.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/sizes/code_functions.csv
Labels: Clean up, Merge-ready

#1143 z_room (1 non-matching)
  include/functions.h
  include/regs.h
  include/variables.h
  include/z64.h
  include/z64bgcheck.h
  include/z64scene.h
  spec
  src/code/PreRender.c
  src/code/z_actor.c
  src/code/z_parameter.c
  src/code/z_play.c
  src/code/z_player_lib.c
  src/code/z_room.c
  src/code/z_scene.c
  src/overlays/actors/ovl_Door_Shutter/z_door_shutter.c
  src/overlays/actors/ovl_En_Gm/z_en_gm.c
  src/overlays/actors/ovl_En_Holl/z_en_holl.c
  src/overlays/actors/ovl_En_Kusa/z_en_kusa.c
  src/overlays/actors/ovl_En_Kusa2/z_en_kusa2.c
  src/overlays/actors/ovl_En_Test4/z_en_test4.c
  src/overlays/actors/ovl_En_Test7/z_en_test7.c
  src/overlays/actors/ovl_Obj_Flowerpot/z_obj_flowerpot.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/namefixer.py
  tools/sizes/code_functions.csv
Labels: code, Merge-ready, Waiting-for-author

#1219 Updated function names in ovl_En_Bom & added documentation from OoT
  src/overlays/actors/ovl_En_Bom/z_en_bom.c
  src/overlays/actors/ovl_En_Bom/z_en_bom.h
  src/overlays/actors/ovl_En_Famos/z_en_famos.c
  src/overlays/actors/ovl_En_Rat/z_en_rat.c
  tools/disasm/functions.txt
Labels: Merge-ready

#1177 THA docs
  include/functions.h
  include/tha.h
  include/thga.h
  include/z64.h
  src/code/TwoHeadArena.c
  src/code/TwoHeadGfxArena.c
  src/code/game.c
  src/code/graph.c
  src/code/sched.c
  src/code/sys_matrix.c
  src/code/z_bgcheck.c
  src/code/z_debug_mode.c
  src/code/z_effect_soft_sprite.c
  src/code/z_kaleido_manager.c
  src/code/z_map_exp.c
  src/code/z_message.c
  src/code/z_parameter.c
  src/code/z_play.c
  src/code/z_room.c
  src/code/z_scene.c
  src/code/z_sram_NES.c
  src/code/z_vr_box.c
  src/overlays/actors/ovl_En_Twig/z_en_twig.c
  src/overlays/gamestates/ovl_daytelop/z_daytelop.c
  src/overlays/gamestates/ovl_title/z_title.c
  tools/disasm/functions.txt
  tools/namefixer.py
  tools/sizes/code_functions.csv
Labels: documentation, code, Clean up, Merge-ready

#1183 `z64game_over.h`
  include/functions.h
  include/z64.h
  include/z64game_over.h
  include/z64shrink_window.h
  src/code/z_game_over.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_scope_NES.c
Labels: Clean up, Merge-ready

#1192 `z_parameter`: Buttons (part 9)
  include/functions.h
  include/z64interface.h
  include/z64player.h
  include/z64save.h
  src/code/code_8012EC80.c
  src/code/z_parameter.c
  src/code/z_player_lib.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_item.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_scope_NES.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/sizes/code_functions.csv
Labels: code, Merge-ready

#1220 [Doc] small, names for mayor dotour's eye and eyebrow textures
  assets/xml/objects/object_dt.xml
  src/overlays/actors/ovl_En_Ending_Hero/z_en_ending_hero.c
  src/overlays/actors/ovl_En_Ending_Hero6/z_en_ending_hero6.c
Labels: documentation, Asset, Merge-ready

#1223 Update documentation to use updated Z64Utils release + updated directions
  docs/tutorial/documenting.md
  docs/tutorial/images/z64utils_object_analyzer.png
  docs/tutorial/object_decomp.md
  docs/tutorial/object_decomp_example.md
Labels: Tooling, Needs-lead-approval
