Repository zeldaret/mm, pull requests merged in 2023-04, with the labels that each got.

#1221 Actors revert cleanup
  spec
  src/overlays/actors/ovl_Bg_Keikoku_Spr/z_bg_keikoku_spr.c
  src/overlays/actors/ovl_Bg_Lotus/z_bg_lotus.c
  src/overlays/actors/ovl_Bg_Lotus/z_bg_lotus.h
  src/overlays/actors/ovl_Bg_Tobira01/z_bg_tobira01.c
  src/overlays/actors/ovl_Bg_Tobira01/z_bg_tobira01.h
  src/overlays/actors/ovl_Door_Spiral/z_door_spiral.c
  src/overlays/actors/ovl_Door_Spiral/z_door_spiral.h
  src/overlays/actors/ovl_En_Invadepoh/z_en_invadepoh.c
  src/overlays/actors/ovl_En_Invadepoh/z_en_invadepoh.h
  src/overlays/actors/ovl_En_Po_Fusen/z_en_po_fusen.c
  src/overlays/actors/ovl_Item_B_Heart/z_item_b_heart.c
  src/overlays/actors/ovl_Item_B_Heart/z_item_b_heart.h
  src/overlays/actors/ovl_Obj_Boyo/z_obj_boyo.c
  src/overlays/actors/ovl_Obj_Boyo/z_obj_boyo.h
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  undefined_syms.txt
Labels: Clean up, Merge-ready

#1198 Introduce `SaveContext.gameMode` enum
  include/z64save.h
  src/code/z_demo.c
  src/code/z_parameter.c
  src/code/z_play.c
  src/overlays/actors/ovl_En_Light/z_en_light.c
  src/overlays/actors/ovl_En_Mag/z_en_mag.c
  src/overlays/actors/ovl_En_Test4/z_en_test4.c
  src/overlays/gamestates/ovl_daytelop/z_daytelop.c
  src/overlays/gamestates/ovl_opening/z_opening.c
  src/overlays/gamestates/ovl_title/z_title.c
Labels: documentation, Merge-ready

#1175 ovl_En_Slime & object_slime OK and documented
  assets/xml/objects/object_slime.xml
  spec
  src/overlays/actors/ovl_En_Slime/z_en_slime.c
  src/overlays/actors/ovl_En_Slime/z_en_slime.h
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: Overlay, Asset, Merge-ready

#1211 z_viszbuf (code_801420C0) OK
  include/functions.h
  include/variables.h
  include/z64.h
  spec
  src/code/code_801420C0.c
  src/code/game.c
  src/code/z_viszbuf.c
  tools/disasm/files.txt
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/sizes/code_functions.csv
Labels: code, Merge-ready

#1217 Add `--convert-statics=global-with-filename` flag to asm-processor
  Makefile
Labels: Tooling, Merge-ready

#1203 Match `DynaPoly_ExpandSRT`
  include/variables.h
  src/code/z_bgcheck.c
  tools/disasm/variables.txt
Labels: code, Merge-ready

#1216 Angle Conversions
  include/z64math.h
  src/code/sys_math.c
  src/code/sys_math_atan.c
  src/code/sys_matrix.c
  src/code/z_olib.c
  src/code/z_quake.c
  src/code/z_sub_s.c
  src/libultra/gu/position.c
  src/overlays/actors/ovl_Bg_Dblue_Movebg/z_bg_dblue_movebg.c
  src/overlays/actors/ovl_Boss_03/z_boss_03.c
  src/overlays/actors/ovl_Demo_Kankyo/z_demo_kankyo.c
  src/overlays/actors/ovl_En_Akindonuts/z_en_akindonuts.c
  src/overlays/actors/ovl_En_Az/z_en_az.c
  src/overlays/actors/ovl_En_Bombal/z_en_bombal.c
  src/overlays/actors/ovl_En_Bubble/z_en_bubble.c
  src/overlays/actors/ovl_En_Dg/z_en_dg.c
  src/overlays/actors/ovl_En_Egol/z_en_egol.c
  src/overlays/actors/ovl_En_Encount2/z_en_encount2.c
  src/overlays/actors/ovl_En_Estone/z_en_estone.c
  src/overlays/actors/ovl_En_Fishing/z_en_fishing.c
  src/overlays/actors/ovl_En_Gg2/z_en_gg2.c
  src/overlays/actors/ovl_En_Gk/z_en_gk.c
  src/overlays/actors/ovl_En_Gs/z_en_gs.c
  src/overlays/actors/ovl_En_Jg/z_en_jg.c
  src/overlays/actors/ovl_En_Poh/z_en_poh.c
  src/overlays/actors/ovl_En_Racedog/z_en_racedog.c
  src/overlays/actors/ovl_En_Rat/z_en_rat.c
  src/overlays/actors/ovl_En_Ruppecrow/z_en_ruppecrow.c
  src/overlays/actors/ovl_En_Scopecrow/z_en_scopecrow.c
  src/overlays/actors/ovl_En_Scopenuts/z_en_scopenuts.c
  src/overlays/actors/ovl_En_Sellnuts/z_en_sellnuts.c
  src/overlays/actors/ovl_En_Sob1/z_en_sob1.c
  src/overlays/actors/ovl_En_Ssh/z_en_ssh.c
  src/overlays/actors/ovl_En_Suttari/z_en_suttari.c
  src/overlays/actors/ovl_En_Trt2/z_en_trt2.c
  src/overlays/actors/ovl_En_Tru_Mt/z_en_tru_mt.c
  src/overlays/actors/ovl_En_Warp_tag/z_en_warp_tag.c
  src/overlays/actors/ovl_Obj_Chan/z_obj_chan.c
  src/overlays/actors/ovl_Obj_Dora/z_obj_dora.c
  src/overlays/actors/ovl_Obj_HsStump/z_obj_hsstump.c
  src/overlays/actors/ovl_Obj_Warpstone/z_obj_warpstone.c
  src/overlays/effects/ovl_Effect_Ss_Fire_Tail/z_eff_ss_fire_tail.c
  src/overlays/effects/ovl_Effect_Ss_Solder_Srch_Ball/z_eff_ss_solder_srch_ball.c
  tools/namefixer.py
Labels: Clean up, Merge-ready

#1204 `stackcheck.h`
  include/functions.h
  include/stackcheck.h
  include/variables.h
  include/z64.h
  src/boot_O2/stackcheck.c
  src/boot_O2_g3/boot_main.c
  src/boot_O2_g3/fault.c
  src/boot_O2_g3/idle.c
  src/boot_O2_g3/irqmgr.c
  src/boot_O2_g3/z_std_dma.c
  src/code/PreRender.c
  src/code/main.c
  src/code/sched.c
  src/code/sys_flashrom.c
  src/code/sys_slowly.c
  tools/disasm/variables.txt
Labels: Clean up, Merge-ready

#1155 Name some `SurfaceType_` functions
  include/functions.h
  include/sfx.h
  include/ultra64/thread.h
  include/z64bgcheck.h
  src/boot_O2_g3/fault.c
  src/boot_O2_g3/irqmgr.c
  src/boot_O2_g3/z_std_dma.c
  src/code/sched.c
  src/code/z_actor.c
  src/code/z_bgcheck.c
  src/code/z_en_hy_code.c
  src/code/z_message.c
  src/code/z_play.c
  src/code/z_quake.c
  src/libultra/io/pimgr.c
  src/overlays/actors/ovl_Bg_Ikana_Block/z_bg_ikana_block.c
  src/overlays/actors/ovl_Dm_Stk/z_dm_stk.c
  src/overlays/actors/ovl_Door_Warp1/z_door_warp1.c
  src/overlays/actors/ovl_En_Bbfall/z_en_bbfall.c
  src/overlays/actors/ovl_En_Bom/z_en_bom.c
  src/overlays/actors/ovl_En_Bom_Chu/z_en_bom_chu.c
  src/overlays/actors/ovl_En_Dodongo/z_en_dodongo.c
  src/overlays/actors/ovl_En_Elf/z_en_elf.c
  src/overlays/actors/ovl_En_Famos/z_en_famos.c
  src/overlays/actors/ovl_En_Fishing/z_en_fishing.c
  src/overlays/actors/ovl_En_Goroiwa/z_en_goroiwa.c
  src/overlays/actors/ovl_En_Horse/z_en_horse.c
  src/overlays/actors/ovl_En_In/z_en_in.c
  src/overlays/actors/ovl_En_Kame/z_en_kame.c
  src/overlays/actors/ovl_En_Kanban/z_en_kanban.c
  src/overlays/actors/ovl_En_Mm/z_en_mm.c
  src/overlays/actors/ovl_En_Mushi2/z_en_mushi2.c
  src/overlays/actors/ovl_En_Nutsball/z_en_nutsball.c
  src/overlays/actors/ovl_En_Rat/z_en_rat.c
  src/overlays/actors/ovl_En_Ru/z_en_ru.c
  src/overlays/actors/ovl_En_Sw/z_en_sw.c
  src/overlays/actors/ovl_En_Test/z_en_test.c
  src/overlays/actors/ovl_En_Test/z_en_test.h
  src/overlays/actors/ovl_En_Tite/z_en_tite.c
  src/overlays/actors/ovl_En_Tk/z_en_tk.c
  src/overlays/actors/ovl_En_Wf/z_en_wf.c
  src/overlays/actors/ovl_En_Zo/z_en_zo.c
  src/overlays/actors/ovl_En_Zog/z_en_zog.c
  src/overlays/actors/ovl_Obj_Iceblock/z_obj_iceblock.c
  src/overlays/actors/ovl_Obj_Nozoki/z_obj_nozoki.c
  src/overlays/actors/ovl_Obj_Oshihiki/z_obj_oshihiki.c
  src/overlays/actors/ovl_Obj_Skateblock/z_obj_skateblock.c
  src/overlays/effects/ovl_Effect_Ss_Bubble/z_eff_ss_bubble.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/namefixer.py
  tools/sizes/code_functions.csv
Labels: Clean up, Merge-ready

#1142 `z_player_lib`: Dawn of the final PR
  assets/xml/objects/gameplay_keep.xml
  assets/xml/objects/object_link_child.xml
  assets/xml/objects/object_link_goron.xml
  assets/xml/objects/object_link_nuts.xml
  include/functions.h
  include/ultra64/message.h
  include/z64.h
  include/z64animation.h
  include/z64player.h
  src/code/code_8012EC80.c
  src/code/z_actor.c
  src/code/z_eff_tire_mark.c
  src/code/z_play.c
  src/code/z_player_lib.c
  src/code/z_skelanime.c
  src/overlays/actors/ovl_Boss_03/z_boss_03.c
  src/overlays/actors/ovl_En_Fsn/z_en_fsn.c
  src/overlays/actors/ovl_En_Kendo_Js/z_en_kendo_js.c
  src/overlays/actors/ovl_En_Kgy/z_en_kgy.c
  src/overlays/actors/ovl_En_Minifrog/z_en_minifrog.c
  src/overlays/actors/ovl_En_Stone_heishi/z_en_stone_heishi.c
  src/overlays/actors/ovl_En_Tab/z_en_tab.c
  src/overlays/actors/ovl_En_Talk_Gibud/z_en_talk_gibud.c
  src/overlays/actors/ovl_En_Test3/z_en_test3.c
  src/overlays/actors/ovl_En_Trt/z_en_trt.c
  src/overlays/actors/ovl_En_Tru/z_en_tru.c
  src/overlays/actors/ovl_Obj_Um/z_obj_um.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/namefixer.py
  tools/sizes/code_functions.csv
Labels: code, Merge-ready

#1230 Ensure all boss title cards are extracted as IA8
  assets/xml/objects/object_boss03.xml
  assets/xml/objects/object_boss07.xml
  assets/xml/objects/object_boss_hakugin.xml
Labels: Asset, Merge-ready

#1229 Cutscene State Cleanup
  src/code/code_800E8EA0.c
  src/code/z_parameter.c
  src/overlays/actors/ovl_Bg_Iknv_Obj/z_bg_iknv_obj.c
  src/overlays/actors/ovl_Dm_Ah/z_dm_ah.c
  src/overlays/actors/ovl_Dm_Al/z_dm_al.c
  src/overlays/actors/ovl_Dm_An/z_dm_an.c
  src/overlays/actors/ovl_Dm_Char00/z_dm_char00.c
  src/overlays/actors/ovl_Dm_Char02/z_dm_char02.c
  src/overlays/actors/ovl_Dm_Char08/z_dm_char08.c
  src/overlays/actors/ovl_Dm_Char09/z_dm_char09.c
  src/overlays/actors/ovl_Dm_Gm/z_dm_gm.c
  src/overlays/actors/ovl_Dm_Nb/z_dm_nb.c
  src/overlays/actors/ovl_Dm_Stk/z_dm_stk.c
  src/overlays/actors/ovl_En_Dnk/z_en_dnk.c
  src/overlays/actors/ovl_En_Dnp/z_en_dnp.c
  src/overlays/actors/ovl_En_Dnq/z_en_dnq.c
  src/overlays/actors/ovl_En_Dns/z_en_dns.c
  src/overlays/actors/ovl_En_Elf/z_en_elf.c
  src/overlays/actors/ovl_En_Fall/z_en_fall.c
  src/overlays/actors/ovl_En_Gg/z_en_gg.c
  src/overlays/actors/ovl_En_Gk/z_en_gk.c
  src/overlays/actors/ovl_En_Gm/z_en_gm.c
  src/overlays/actors/ovl_En_Go/z_en_go.c
  src/overlays/actors/ovl_En_Hg/z_en_hg.c
  src/overlays/actors/ovl_En_Holl/z_en_holl.c
  src/overlays/actors/ovl_En_Ishi/z_en_ishi.c
  src/overlays/actors/ovl_En_Kusa/z_en_kusa.c
  src/overlays/actors/ovl_En_Mk/z_en_mk.c
  src/overlays/actors/ovl_En_Pamera/z_en_pamera.c
  src/overlays/actors/ovl_En_Pm/z_en_pm.c
  src/overlays/actors/ovl_En_Rg/z_en_rg.c
  src/overlays/actors/ovl_En_Weather_Tag/z_en_weather_tag.c
  src/overlays/actors/ovl_Obj_Hamishi/z_obj_hamishi.c
  src/overlays/actors/ovl_Obj_Tokeidai/z_obj_tokeidai.c
  src/overlays/actors/ovl_Obj_Um/z_obj_um.c
  src/overlays/actors/ovl_Oceff_Wipe5/z_oceff_wipe5.c
  tools/namefixer.py
Labels: Clean up, Merge-ready

#1176 Update `m2ctx.py`
  tools/m2ctx.py
Labels: Tooling, Clean up

#1232 Match Room_DrawCullable
  src/code/z_room.c
Labels: code, Merge-ready
