Repository zeldaret/mm, pull requests merged in 2024-06, with the labels that each got.

#1640 Even more general cleanup
  docs/CONTRIBUTING.md
  docs/tools.md
  linker_scripts/undefined_syms.ld
  src/overlays/actors/ovl_Bg_Dblue_Waterfall/z_bg_dblue_waterfall.c
  src/overlays/actors/ovl_Boss_03/z_boss_03.c
  src/overlays/actors/ovl_Boss_Hakugin/z_boss_hakugin.c
  src/overlays/actors/ovl_En_Bigslime/z_en_bigslime.c
  src/overlays/actors/ovl_En_Floormas/z_en_floormas.c
  src/overlays/actors/ovl_En_Horse/z_en_horse.c
  src/overlays/actors/ovl_En_Pametfrog/z_en_pametfrog.c
  src/overlays/actors/ovl_En_Poh/z_en_poh.c
  src/overlays/actors/ovl_En_Slime/z_en_slime.c
  src/overlays/actors/ovl_Obj_Lightblock/z_obj_lightblock.c
  tools/check_format.sh
  tools/first_diff.py
  tools/fixle.sh
  tools/format.py
  tools/sym_info.py
Labels: Clean up, Merge-ready

#1642 obj_b_heart documentation continuation
  assets/xml/objects/object_b_heart.xml
Labels: Asset, Merge-ready

#1643 Fix LensMode Names
  include/z64actor.h
  src/code/z_actor.c
  src/overlays/actors/ovl_En_Test2/z_en_test2.c
Labels: documentation, Merge-ready

#1495 obj_tab
  assets/xml/objects/object_tab.xml
  src/overlays/actors/ovl_En_Tab/z_en_tab.c
Labels: Asset, Merge-ready

#1644 Small general cleanup
  include/fault.h
  include/libc64/aprintf.h
  include/libc64/sprintf.h
  include/main.h
  include/padmgr.h
  include/padutils.h
  include/segment_symbols.h
  include/z64dma.h
  include/z64effect_ss.h
  include/z64lib.h
  include/z64rumble.h
  include/z64speed_meter.h
  include/z64voice.h
  linker_scripts/undefined_syms.ld
  src/boot/O2/padutils.c
  src/boot/libc64/sprintf.c
  src/boot/z_std_dma.c
  src/code/padmgr.c
  src/code/sys_ucode.c
  src/code/z_bgcheck.c
  src/code/z_camera.c
  src/code/z_demo.c
  src/code/z_vimode.c
  src/overlays/actors/ovl_Boss_01/z_boss_01.c
  tools/m2ctx.py
  tools/warnings_count/.gitignore
  tools/warnings_count/check_new_warnings.sh
Labels: Clean up, Merge-ready

#1032 z_map decompiled
  assets/xml/code/z_map_disp.xml
  assets/xml/objects/gameplay_dangeon_keep.xml
  assets/xml/objects/gameplay_keep.xml
  assets/xml/overlays/ovl_En_Mm2.xml
  assets/xml/overlays/ovl_Oceff_Wipe7.xml
  include/functions.h
  include/regs.h
  include/z64.h
  include/z64interface.h
  include/z64map.h
  include/z64pause_menu.h
  include/z64save.h
  include/z64scene.h
  spec
  src/code/gDPLoadTextureBlock_Runtime.inc.c
  src/code/title_setup.c
  src/code/z_actor.c
  src/code/z_kaleido_setup.c
  src/code/z_map_data.c
  src/code/z_map_disp.c
  src/code/z_map_exp.c
  src/code/z_message.c
  src/code/z_message_nes.c
  src/code/z_parameter.c
  src/code/z_play.c
  src/code/z_room.c
  src/code/z_scene.c
  src/overlays/actors/ovl_Bg_Open_Shutter/z_bg_open_shutter.c
  src/overlays/actors/ovl_Door_Shutter/z_door_shutter.c
  src/overlays/actors/ovl_Door_Shutter/z_door_shutter.h
  src/overlays/actors/ovl_Door_Spiral/z_door_spiral.c
  src/overlays/actors/ovl_En_Door/z_en_door.c
  src/overlays/actors/ovl_En_Door/z_en_door.h
  src/overlays/actors/ovl_En_Elforg/z_en_elforg.c
  src/overlays/actors/ovl_En_Holl/z_en_holl.c
  src/overlays/actors/ovl_En_Kusa/z_en_kusa.c
  src/overlays/actors/ovl_Obj_Hunsui/z_obj_hunsui.c
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/gamestates/ovl_file_choose/z_file_nameset_NES.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_map.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_scope_NES.c
  tools/disasm/files.txt
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/namefixer.py
  tools/sizes/code_functions.csv
Labels: code, Merge-ready

#1645 ovl_En_Death and ovl_En_Minideath
  assets/xml/objects/object_death.xml
  linker_scripts/undefined_syms.ld
  spec
  src/overlays/actors/ovl_En_Death/z_en_death.c
  src/overlays/actors/ovl_En_Death/z_en_death.h
  src/overlays/actors/ovl_En_Minideath/z_en_minideath.c
  src/overlays/actors/ovl_En_Minideath/z_en_minideath.h
  tools/disasm/functions.txt
Labels: Overlay, Merge-ready

#1647 Cleanup the point lighting gbi implementation
  include/PR/gbi.h
Labels: Clean up, Merge-ready

#1650 Format gbi.h, move ucode defines to makefile
  Makefile
  include/PR/gbi.h
  src/code/sys_math3d.c
  src/code/z_bgcheck.c
  src/code/z_lights.c
  src/code/z_map_disp.c
  src/code/z_message.c
  src/overlays/actors/ovl_Dm_Char00/z_dm_char00.c
  src/overlays/actors/ovl_Dm_Char04/z_dm_char04.c
  src/overlays/actors/ovl_En_Invadepoh/z_en_invadepoh.c
  src/overlays/actors/ovl_En_Invadepoh_Demo/z_en_invadepoh_demo.c
  src/overlays/actors/ovl_En_Kusa2/z_en_kusa2.c
  src/overlays/actors/ovl_En_Osk/z_en_osk.c
  src/overlays/actors/ovl_En_Ot/z_en_ot.c
  src/overlays/actors/ovl_En_Zoraegg/z_en_zoraegg.c
  src/overlays/actors/ovl_Obj_Flowerpot/z_obj_flowerpot.c
  tools/calc_bss.sh
Labels: Clean up, Merge-ready

#1641 EnOkuta (Octorok and its projectiles) OK and documented
  assets/xml/overlays/ovl_En_Okuta.xml
  linker_scripts/undefined_syms.ld
  spec
  src/overlays/actors/ovl_En_Bb/z_en_bb.c
  src/overlays/actors/ovl_En_Bb/z_en_bb.h
  src/overlays/actors/ovl_En_Bbfall/z_en_bbfall.c
  src/overlays/actors/ovl_En_Bigokuta/z_en_bigokuta.c
  src/overlays/actors/ovl_En_Okuta/z_en_okuta.c
  src/overlays/actors/ovl_En_Okuta/z_en_okuta.h
  src/overlays/actors/ovl_En_Syateki_Okuta/z_en_syateki_okuta.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: Overlay, Merge-ready

#1646 Add a `z64play.h` header
  diff_settings.py
  include/color.h
  include/functions.h
  include/ichain.h
  include/macros.h
  include/variables.h
  include/z64.h
  include/z64bombers_notebook.h
  include/z64environment.h
  include/z64frameadvance.h
  include/z64lib.h
  include/z64play.h
  src/code/sys_math.c
  src/code/sys_math3d.c
  src/code/z_actor.c
  src/code/z_collision_check.c
  src/code/z_demo.c
  src/code/z_effect.c
  src/code/z_effect_soft_sprite.c
  src/code/z_game_over.c
  src/code/z_kankyo.c
  src/code/z_lib.c
  src/code/z_message.c
  src/code/z_parameter.c
  src/code/z_play.c
  src/code/z_player_lib.c
  src/code/z_scene.c
  src/code/z_sram_NES.c
  src/overlays/actors/ovl_Bg_Crace_Movebg/z_bg_crace_movebg.c
  src/overlays/actors/ovl_Bg_Hakugin_Post/z_bg_hakugin_post.c
  src/overlays/actors/ovl_Bg_Ikana_Rotaryroom/z_bg_ikana_rotaryroom.c
  src/overlays/actors/ovl_Dm_Stk/z_dm_stk.c
  src/overlays/actors/ovl_Door_Ana/z_door_ana.c
  src/overlays/actors/ovl_Door_Warp1/z_door_warp1.c
  src/overlays/actors/ovl_En_Bji_01/z_en_bji_01.c
  src/overlays/actors/ovl_En_Kakasi/z_en_kakasi.c
  src/overlays/actors/ovl_En_Lift_Nuts/z_en_lift_nuts.c
  src/overlays/actors/ovl_En_Nb/z_en_nb.c
  src/overlays/actors/ovl_En_Okarina_Effect/z_en_okarina_effect.c
  src/overlays/actors/ovl_En_Test4/z_en_test4.c
  src/overlays/actors/ovl_En_Test6/z_en_test6.c
  src/overlays/actors/ovl_En_Test7/z_en_test7.c
  src/overlays/actors/ovl_En_Torch2/z_en_torch2.c
  src/overlays/actors/ovl_En_Tru/z_en_tru.c
  src/overlays/actors/ovl_En_Wallmas/z_en_wallmas.c
  src/overlays/actors/ovl_En_Warp_Uzu/z_en_warp_uzu.c
  src/overlays/actors/ovl_En_Warp_tag/z_en_warp_tag.c
  src/overlays/actors/ovl_En_Weather_Tag/z_en_weather_tag.c
  src/overlays/actors/ovl_Obj_Roomtimer/z_obj_roomtimer.c
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_scope_NES.c
Labels: Clean up, Merge-ready
