Repository zeldaret/mm, pull requests merged in 2024-05, with the labels that each got.

#1620 Document missing gDPSetEnvColor
  src/code/z_parameter.c
Labels: documentation, Merge-ready

#1621 CLOSE_DISPS fixes and avoid early return
  src/code/z_eff_blure.c
  src/overlays/actors/ovl_En_Mnk/z_en_mnk.c
  src/overlays/actors/ovl_En_Osn/z_en_osn.c
Labels: Clean up, Merge-ready

#1623 Consolidate text array
  src/overlays/actors/ovl_En_Toto/z_en_toto.c
Labels: Clean up, Merge-ready

#1624 Fix Song of Time frustum Vtx count
  assets/xml/overlays/ovl_Oceff_Wipe.xml
Labels: Clean up, Merge-ready

#1625 Document bug in talk wait animation frame count
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: documentation, Merge-ready

#1618 Use Romfile in place of vromStart and vromEnd in structs
  include/romfile.h
  include/segment_symbols.h
  include/z64actor_dlftbls.h
  include/z64dma.h
  include/z64effect_ss.h
  include/z64game.h
  include/z64pause_menu.h
  include/z64transition.h
  src/boot/z_std_dma.c
  src/code/graph.c
  src/code/z_DLF.c
  src/code/z_actor.c
  src/code/z_actor_dlftbls.c
  src/code/z_effect_soft_sprite.c
  src/code/z_effect_soft_sprite_dlftbls.c
  src/code/z_fbdemo_dlftbls.c
  src/code/z_game_dlftbls.c
  src/code/z_kaleido_manager.c
  src/code/z_overlay.c
  src/dmadata/dmadata.c
Labels: Clean up, Merge-ready

#1626 Remove s32 cast from actionfunc check
  src/overlays/actors/ovl_Obj_Lightswitch/z_obj_lightswitch.c
Labels: Merge-ready

#1627 Consolidate array | z_en_fish2
  src/overlays/actors/ovl_En_Fish2/z_en_fish2.c
Labels: Merge-ready

#1601 Bss script update
  requirements.txt
  tools/check_reordering.py
  tools/global_bss_check.py
Labels: Tooling, Merge-ready

#1631 Remove unnecessary stuff from undefined_syms.txt
  undefined_syms.txt
Labels: Clean up, Merge-ready

#1429 Danpei movebg
  spec
  src/overlays/actors/ovl_Bg_Danpei_Movebg/z_bg_danpei_movebg.c
  src/overlays/actors/ovl_Bg_Danpei_Movebg/z_bg_danpei_movebg.h
  src/overlays/actors/ovl_En_Tk/z_en_tk.c
Labels: Overlay, Merge-ready

#1622 Document Bug in EnMttag_GetCurrentCheckpoint and Cleanup
  src/overlays/actors/ovl_En_Mt_tag/z_en_mt_tag.c
Labels: documentation, Overlay, Merge-ready

#1630 c_keyframe.c decompiled and documented
  assets/xml/objects/gameplay_keep.xml
  include/functions.h
  include/macros.h
  include/z64.h
  include/z64animation.h
  include/z64keyframe.h
  src/code/c_keyframe.c
  src/code/z_collision_check.c
  src/code/z_demo.c
  src/overlays/actors/ovl_Boss_03/z_boss_03.c
  src/overlays/actors/ovl_Demo_Moonend/z_demo_moonend.c
  src/overlays/actors/ovl_Demo_Moonend/z_demo_moonend.h
  src/overlays/actors/ovl_Demo_Syoten/z_demo_syoten.c
  src/overlays/actors/ovl_Demo_Syoten/z_demo_syoten.h
  src/overlays/actors/ovl_Eff_Change/z_eff_change.c
  src/overlays/actors/ovl_Eff_Change/z_eff_change.h
  src/overlays/actors/ovl_En_Fall2/z_en_fall2.c
  src/overlays/actors/ovl_En_Fall2/z_en_fall2.h
  src/overlays/actors/ovl_En_Test/z_en_test.c
  src/overlays/actors/ovl_En_Test/z_en_test.h
  src/overlays/actors/ovl_En_Test7/z_en_test7.c
  src/overlays/actors/ovl_En_Test7/z_en_test7.h
  src/overlays/actors/ovl_Obj_Takaraya_Wall/z_obj_takaraya_wall.c
  tools/disasm/functions.txt
  tools/sizes/code_functions.csv
Labels: code, Merge-ready

#1628 New Romheader format
  Makefile
  include/rom_header.h
  tools/disasm/disasm.py
Labels: Clean up, Merge-ready

#1632 Change tooling for better elf correctness
  Makefile
  include/macro.inc
  linker_scripts/extra.ld
  linker_scripts/undefined_syms.ld
  spec
  tools/asm-processor/.gitrepo
  tools/asm-processor/asm_processor.py
  tools/asm-processor/prelude.inc
  tools/disasm/disasm.py
Labels: Tooling, Merge-ready

#1633 Fix a fake match on `EnSGoro`
  src/overlays/actors/ovl_En_S_Goro/z_en_s_goro.c
Labels: Clean up, Merge-ready

#1634 warnings_count fix
  tools/warnings_count/check_new_warnings.sh
Labels: Tooling, Clean up, Merge-ready

#1629 ovl_En_Wdhand
  assets/xml/objects/object_wdhand.xml
  spec
  src/overlays/actors/ovl_En_Wdhand/z_en_wdhand.c
  src/overlays/actors/ovl_En_Wdhand/z_en_wdhand.h
  tools/disasm/variables.txt
Labels: Overlay, Merge-ready

#1635 Various makefile adjustments
  Makefile
  include/tables/dmadata_table.h
Labels: Tooling, Clean up, Merge-ready

#1636 General cleanup
  include/tables/bombers_notebook/person_table.h
  include/tables/notebook_table.h
  include/z64.h
  include/z64bombers_notebook.h
  src/code/z_actor.c
  src/code/z_message.c
  src/code/z_play_hireso.c
  src/overlays/actors/ovl_En_Sw/z_en_sw.h
  src/overlays/actors/ovl_Obj_Mine/z_obj_mine.h
  src/overlays/actors/ovl_TG_Sw/z_tg_sw.c
  src/overlays/actors/ovl_TG_Sw/z_tg_sw.h
  src/overlays/gamestates/ovl_select/z_select.c
  tools/disasm/functions.txt
Labels: Clean up, Merge-ready

#1639 Use `gcc -E` for `cpp`
  Makefile
  tools/disasm/disasm.py
Labels: Tooling, Merge-ready
