Repository zeldaret/mm, pull requests merged in 2024-02, with the labels that each got.

#1462 A higher level language for schedule scripts
  .gitignore
  Makefile
  docs/schedule_scripting_language.md
  format.py
  include/functions.h
  include/variables.h
  include/z64schedule.h
  src/code/z_schedule.c
  src/overlays/actors/ovl_En_Ah/scheduleScripts.schl
  src/overlays/actors/ovl_En_Ah/z_en_ah.c
  src/overlays/actors/ovl_En_Al/scheduleScripts.schl
  src/overlays/actors/ovl_En_Al/z_en_al.c
  src/overlays/actors/ovl_En_An/scheduleScripts.schl
  src/overlays/actors/ovl_En_An/z_en_an.c
  src/overlays/actors/ovl_En_Baba/scheduleScripts.schl
  src/overlays/actors/ovl_En_Baba/z_en_baba.c
  src/overlays/actors/ovl_En_Bjt/scheduleScripts.schl
  src/overlays/actors/ovl_En_Bjt/z_en_bjt.c
  src/overlays/actors/ovl_En_Door/scheduleScripts.schl
  src/overlays/actors/ovl_En_Door/z_en_door.c
  src/overlays/actors/ovl_En_Gm/scheduleScripts.schl
  src/overlays/actors/ovl_En_Gm/z_en_gm.c
  src/overlays/actors/ovl_En_Ig/scheduleScripts.schl
  src/overlays/actors/ovl_En_Ig/z_en_ig.c
  src/overlays/actors/ovl_En_Ja/scheduleScripts.schl
  src/overlays/actors/ovl_En_Ja/z_en_ja.c
  src/overlays/actors/ovl_En_Nb/scheduleScripts.schl
  src/overlays/actors/ovl_En_Nb/z_en_nb.c
  src/overlays/actors/ovl_En_Pm/scheduleScripts.schl
  src/overlays/actors/ovl_En_Pm/z_en_pm.c
  src/overlays/actors/ovl_En_Pst/scheduleScripts.schl
  src/overlays/actors/ovl_En_Pst/z_en_pst.c
  src/overlays/actors/ovl_En_Suttari/scheduleScripts.schl
  src/overlays/actors/ovl_En_Suttari/z_en_suttari.c
  src/overlays/actors/ovl_En_Tab/scheduleScripts.schl
  src/overlays/actors/ovl_En_Tab/z_en_tab.c
  src/overlays/actors/ovl_En_Test3/scheduleScripts.schl
  src/overlays/actors/ovl_En_Test3/z_en_test3.c
  src/overlays/actors/ovl_En_Tk/scheduleScripts.schl
  src/overlays/actors/ovl_En_Tk/z_en_tk.c
  src/overlays/actors/ovl_Obj_Shutter/scheduleScripts.schl
  src/overlays/actors/ovl_Obj_Shutter/z_obj_shutter.c
  tools/buildtools/schc.py
  tools/disasm/variables.txt
  tools/overlayhelpers/scheduledis.py
Labels: Tooling, Merge-ready

#1599 BossHakugin (Goht) OK and documented, EnHakurock documented, other assorted documentation
  include/z64save.h
  include/z64subs.h
  spec
  src/code/z_parameter.c
  src/code/z_sub_s.c
  src/overlays/actors/ovl_Boss_01/z_boss_01.c
  src/overlays/actors/ovl_Boss_02/z_boss_02.c
  src/overlays/actors/ovl_Boss_03/z_boss_03.c
  src/overlays/actors/ovl_Boss_04/z_boss_04.c
  src/overlays/actors/ovl_Boss_06/z_boss_06.c
  src/overlays/actors/ovl_Boss_Hakugin/z_boss_hakugin.c
  src/overlays/actors/ovl_Boss_Hakugin/z_boss_hakugin.h
  src/overlays/actors/ovl_En_Hakurock/z_en_hakurock.c
  src/overlays/actors/ovl_En_Hakurock/z_en_hakurock.h
  src/overlays/actors/ovl_En_Sda/z_en_sda.c
  src/overlays/actors/ovl_En_Tanron2/z_en_tanron2.c
  src/overlays/effects/ovl_Effect_Ss_Fhg_Flash/z_eff_ss_fhg_flash.c
  src/overlays/effects/ovl_Effect_Ss_Fhg_Flash/z_eff_ss_fhg_flash.h
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  undefined_syms.txt
Labels: Overlay, Merge-ready

#1537 Document OoB in z_message_nes
  src/code/z_message_nes.c
Labels: documentation, Merge-ready

#1515 Introduce More Audio Headers
  include/audio/heap.h
  include/audio/list.h
  include/audio/load.h
  include/audio/playback.h
  include/audio/reverb.h
  include/audio/seqplayer.h
  include/audio/synthesis.h
  include/functions.h
  include/variables.h
  include/z64audio.h
  src/audio/lib/heap.c
  src/audio/lib/load.c
  src/audio/lib/playback.c
  src/audio/lib/seqplayer.c
  src/audio/lib/synthesis.c
  tools/disasm/functions.txt
  tools/sizes/code_functions.csv
Labels: Clean up, Audio, Merge-ready

#1606 Fix disasm.py
  requirements.txt
  tools/disasm/disasm.py
Labels: Tooling, Merge-ready

#1605 Clean2
  assets/xml/code/circle_tex.xml
  include/variables.h
  include/z64circle_tex.h
  include/z64transition.h
  spec
  src/code/title_setup.c
  src/code/z_actor.c
  src/code/z_circle_tex.c
  src/code/z_fbdemo.c
  src/code/z_fbdemo_circle.c
  src/code/z_inventory.c
  src/code/z_skelanime.c
  tools/disasm/files.txt
  tools/disasm/functions.txt
  tools/sizes/code_functions.csv
Labels: Clean up, Merge-ready
