Repository zeldaret/mm, pull requests merged in 2024-12, with the labels that each got.

#1751 Small Misc Clean
  include/z64actor.h
  include/z64item.h
  spec
  src/buffers/gfxbuffers.c
  src/buffers/gfxpools.c
  src/buffers/gfxstack.c
  src/buffers/gfxyield.c
  src/code/z_actor.c
  src/overlays/actors/ovl_Boss_01/z_boss_01.c
  src/overlays/actors/ovl_Boss_02/z_boss_02.c
  src/overlays/actors/ovl_Boss_03/z_boss_03.c
  src/overlays/actors/ovl_Boss_Hakugin/z_boss_hakugin.c
  tools/disasm/disasm.py
  tools/disasm/files.txt
  tools/namefixer.py
Labels: Clean up, Merge-ready

#1752 Player Docs: Slide on Slope
  include/z64player.h
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: documentation, Merge-ready

#1754 Document Light-Based Actor Flags
  include/z64actor.h
  src/code/z_actor.c
  src/code/z_lights.c
  src/overlays/actors/ovl_Bg_Astr_Bombwall/z_bg_astr_bombwall.c
  src/overlays/actors/ovl_Bg_Crace_Movebg/z_bg_crace_movebg.c
  src/overlays/actors/ovl_Bg_Ikana_Bombwall/z_bg_ikana_bombwall.c
  src/overlays/actors/ovl_Bg_Kin2_Bombwall/z_bg_kin2_bombwall.c
  src/overlays/actors/ovl_Bg_Kin2_Shelf/z_bg_kin2_shelf.c
  src/overlays/actors/ovl_Bg_Market_Step/z_bg_market_step.c
  src/overlays/actors/ovl_Door_Shutter/z_door_shutter.c
  src/overlays/actors/ovl_Door_Spiral/z_door_spiral.c
  src/overlays/actors/ovl_En_Horse_Game_Check/z_en_horse_game_check.c
  src/overlays/actors/ovl_Obj_Bean/z_obj_bean.c
  src/overlays/actors/ovl_Obj_Dhouse/z_obj_dhouse.c
  src/overlays/actors/ovl_Obj_Spidertent/z_obj_spidertent.c
  src/overlays/actors/ovl_Obj_Tokei_Step/z_obj_tokei_step.c
  tools/disasm/variables.txt
Labels: documentation, Merge-ready

#1753 Boss07 (Majora) OK and documented [mm-n64-us.z64 OK]
  assets/xml/objects/object_boss07.xml
  include/z64subs.h
  linker_scripts/final/undefined_syms.ld
  spec
  src/code/z_sub_s.c
  src/overlays/actors/ovl_Boss_01/z_boss_01.c
  src/overlays/actors/ovl_Boss_01/z_boss_01.h
  src/overlays/actors/ovl_Boss_07/z_boss_07.c
  src/overlays/actors/ovl_Boss_07/z_boss_07.h
  src/overlays/actors/ovl_Boss_Hakugin/z_boss_hakugin.c
  src/overlays/actors/ovl_En_Sda/z_en_sda.c
  src/overlays/actors/ovl_Obj_Tsubo/z_obj_tsubo.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/sizes/code_functions.csv
Labels: Overlay, Merge-ready

#1755 [Audio 9/9] Loose ends
  Makefile
  assets/xml/audio/samplebanks/SampleBank_0.xml
  assets/xml/audio/samplebanks/SampleBank_2.xml
  docs/audio/Samplebank_XML.md
  docs/audio/Soundfont_XML.md
  docs/audio/build_flowchart.png
  include/audio/aseq.h
  include/libc/assert.h
  include/sfx.h
  linker_scripts/soundfont.ld
  src/audio/session_config.c
  src/overlays/actors/ovl_Boss_02/z_boss_02.c
  tools/audio/.gitignore
  tools/audio/Makefile
  tools/audio/README.md
  tools/audio/afile_sizes.c
  tools/audio/aifc.c
  tools/audio/audio_tablegen.c
  tools/audio/extraction/audio_extract.py
  tools/audio/extraction/audiobank_file.py
  tools/audio/extraction/audiotable.py
  tools/audio/extraction/disassemble_sequence.py
  tools/audio/extraction/extraction_xml.py
  tools/audio/samplebank_compiler.c
  tools/audio/sampleconv/Makefile
  tools/audio/sampleconv/src/codec/vadpcm.c
  tools/audio/sampleconv/src/codec/vadpcm_tabledesign.c
  tools/audio/sampleconv/src/container/aiff.c
  tools/audio/sampleconv/src/container/wav.c
  tools/audio/soundfont_compiler.c
  tools/audio/util.c
  tools/audio_extraction.py
Labels: Tooling, Audio, Merge-ready

#1757 libultra/libc cleanup
  include/PR/os_libc.h
  include/PR/xstdio.h
  include/libc/alloca.h
  include/libc/stddef.h
  include/libc/string.h
  src/libultra/libc/ldiv.c
  src/libultra/libc/ll.c
  src/libultra/libc/llcvt.c
  src/libultra/libc/string.c
  src/libultra/libc/xldtob.c
  src/libultra/libc/xlitob.c
  src/libultra/libc/xprintf.c
Labels: Clean up, Merge-ready

#1750 Ports over OoT's version config
  Makefile
  baseroms/n64-us/config.yml
  baseroms/n64-us/dmadata_names.txt
  baseroms/n64-us/dmadata_start.txt
  baseroms/n64-us/segments.csv
  requirements.txt
  tools/decompress_baserom.py
  tools/extract_audio.py
  tools/extract_baserom.py
  tools/extract_text.py
  tools/extract_yars.py
  tools/text/msgdis.py
  tools/version/version_config.py
Labels: Tooling, Merge-ready

#1763 Port over macOS fix
  Makefile
Labels: Tooling, Merge-ready

#1765 Add original asset names to all `object_y*` and `object_z*` files
  assets/xml/objects/object_yado_obj.xml
  assets/xml/objects/object_yb.xml
  assets/xml/objects/object_yukimura_obj.xml
  assets/xml/objects/object_yukiyama.xml
  assets/xml/objects/object_zg.xml
  assets/xml/objects/object_zl1.xml
  assets/xml/objects/object_zl4.xml
  assets/xml/objects/object_zm.xml
  assets/xml/objects/object_zo.xml
  assets/xml/objects/object_zob.xml
  assets/xml/objects/object_zod.xml
  assets/xml/objects/object_zog.xml
  assets/xml/objects/object_zoraband.xml
  assets/xml/objects/object_zoraegg.xml
  assets/xml/objects/object_zov.xml
  src/overlays/actors/ovl_En_Yb/z_en_yb.c
Labels: Asset, Merge-ready

#1762 Document Update Actor Flags
  include/z64actor.h
  include/z64play.h
  src/code/z_actor.c
  src/code/z_eventmgr.c
  src/code/z_play.c
  src/code/z_player_call.c
  src/code/z_player_lib.c
  src/overlays/actors/ovl_Bg_Iknv_Obj/z_bg_iknv_obj.c
  src/overlays/actors/ovl_En_Bom/z_en_bom.c
  src/overlays/actors/ovl_En_Bombal/z_en_bombal.c
  src/overlays/actors/ovl_En_Col_Man/z_en_col_man.c
  src/overlays/actors/ovl_En_Dinofos/z_en_dinofos.c
  src/overlays/actors/ovl_En_Dragon/z_en_dragon.c
  src/overlays/actors/ovl_En_Egol/z_en_egol.c
  src/overlays/actors/ovl_En_Encount1/z_en_encount1.c
  src/overlays/actors/ovl_En_Guard_Nuts/z_en_guard_nuts.c
  src/overlays/actors/ovl_En_Hg/z_en_hg.c
  src/overlays/actors/ovl_En_Jso/z_en_jso.c
  src/overlays/actors/ovl_En_Jso2/z_en_jso2.c
  src/overlays/actors/ovl_En_Kaizoku/z_en_kaizoku.c
  src/overlays/actors/ovl_En_Ma_Yto/z_en_ma_yto.c
  src/overlays/actors/ovl_En_Ma_Yts/z_en_ma_yts.c
  src/overlays/actors/ovl_En_Pamera/z_en_pamera.c
  src/overlays/actors/ovl_En_Paper/z_en_paper.c
  src/overlays/actors/ovl_En_Po_Composer/z_en_po_composer.c
  src/overlays/actors/ovl_En_Po_Fusen/z_en_po_fusen.c
  src/overlays/actors/ovl_En_Rail_Skb/z_en_rail_skb.c
  src/overlays/actors/ovl_En_Railgibud/z_en_railgibud.c
  src/overlays/actors/ovl_En_Skb/z_en_skb.c
  src/overlays/actors/ovl_En_Talk_Gibud/z_en_talk_gibud.c
  src/overlays/actors/ovl_En_Test4/z_en_test4.c
  src/overlays/actors/ovl_En_Test6/z_en_test6.c
  src/overlays/actors/ovl_En_Test7/z_en_test7.c
  src/overlays/actors/ovl_En_Viewer/z_en_viewer.c
  src/overlays/actors/ovl_En_Wiz/z_en_wiz.c
  src/overlays/actors/ovl_Obj_Hgdoor/z_obj_hgdoor.c
  src/overlays/actors/ovl_Obj_Moon_Stone/z_obj_moon_stone.c
  src/overlays/actors/ovl_Obj_Wturn/z_obj_wturn.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: documentation, Merge-ready

#1766 Add original asset names to all assets present in overlays
  assets/xml/overlays/ovl_Arrow_Fire.xml
  assets/xml/overlays/ovl_Arrow_Ice.xml
  assets/xml/overlays/ovl_Arrow_Light.xml
  assets/xml/overlays/ovl_En_Bom.xml
  assets/xml/overlays/ovl_En_Clear_Tag.xml
  assets/xml/overlays/ovl_En_Gakufu.xml
  assets/xml/overlays/ovl_En_Holl.xml
  assets/xml/overlays/ovl_En_Horse_Game_Check.xml
  assets/xml/overlays/ovl_En_Tru.xml
  assets/xml/overlays/ovl_Oceff_Spot.xml
  assets/xml/overlays/ovl_Oceff_Storm.xml
  assets/xml/overlays/ovl_Oceff_Wipe.xml
  assets/xml/overlays/ovl_Oceff_Wipe2.xml
  assets/xml/overlays/ovl_Oceff_Wipe3.xml
  assets/xml/overlays/ovl_Oceff_Wipe4.xml
  assets/xml/overlays/ovl_Oceff_Wipe5.xml
  assets/xml/overlays/ovl_Oceff_Wipe6.xml
  assets/xml/overlays/ovl_Oceff_Wipe7.xml
Labels: Asset, Merge-ready

#1769 Fix return type of `EnDeath_UpdateCoreVelocityAndRotation`
  src/overlays/actors/ovl_En_Death/z_en_death.c
Labels: Clean up, Merge-ready

#1770 Add missing ExternalFile tags to object_dmask and object_osn
  assets/xml/objects/object_dmask.xml
  assets/xml/objects/object_osn.xml
Labels: Asset, Merge-ready

#1767 Remove gSystemHeap and the system_heap spec segment, use _buffersSegmentEnd to represent the start of the system heap
  include/buffers.h
  include/segment_symbols.h
  linker_scripts/final/extra.ld
  spec
  src/buffers/system_heap.c
  src/code/main.c
  tools/disasm/variables.txt
Labels: Clean up, Merge-ready

#1771 Move gAudioTatumInit and gAudioHeapInitSizes to their own file, using data-with-rodata instead of const qualifiers
  Makefile
  include/variables.h
  include/z64audio.h
  spec
  src/audio/lib/load.c
  src/audio/session_config.c
  src/audio/session_init.c
Labels: code, Audio, Merge-ready

#1764 Updated Docker Image
  Dockerfile
Labels: Tooling, Merge-ready

#1773 Standardize "ActorMovement" over "ActorMove"
  include/z64animation.h
  src/code/z_en_hy_code.c
  src/code/z_player_lib.c
  src/code/z_skelanime.c
  src/overlays/actors/ovl_En_Gm/z_en_gm.c
  src/overlays/actors/ovl_En_Test3/z_en_test3.c
  src/overlays/actors/ovl_En_Tru/z_en_tru.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
  tools/namefixer.py
  tools/sizes/code_functions.csv
Labels: documentation, Merge-ready

#1772 Add original asset names to `gameplay_field_keep` and `gameplay_dangeon_keep`
  assets/xml/objects/gameplay_dangeon_keep.xml
  assets/xml/objects/gameplay_field_keep.xml
Labels: Asset, Merge-ready

#1768 Apply the NORETURN attribute to functions that do not return
  include/attributes.h
  include/fault.h
  include/functions.h
  include/libu64/debug.h
  src/boot/fault.c
  src/boot/libu64/debug.c
  src/code/code_80183070.c
Labels: Clean up, Merge-ready

#1774 Add the bgcheck macros from OoT
  include/z64bgcheck.h
Labels: Clean up, Merge-ready

#1758 Check in makerom files
  Makefile
  include/PR/asm.h
  include/boot.h
  spec
  src/boot/boot_main.c
  src/makerom/entry.s
  src/makerom/ipl3.s
  src/makerom/rom_header.s
  tools/disasm/disasm.py
Labels: boot, Merge-ready

#1775 Add D_801D1E80 to data in audio lib
  spec
  src/audio/lib/data.c
Labels: code, Audio, Merge-ready

#1778 Misc Fixes
  src/audio/lib/load.c
  src/audio/voice_internal.c
  src/code/z_parameter.c
  src/overlays/actors/ovl_En_Test7/z_en_test7.c
  src/overlays/actors/ovl_Obj_Um/z_obj_um.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_map.c
Labels: Clean up, Merge-ready

#1779 Move D_80097508 out of system_heap.c
  include/libc64/fixed_point.h
  src/boot/libu64/system_heap.c
  tools/disasm/disasm.py
  tools/disasm/files.txt
  tools/disasm/variables.txt
Labels: boot, Clean up, Merge-ready

#1780 Match SysCfb_Init without extra symbols
  include/buffers.h
  linker_scripts/final/undefined_syms.ld
  src/code/sys_cfb.c
Labels: Clean up, Merge-ready
