Repository zeldaret/mm, pull requests merged in 2024-04, with the labels that each got.

#1505 Introduce `z64pause_menu.h` header
  include/functions.h
  include/regs.h
  include/variables.h
  include/z64.h
  include/z64pause_menu.h
  include/z64view.h
  src/code/flg_set.c
  src/code/game.c
  src/code/z_bgcheck.c
  src/code/z_demo.c
  src/code/z_kaleido_manager.c
  src/code/z_kaleido_scope_call.c
  src/code/z_kaleido_setup.c
  src/code/z_kankyo.c
  src/code/z_lifemeter.c
  src/code/z_map_exp.c
  src/code/z_message.c
  src/code/z_message_nes.c
  src/code/z_parameter.c
  src/code/z_play.c
  src/code/z_player_call.c
  src/code/z_rcp.c
  src/code/z_sram_NES.c
  src/overlays/actors/ovl_Boss_03/z_boss_03.c
  src/overlays/actors/ovl_En_Okarina_Effect/z_en_okarina_effect.c
  src/overlays/actors/ovl_En_Thiefbird/z_en_thiefbird.c
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/gamestates/ovl_file_choose/z_file_nameset_NES.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_collect.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_item.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_map.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_scope.h
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_scope_NES.c
Labels: Clean up, Merge-ready

#1500 Add Shift-JIS support for some voice and message files
  Makefile
  src/audio/voice_external.c
  src/code/z_message.c
  src/code/z_message_nes.c
  src/libultra/voice/voicecheckword.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/shiftjis_conv.py
  tools/sizes/code_functions.csv
Labels: Clean up, Merge-ready

#1608 bg_hakugin_post: replace hardcoded size for sizeof
  src/overlays/actors/ovl_Bg_Hakugin_Post/z_bg_hakugin_post.c
Labels: Clean up, Merge-ready

#1610 Increase audio seq cmd list size
  include/sequence.h
  tools/disasm/variables.txt
Labels: Clean up, Merge-ready

#1609 bg_breakwall: fix great bay storm dl reference
  src/overlays/actors/ovl_Bg_Breakwall/z_bg_breakwall.c
Labels: Clean up, Merge-ready

#1607 Mayor Dotour (ovl_en_dt) OK and documented
  assets/xml/objects/object_dt.xml
  include/z64save.h
  spec
  src/code/z_sram_NES.c
  src/overlays/actors/ovl_En_Baisen/z_en_baisen.c
  src/overlays/actors/ovl_En_Baisen/z_en_baisen.h
  src/overlays/actors/ovl_En_Daiku/z_en_daiku.c
  src/overlays/actors/ovl_En_Dt/z_en_dt.c
  src/overlays/actors/ovl_En_Dt/z_en_dt.h
  src/overlays/actors/ovl_En_Ending_Hero/z_en_ending_hero.c
  src/overlays/actors/ovl_En_Ending_Hero6/z_en_ending_hero6.c
  src/overlays/actors/ovl_En_Heishi/z_en_heishi.c
  src/overlays/actors/ovl_En_Muto/z_en_muto.c
  src/overlays/actors/ovl_En_Recepgirl/z_en_recepgirl.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: Overlay, Merge-ready

#1602 Misc Clean
  include/functions.h
  include/loadfragment.h
  spec
  src/boot/O2/loadfragment.c
  src/boot/O2/loadfragment2.c
  src/code/PreRender.c
  src/code/flg_set.c
  src/code/game.c
  src/code/gfxalloc.c
  src/code/z_debug_mode.c
  src/code/z_eff_ss_dead.c
  src/code/z_kankyo.c
  src/code/z_message.c
  src/code/z_play.c
  src/code/z_rcp.c
  src/code/z_skin_awb.c
  src/code/z_visfbuf.c
  src/code/z_vismono.c
  src/overlays/actors/ovl_En_Mag/z_en_mag.c
  src/overlays/actors/ovl_En_Thiefbird/z_en_thiefbird.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_debug.c
  tools/disasm/files.txt
  tools/disasm/functions.txt
  tools/sizes/code_functions.csv
Labels: Clean up, Merge-ready

#1225 Obj_Mine matched
  spec
  src/overlays/actors/ovl_Obj_Mine/z_obj_mine.c
  src/overlays/actors/ovl_Obj_Mine/z_obj_mine.h
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: Overlay, Merge-ready

#1611 Hotfix progress script due to extracted change
  tools/progress.py
Labels: Tooling, Merge-ready

#1612 Jenkinsfile Hotfix: install GitPython for progress script
  Jenkinsfile
Labels: Tooling, Merge-ready

#1613 Remove tailing comma from vscode json file
  docs/tutorial/vscode.md
Labels: Tooling, Merge-ready

#1615 Name a lot of the weekeventregs for when the player receives a Heart Piece
  include/z64save.h
  src/code/z_sram_NES.c
  src/overlays/actors/ovl_En_Az/z_en_az.c
  src/overlays/actors/ovl_En_Col_Man/z_en_col_man.c
  src/overlays/actors/ovl_En_Dt/z_en_dt.c
  src/overlays/actors/ovl_En_Fu/z_en_fu.c
  src/overlays/actors/ovl_En_Gb2/z_en_gb2.c
  src/overlays/actors/ovl_En_Ginko_Man/z_en_ginko_man.c
  src/overlays/actors/ovl_En_Gs/z_en_gs.c
  src/overlays/actors/ovl_En_Jgame_Tsn/z_en_jgame_tsn.c
  src/overlays/actors/ovl_En_Kendo_Js/z_en_kendo_js.c
  src/overlays/actors/ovl_En_Kitan/z_en_kitan.c
  src/overlays/actors/ovl_En_Minifrog/z_en_minifrog.c
  src/overlays/actors/ovl_En_Mm3/z_en_mm3.c
  src/overlays/actors/ovl_En_Ot/z_en_ot.c
  src/overlays/actors/ovl_En_Zos/z_en_zos.c
  tools/weekeventregconvert.py
Labels: documentation, Merge-ready

#1616 Some Lifemeter functions not named in functions.txt
  tools/disasm/functions.txt
Labels: Clean up, Merge-ready

#1603 `ovl_En_Door` docs pass
  assets/xml/objects/gameplay_keep.xml
  include/z64actor.h
  include/z64door.h
  include/z64subs.h
  include/z64view.h
  src/code/z_actor.c
  src/code/z_en_hy_code.c
  src/code/z_scene.c
  src/code/z_sub_s.c
  src/code/z_view.c
  src/overlays/actors/ovl_En_An/z_en_an.c
  src/overlays/actors/ovl_En_Door/scheduleScripts.schl
  src/overlays/actors/ovl_En_Door/z_en_door.c
  src/overlays/actors/ovl_En_Door/z_en_door.h
  src/overlays/actors/ovl_En_Door_Etc/z_en_door_etc.c
  src/overlays/actors/ovl_En_Gm/z_en_gm.c
  src/overlays/actors/ovl_En_Ig/z_en_ig.c
  src/overlays/actors/ovl_En_Pm/z_en_pm.c
  src/overlays/actors/ovl_En_Suttari/z_en_suttari.c
  src/overlays/actors/ovl_En_Test3/z_en_test3.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/namefixer.py
  tools/sizes/code_functions.csv
Labels: Overlay, Merge-ready

#1617 More weekeventregs naming for things related to receiving items
  include/z64save.h
  src/code/z_sram_NES.c
  src/overlays/actors/ovl_En_Az/z_en_az.c
  src/overlays/actors/ovl_En_Elfgrp/z_en_elfgrp.c
  src/overlays/actors/ovl_En_Ginko_Man/z_en_ginko_man.c
  src/overlays/actors/ovl_En_Gk/z_en_gk.c
  src/overlays/actors/ovl_En_M_Thunder/z_en_m_thunder.c
  src/overlays/actors/ovl_En_Rz/z_en_rz.c
  src/overlays/actors/ovl_En_Scopenuts/z_en_scopenuts.c
  src/overlays/actors/ovl_En_Sellnuts/z_en_sellnuts.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/weekeventregconvert.py
Labels: documentation, Merge-ready

#1619 Add original asset names to all `object_s*` files
  assets/xml/objects/object_sb.xml
  assets/xml/objects/object_sdn.xml
  assets/xml/objects/object_secom_obj.xml
  assets/xml/objects/object_sek.xml
  assets/xml/objects/object_sichitai_obj.xml
  assets/xml/objects/object_sinkai_kabe.xml
  assets/xml/objects/object_skb.xml
  assets/xml/objects/object_slime.xml
  assets/xml/objects/object_smtower.xml
  assets/xml/objects/object_snowwd.xml
  assets/xml/objects/object_spdweb.xml
  assets/xml/objects/object_spidertent.xml
  assets/xml/objects/object_spinyroll.xml
  assets/xml/objects/object_spot11_obj.xml
  assets/xml/objects/object_ssh.xml
  assets/xml/objects/object_st.xml
  assets/xml/objects/object_syokudai.xml
  assets/xml/objects/object_syoten.xml
Labels: documentation, Merge-ready

#1614 EnInvadepoh (Aliens, UFO, Invasion Handler, etc.) OK and documented
  include/tables/bombers_notebook/event_table.h
  include/z64save.h
  spec
  src/code/z_kankyo.c
  src/code/z_lights.c
  src/code/z_play_hireso.c
  src/code/z_sram_NES.c
  src/overlays/actors/ovl_Bg_Breakwall/z_bg_breakwall.c
  src/overlays/actors/ovl_Bg_Umajump/z_bg_umajump.c
  src/overlays/actors/ovl_Boss_02/z_boss_02.c
  src/overlays/actors/ovl_Boss_02/z_boss_02.h
  src/overlays/actors/ovl_En_Cow/z_en_cow.c
  src/overlays/actors/ovl_En_In/z_en_in.c
  src/overlays/actors/ovl_En_Invadepoh/z_en_invadepoh.c
  src/overlays/actors/ovl_En_Invadepoh/z_en_invadepoh.h
  src/overlays/actors/ovl_En_Invadepoh_Demo/z_en_invadepoh_demo.c
  src/overlays/actors/ovl_En_Ma4/z_en_ma4.c
  src/overlays/actors/ovl_En_Ma_Yto/z_en_ma_yto.c
  src/overlays/actors/ovl_En_Ma_Yts/z_en_ma_yts.c
  src/overlays/actors/ovl_En_Tanron5/z_en_tanron5.c
  src/overlays/actors/ovl_En_Tanron5/z_en_tanron5.h
  src/overlays/actors/ovl_Obj_Dinner/z_obj_dinner.c
  src/overlays/actors/ovl_Obj_Milk_Bin/z_obj_milk_bin.c
  src/overlays/actors/ovl_Obj_Mine/z_obj_mine.c
  src/overlays/actors/ovl_Obj_Tokei_Step/z_obj_tokei_step.c
  src/overlays/actors/ovl_Obj_Um/z_obj_um.c
  src/overlays/actors/ovl_Obj_Usiyane/z_obj_usiyane.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/namefixer.py
  tools/weekeventregconvert.py
  undefined_syms.txt
Labels: Overlay, Merge-ready
