Repository zeldaret/mm, pull requests merged in 2024-07, with the labels that each got.

#1655 Suppress address warning in en_s_goro
  src/overlays/actors/ovl_En_S_Goro/z_en_s_goro.c
Labels: Merge-ready

#1652 `z_parameter.c`: remaining functions, do action documentation, gfx cleanup
  include/z64interface.h
  include/z64play.h
  include/z64player.h
  src/code/z_inventory.c
  src/code/z_kaleido_setup.c
  src/code/z_message.c
  src/code/z_message_nes.c
  src/code/z_message_staff.c
  src/code/z_parameter.c
  src/code/z_player_lib.c
  src/overlays/actors/ovl_Bg_Ingate/z_bg_ingate.c
  src/overlays/actors/ovl_En_Fishing/z_en_fishing.c
  src/overlays/actors/ovl_En_Fsn/z_en_fsn.c
  src/overlays/actors/ovl_En_Horse/z_en_horse.c
  src/overlays/actors/ovl_En_Okuta/z_en_okuta.c
  src/overlays/actors/ovl_En_Ossan/z_en_ossan.c
  src/overlays/actors/ovl_En_Sob1/z_en_sob1.c
  src/overlays/actors/ovl_En_Syateki_Man/z_en_syateki_man.c
  src/overlays/actors/ovl_En_Trt/z_en_trt.c
  src/overlays/actors/ovl_Obj_Um/z_obj_um.c
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_collect.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_scope_NES.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/namefixer.py
  tools/sizes/code_functions.csv
Labels: documentation, code, Merge-ready

#1654 ovl_bg_dblue_elevator OK and documented
  linker_scripts/undefined_syms.ld
  spec
  src/overlays/actors/ovl_Bg_Dblue_Elevator/z_bg_dblue_elevator.c
  src/overlays/actors/ovl_Bg_Dblue_Elevator/z_bg_dblue_elevator.h
  tools/disasm/functions.txt
Labels: Overlay, Merge-ready

#1657 Add original asset names to all `object_t*` files
  assets/xml/objects/object_tab.xml
  assets/xml/objects/object_taisou.xml
  assets/xml/objects/object_takaraya_objects.xml
  assets/xml/objects/object_tanron4.xml
  assets/xml/objects/object_taru.xml
  assets/xml/objects/object_tite.xml
  assets/xml/objects/object_tk.xml
  assets/xml/objects/object_tokei_step.xml
  assets/xml/objects/object_tokei_tobira.xml
  assets/xml/objects/object_tokei_turret.xml
  assets/xml/objects/object_toryo.xml
  assets/xml/objects/object_trap.xml
  assets/xml/objects/object_tree.xml
  assets/xml/objects/object_tro.xml
  assets/xml/objects/object_trt.xml
  assets/xml/objects/object_tru.xml
  assets/xml/objects/object_tsn.xml
  assets/xml/objects/object_tsubo.xml
  assets/xml/objects/object_twig.xml
  assets/xml/overlays/ovl_En_Tanron1.xml
  assets/xml/overlays/ovl_Obj_Jgame_Light.xml
Labels: Asset, Merge-ready

#1658 More General Cleanup
  assets/xml/misc/scene_texture_01.xml
  assets/xml/objects/gameplay_keep.xml
  assets/xml/objects/object_an1.xml
  assets/xml/objects/object_az.xml
  assets/xml/objects/object_bigslime.xml
  assets/xml/objects/object_boss02.xml
  assets/xml/objects/object_boss03.xml
  assets/xml/objects/object_boss_hakugin.xml
  assets/xml/objects/object_botihasira.xml
  assets/xml/objects/object_box.xml
  assets/xml/objects/object_cs.xml
  assets/xml/objects/object_ds2.xml
  assets/xml/objects/object_ds2n.xml
  assets/xml/objects/object_fall2.xml
  assets/xml/objects/object_gk.xml
  assets/xml/objects/object_iknv_obj.xml
  assets/xml/objects/object_kamejima.xml
  assets/xml/objects/object_mnk.xml
  assets/xml/objects/object_nwc.xml
  assets/xml/objects/object_shn.xml
  assets/xml/objects/object_skb.xml
  assets/xml/objects/object_trt.xml
  assets/xml/objects/object_um.xml
  assets/xml/objects/object_zl4.xml
  assets/xml/overlays/ovl_En_Mm2.xml
  linker_scripts/undefined_syms.ld
  src/code/z_collision_check.c
  src/overlays/actors/ovl_En_Ishi/z_en_ishi.c
  src/overlays/actors/ovl_En_Kusa/z_en_kusa.c
  src/overlays/actors/ovl_En_Mushi2/z_en_mushi2.c
  src/overlays/actors/ovl_Obj_Aqua/z_obj_aqua.c
  src/overlays/actors/ovl_Obj_Bombiwa/z_obj_bombiwa.c
  src/overlays/actors/ovl_Obj_Grass_Unit/z_obj_grass_unit.c
  src/overlays/actors/ovl_Obj_Hamishi/z_obj_hamishi.c
  tools/disasm/functions.txt
Labels: Clean up, Merge-ready

#1651 Another General Cleanup
  Makefile
  include/variables.h
  include/z64bgcheck.h
  src/audio/lib/thread.c
  src/code/z_bgcheck.c
  src/code/z_parameter.c
  src/overlays/actors/ovl_En_Invadepoh/z_en_invadepoh.c
  src/overlays/actors/ovl_En_Invadepoh_Demo/z_en_invadepoh_demo.c
  src/overlays/actors/ovl_En_Test5/z_en_test5.h
  src/overlays/actors/ovl_En_Tk/z_en_tk.c
  src/overlays/actors/ovl_En_Warp_tag/z_en_warp_tag.c
  src/overlays/actors/ovl_Obj_Driftice/z_obj_driftice.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/calc_bss.sh
  tools/disasm/variables.txt
  tools/m2ctx.py
Labels: Clean up, Merge-ready

#1656 Document object_bob
  assets/xml/objects/object_bba.xml
  assets/xml/objects/object_bob.xml
  assets/xml/objects/object_cne.xml
  src/code/z_en_hy_code.c
  src/overlays/actors/ovl_En_Baba/z_en_baba.c
  src/overlays/actors/ovl_En_Baba/z_en_baba.h
  src/overlays/actors/ovl_En_Bba_01/z_en_bba_01.c
  src/overlays/actors/ovl_En_Cne_01/z_en_cne_01.c
Labels: Asset, Merge-ready

#1648 Document garbage data on the on-screen clock.
  src/code/z_parameter.c
Labels: Clean up, Merge-ready

#1662 Cleaner AudioScript_SequenceChannelProcessScript Match
  src/audio/lib/seqplayer.c
Labels: Clean up, Merge-ready

#1659 ovl_En_Knight OK
  assets/xml/objects/object_knight.xml
  include/variables.h
  linker_scripts/undefined_syms.ld
  spec
  src/overlays/actors/ovl_Boss_06/z_boss_06.c
  src/overlays/actors/ovl_Boss_06/z_boss_06.h
  src/overlays/actors/ovl_En_Knight/z_en_knight.c
  src/overlays/actors/ovl_En_Knight/z_en_knight.h
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: documentation, Overlay, Merge-ready

#1660 Fix MSCRIPT_CMD_UNSET_EVENT_INF command
  include/z64msgevent.h
  src/overlays/actors/ovl_En_Dnh/z_en_dnh.c
  src/overlays/actors/ovl_En_Nb/z_en_nb.c
  tools/overlayhelpers/mscriptdis.py
Labels: Clean up, Merge-ready

#1664 Extract Keyframe Assets data
  assets/xml/objects/gameplay_keep.xml
  assets/xml/objects/object_fall2.xml
  assets/xml/objects/object_moonend.xml
  assets/xml/objects/object_syoten.xml
  include/z64keyframe.h
  src/overlays/actors/ovl_Demo_Moonend/z_demo_moonend.c
  src/overlays/actors/ovl_Demo_Syoten/z_demo_syoten.c
  src/overlays/actors/ovl_Door_Warp1/z_door_warp1.c
  src/overlays/actors/ovl_Eff_Change/z_eff_change.c
  src/overlays/actors/ovl_En_Fall2/z_en_fall2.c
  src/overlays/actors/ovl_En_Ot/z_en_ot.c
  src/overlays/actors/ovl_En_Test/z_en_test.c
  src/overlays/actors/ovl_En_Test7/z_en_test7.c
  tools/ZAPD/.github/workflows/main.yml
  tools/ZAPD/.gitrepo
  tools/ZAPD/README.md
  tools/ZAPD/ZAPD/Globals.h
  tools/ZAPD/ZAPD/Main.cpp
  tools/ZAPD/ZAPD/OtherStructs/CutsceneMM_Commands.cpp
  tools/ZAPD/ZAPD/OtherStructs/CutsceneMM_Commands.h
  tools/ZAPD/ZAPD/OtherStructs/CutsceneOoT_Commands.cpp
  tools/ZAPD/ZAPD/ZAPD.vcxproj
  tools/ZAPD/ZAPD/ZAPD.vcxproj.filters
  tools/ZAPD/ZAPD/ZCKeyFrame.cpp
  tools/ZAPD/ZAPD/ZCKeyFrame.h
  tools/ZAPD/ZAPD/ZCKeyFrameAnim.cpp
  tools/ZAPD/ZAPD/ZCkeyFrameAnim.h
  tools/ZAPD/ZAPD/ZCutscene.cpp
  tools/ZAPD/ZAPD/ZCutscene.h
  tools/ZAPD/ZAPD/ZFile.cpp
  tools/ZAPD/ZAPD/ZResource.h
  tools/ZAPD/ZAPDUtils/Utils/StringHelper.h
Labels: Asset, Merge-ready

#1663 z_en_zl4 OK
  linker_scripts/undefined_syms.ld
  spec
  src/overlays/actors/ovl_Dm_Char04/z_dm_char04.c
  src/overlays/actors/ovl_Dm_Sa/z_dm_sa.c
  src/overlays/actors/ovl_Dm_Sa/z_dm_sa.h
  src/overlays/actors/ovl_En_Zl4/z_en_zl4.c
  src/overlays/actors/ovl_En_Zl4/z_en_zl4.h
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: Overlay, Merge-ready

#1665 Misc Cleanup
  assets/xml/objects/object_fu_kaiten.xml
  assets/xml/objects/object_horse_link_child.xml
  assets/xml/objects/object_kz.xml
  assets/xml/objects/object_link_child.xml
  assets/xml/objects/object_zl1.xml
  assets/xml/objects/object_zod.xml
  include/libc64/os_malloc.h
  include/variables.h
  linker_scripts/hardware_regs.ld
  linker_scripts/undefined_syms.ld
  src/audio/lib/heap.c
  src/audio/lib/load.c
  src/audio/lib/thread.c
  src/boot/fault.c
  src/boot/libc64/__osMalloc.c
  src/boot/libc64/malloc.c
  src/code/graph.c
  src/code/main.c
  src/code/z_eff_blure.c
  src/code/z_malloc.c
  src/code/z_scene_proc.c
  src/overlays/actors/ovl_En_Baba/z_en_baba.c
  src/overlays/actors/ovl_En_Bigslime/z_en_bigslime.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/sizes/boot_functions.csv
Labels: Clean up, Merge-ready

#1649 Introduce a bunch of small new headers
  include/functions.h
  include/gfx.h
  include/gfxalloc.h
  include/regs.h
  include/variables.h
  include/z64actor.h
  include/z64cutscene.h
  include/z64elf_message.h
  include/z64inventory.h
  include/z64math.h
  include/z64olib.h
  include/z64save.h
  include/z64snap.h
  src/code/PreRender.c
  src/code/cutscene_camera.c
  src/code/flg_set.c
  src/code/game.c
  src/code/gfxalloc.c
  src/code/graph.c
  src/code/sys_math3d.c
  src/code/z_camera.c
  src/code/z_debug_mode.c
  src/code/z_elf_message.c
  src/code/z_eventmgr.c
  src/code/z_inventory.c
  src/code/z_kankyo.c
  src/code/z_message.c
  src/code/z_olib.c
  src/code/z_play.c
  src/code/z_quake.c
  src/code/z_rcp.c
  src/code/z_snap.c
  src/code/z_visfbuf.c
  src/code/z_vismono.c
  src/overlays/actors/ovl_Dm_Char01/z_dm_char01.c
  src/overlays/actors/ovl_En_Egol/z_en_egol.c
  src/overlays/actors/ovl_En_Elf/z_en_elf.c
  src/overlays/actors/ovl_En_Jso2/z_en_jso2.c
  src/overlays/actors/ovl_En_Kakasi/z_en_kakasi.c
  src/overlays/actors/ovl_En_Kusa/z_en_kusa.c
  src/overlays/actors/ovl_En_Mag/z_en_mag.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_debug.c
  tools/check_reordering.py
Labels: Clean up, Merge-ready
