Repository zeldaret/mm, pull requests merged in 2024-09, with the labels that each got.

#1669 Cleanup: Pass all paths to tools rather than tools constructing them
  Makefile
  extract_assets.py
  tools/buildtools/decompress_baserom.py
  tools/buildtools/extract_baserom.py
  tools/buildtools/extract_yars.py
  tools/disasm/disasm.py
  tools/disasm/files.txt
  tools/msg/nes/msgdisNES.py
  tools/msg/staff/msgdisStaff.py
Labels: Tooling, Merge-ready

#1678 Update Room Documentation
  include/functions.h
  include/z64play.h
  include/z64scene.h
  src/code/z_map_disp.c
  src/code/z_play.c
  src/code/z_room.c
  src/code/z_scene.c
  src/overlays/actors/ovl_Door_Shutter/z_door_shutter.c
  src/overlays/actors/ovl_En_Holl/z_en_holl.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
  tools/sizes/code_functions.csv
Labels: documentation, Merge-ready

#1668 Small Misc Tooling
  .gitignore
  Makefile
  tools/extract_assets.py
Labels: Tooling, Merge-ready

#1682 Fixup actor audio flags docs
  include/functions.h
  src/code/z_actor.c
  src/overlays/actors/ovl_Arms_Hook/z_arms_hook.c
  src/overlays/actors/ovl_Bg_Hakugin_Post/z_bg_hakugin_post.c
  src/overlays/actors/ovl_Demo_Effect/z_demo_effect.c
  src/overlays/actors/ovl_En_Bom_Chu/z_en_bom_chu.c
  src/overlays/actors/ovl_En_Hanabi/z_en_hanabi.c
  src/overlays/actors/ovl_En_Stream/z_en_stream.c
  src/overlays/actors/ovl_En_Takaraya/z_en_takaraya.c
  src/overlays/actors/ovl_En_Test6/z_en_test6.c
  src/overlays/actors/ovl_Mir_Ray/z_mir_ray.c
  src/overlays/actors/ovl_Mir_Ray3/z_mir_ray3.c
  src/overlays/actors/ovl_Obj_Sound/z_obj_sound.c
  src/overlays/actors/ovl_Obj_Wturn/z_obj_wturn.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
  tools/namefixer.py
  tools/sizes/code_functions.csv
Labels: documentation, Audio, Merge-ready

#1676 Import data + bss
  assets/xml/boot/fault_drawer.xml
  assets/xml/boot/gfxprint.xml
  include/sequence.h
  include/variables.h
  include/z64audio.h
  spec
  src/audio/lib/heap.c
  src/audio/sequence.c
  src/audio/session_config.c
  src/boot/O2/gfxprint.c
  tools/disasm/files.txt
  tools/disasm/variables.txt
Labels: Clean up, Merge-ready

#1681 [headers] Move padmgr, scheduler, irqmgr symbols to respective headers; add segmented_address.h
  include/audiomgr.h
  include/idle.h
  include/irqmgr.h
  include/main.h
  include/padmgr.h
  include/scheduler.h
  include/segmented_address.h
  include/z64.h
  include/z64player.h
  src/boot/idle.c
  src/code/main.c
  src/code/padmgr.c
  src/code/speed_meter.c
  src/code/z_jpeg.c
  src/code/z_lib.c
  src/code/z_nulltask.c
Labels: Clean up, Merge-ready

#1680 Misc Clean
  include/PR/os_cont.h
  include/controller.h
  include/functions.h
  include/macros.h
  include/z64.h
  src/boot/O2/loadfragment.c
  src/boot/O2/loadfragment2.c
  src/boot/fault.c
  src/code/padmgr.c
  src/code/z_actor.c
  src/code/z_en_hy_code.c
  src/code/z_pause.c
  src/code/z_sub_s.c
  src/code/z_vimode.c
  src/overlays/actors/ovl_Bg_Ctower_Rot/z_bg_ctower_rot.c
  src/overlays/actors/ovl_Bg_Fire_Wall/z_bg_fire_wall.c
  src/overlays/actors/ovl_Bg_Iknin_Susceil/z_bg_iknin_susceil.c
  src/overlays/actors/ovl_Bg_Open_Shutter/z_bg_open_shutter.c
  src/overlays/actors/ovl_Bg_Spout_Fire/z_bg_spout_fire.c
  src/overlays/actors/ovl_Boss_Hakugin/z_boss_hakugin.c
  src/overlays/actors/ovl_Door_Shutter/z_door_shutter.c
  src/overlays/actors/ovl_Door_Spiral/z_door_spiral.c
  src/overlays/actors/ovl_En_Arrow/z_en_arrow.c
  src/overlays/actors/ovl_En_Bomjima/z_en_bomjima.c
  src/overlays/actors/ovl_En_Bomjima/z_en_bomjima.h
  src/overlays/actors/ovl_En_Box/z_en_box.c
  src/overlays/actors/ovl_En_Death/z_en_death.c
  src/overlays/actors/ovl_En_Dekubaba/z_en_dekubaba.c
  src/overlays/actors/ovl_En_Dodongo/z_en_dodongo.c
  src/overlays/actors/ovl_En_Door/z_en_door.c
  src/overlays/actors/ovl_En_Door_Etc/z_en_door_etc.c
  src/overlays/actors/ovl_En_Ge2/z_en_ge2.c
  src/overlays/actors/ovl_En_Holl/z_en_holl.c
  src/overlays/actors/ovl_En_Honotrap/z_en_honotrap.c
  src/overlays/actors/ovl_En_Kaizoku/z_en_kaizoku.c
  src/overlays/actors/ovl_En_Knight/z_en_knight.c
  src/overlays/actors/ovl_En_Test3/z_en_test3.c
  src/overlays/actors/ovl_En_Tk/z_en_tk.c
  src/overlays/actors/ovl_En_Viewer/z_en_viewer.c
  src/overlays/actors/ovl_Obj_Nozoki/z_obj_nozoki.c
  src/overlays/actors/ovl_Obj_Spinyroll/z_obj_spinyroll.c
  src/overlays/actors/ovl_Obj_Tokei_Tobira/z_obj_tokei_tobira.c
  src/overlays/actors/ovl_Obj_Um/z_obj_um.c
  src/overlays/actors/ovl_Obj_Vspinyroll/z_obj_vspinyroll.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/namefixer.py
  tools/sizes/code_functions.csv
Labels: Clean up, Merge-ready

#1688 [headers] Add kaleido_manager.h, clean up z64jpeg.h protos
  include/kaleido_manager.h
  include/z64.h
  include/z64jpeg.h
  include/z64pause_menu.h
  src/code/game.c
  src/code/jpegdecoder.c
  src/code/z_kaleido_manager.c
  src/code/z_kaleido_scope_call.c
  src/code/z_player_call.c
Labels: Clean up, Merge-ready

#1679 [Audio 8/?] Check-in handwritten sequences, build sequences, automate various sfx arrays
  .gitattributes
  Makefile
  assets/audio/sequences/seq_0.prg.seq
  assets/audio/sequences/seq_1.prg.seq
  include/audio/aseq.h
  include/sequence.h
  include/sfx.h
  include/tables/sequence_table.h
  include/tables/sfx/enemybank_table.h
  include/tables/sfx/environmentbank_table.h
  include/tables/sfx/itembank_table.h
  include/tables/sfx/ocarinabank_table.h
  include/tables/sfx/playerbank_table.h
  include/tables/sfx/systembank_table.h
  include/tables/sfx/voicebank_table.h
  spec
  src/audio/code_8019AF00.c
  src/audio/sfx_params.c
  src/audio/tables/sequence_table.c
  tools/audio/audio_tablegen.c
  tools/audio/extraction/audio_extract.py
  tools/audio/extraction/disassemble_sequence.py
  tools/progress.py
Labels: Audio, Merge-ready, held

#1690 Update website links
  README.md
  docs/CONTRIBUTING.md
  docs/REVIEWING.md
  docs/tutorial/introduction.md
Labels: Clean up

#1684 Add rand.h for non-qrand.c rand functions
  include/rand.h
  include/z64.h
  include/z64math.h
  src/code/sys_math.c
  src/code/z_lib.c
Labels: Clean up, Merge-ready

#1691 Incremental link z_game_over
  Makefile
  linker_scripts/audio_table_rodata.ld
  linker_scripts/data_with_rodata.ld
  spec
  tools/buildtools/mkldscript.c
  tools/buildtools/spec.c
  tools/buildtools/spec.h
Labels: Tooling, Clean up, Merge-ready

#1692 Revamp "AnimationContext" Docs, now called "AnimTaskQueue"
  include/z64animation.h
  include/z64play.h
  src/code/z_collision_check.c
  src/code/z_en_hy_code.c
  src/code/z_play.c
  src/code/z_skelanime.c
  src/overlays/actors/ovl_En_Gm/z_en_gm.c
  src/overlays/actors/ovl_En_Tru/z_en_tru.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/namefixer.py
  tools/sizes/code_functions.csv
Labels: documentation, Merge-ready

#1693 Colliders Sync General Clean
  include/z64collision_check.h
  src/code/z_collision_check.c
Labels: documentation, Clean up, Merge-ready

#1694 Player: Document "WaitForPutAway"
  include/z64player.h
  src/code/z_actor.c
  src/code/z_player_lib.c
  src/overlays/actors/ovl_Door_Shutter/z_door_shutter.c
  src/overlays/actors/ovl_En_Bombf/z_en_bombf.c
  src/overlays/actors/ovl_En_Ig/z_en_ig.c
  src/overlays/actors/ovl_En_Test3/z_en_test3.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: documentation, Merge-ready

#1687 Promote some CC_CHECK warnings to errors
  Makefile
Labels: Tooling, Merge-ready

#1699 [headers] gfx_setupdl.h and (fixup) z64skin_matrix.h
  include/gfx.h
  include/gfx_setupdl.h
  include/z64.h
  include/z64skin_matrix.h
Labels: Clean up, Merge-ready

#1701 Divy out mkdir some more in the makefile
  Makefile
Labels: Tooling, Merge-ready
