Repository zeldaret/mm, pull requests merged in 2024-10, with the labels that each got.

#1696 [headers] Move z_actor functions to z64actor.h
  include/functions.h
  include/z64actor.h
  include/z64bgcheck.h
  include/z64scene.h
Labels: Clean up, Merge-ready

#1702 [headers] `z64malloc.h` -> `zelda_arena.h`
  include/zelda_arena.h
  src/code/speed_meter.c
  src/code/z_actor.c
  src/code/z_camera.c
  src/code/z_collision_check.c
  src/code/z_effect_soft_sprite.c
  src/code/z_fcurve_data_skelanime.c
  src/code/z_malloc.c
  src/code/z_overlay.c
  src/code/z_parameter.c
  src/code/z_play.c
  src/code/z_play_hireso.c
  src/code/z_skelanime.c
  src/code/z_skin_awb.c
  src/overlays/actors/ovl_En_Test3/z_en_test3.c
  src/overlays/actors/ovl_En_Test6/z_en_test6.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Clean up, Merge-ready

#1703 [headers] Move object decls to z64object.h, cleanup `Scene_Command*` protos
  include/z64object.h
  include/z64play.h
  include/z64player.h
  include/z64scene.h
Labels: Clean up, Merge-ready

#1704 Add missing std headers to audio tools
  tools/audio/samplebank.c
  tools/audio/samplebank_compiler.c
  tools/audio/soundfont_compiler.c
  tools/audio/xml.c
Labels: Tooling, Audio, Merge-ready

#1685 Port over OoT's new text pipeline
  Makefile
  assets/text/charmap.txt
  assets/text/message_data_static.c
  assets/text/staff_message_data_static.c
  include/message_data_fmt_nes.h
  include/message_data_fmt_staff.h
  include/message_data_static.h
  src/code/z_message.c
  tools/extract_assets.py
  tools/msg/nes/msgdisNES.py
  tools/msg/nes/msgencNES.py
  tools/msg/staff/msgdisStaff.py
  tools/msg/staff/msgencStaff.py
  tools/text/msgdis.py
  tools/text/msgenc.py
Labels: Tooling, Asset, Merge-ready

#1700 Colliders Sync JntSphere
  include/z64actor.h
  include/z64collision_check.h
  src/code/z_actor.c
  src/code/z_collision_check.c
  src/overlays/actors/ovl_Bg_Kin2_Fence/z_bg_kin2_fence.c
  src/overlays/actors/ovl_Boss_01/z_boss_01.c
  src/overlays/actors/ovl_Boss_02/z_boss_02.c
  src/overlays/actors/ovl_Boss_03/z_boss_03.c
  src/overlays/actors/ovl_Boss_04/z_boss_04.c
  src/overlays/actors/ovl_Boss_05/z_boss_05.c
  src/overlays/actors/ovl_Boss_Hakugin/z_boss_hakugin.c
  src/overlays/actors/ovl_En_Baguo/z_en_baguo.c
  src/overlays/actors/ovl_En_Bal/z_en_bal.c
  src/overlays/actors/ovl_En_Bbfall/z_en_bbfall.c
  src/overlays/actors/ovl_En_Bom/z_en_bom.c
  src/overlays/actors/ovl_En_Bombf/z_en_bombf.c
  src/overlays/actors/ovl_En_Bsb/z_en_bsb.c
  src/overlays/actors/ovl_En_Bubble/z_en_bubble.c
  src/overlays/actors/ovl_En_Butte/z_en_butte.c
  src/overlays/actors/ovl_En_Crow/z_en_crow.c
  src/overlays/actors/ovl_En_Dekubaba/z_en_dekubaba.c
  src/overlays/actors/ovl_En_Dinofos/z_en_dinofos.c
  src/overlays/actors/ovl_En_Dodongo/z_en_dodongo.c
  src/overlays/actors/ovl_En_Dragon/z_en_dragon.c
  src/overlays/actors/ovl_En_Egol/z_en_egol.c
  src/overlays/actors/ovl_En_Encount2/z_en_encount2.c
  src/overlays/actors/ovl_En_Fish/z_en_fish.c
  src/overlays/actors/ovl_En_Goroiwa/z_en_goroiwa.c
  src/overlays/actors/ovl_En_Grasshopper/z_en_grasshopper.c
  src/overlays/actors/ovl_En_Horse/z_en_horse.c
  src/overlays/actors/ovl_En_Insect/z_en_insect.c
  src/overlays/actors/ovl_En_Knight/z_en_knight.c
  src/overlays/actors/ovl_En_Minideath/z_en_minideath.c
  src/overlays/actors/ovl_En_Mushi2/z_en_mushi2.c
  src/overlays/actors/ovl_En_Pametfrog/z_en_pametfrog.c
  src/overlays/actors/ovl_En_Pp/z_en_pp.c
  src/overlays/actors/ovl_En_Ruppecrow/z_en_ruppecrow.c
  src/overlays/actors/ovl_En_Scopecrow/z_en_scopecrow.c
  src/overlays/actors/ovl_En_Syateki_Wf/z_en_syateki_wf.c
  src/overlays/actors/ovl_En_Thiefbird/z_en_thiefbird.c
  src/overlays/actors/ovl_En_Vm/z_en_vm.c
  src/overlays/actors/ovl_En_Wdhand/z_en_wdhand.c
  src/overlays/actors/ovl_En_Wf/z_en_wf.c
  src/overlays/actors/ovl_En_Wiz/z_en_wiz.c
  src/overlays/actors/ovl_Mir_Ray/z_mir_ray.c
  src/overlays/actors/ovl_Obj_Comb/z_obj_comb.c
  src/overlays/actors/ovl_Obj_Flowerpot/z_obj_flowerpot.c
  src/overlays/actors/ovl_Obj_Lightswitch/z_obj_lightswitch.c
  src/overlays/actors/ovl_Obj_Mine/z_obj_mine.c
  src/overlays/actors/ovl_Obj_Snowball/z_obj_snowball.c
  src/overlays/actors/ovl_Obj_Snowball2/z_obj_snowball2.c
Labels: documentation, Clean up, Merge-ready

#1708 Extract assets to extracted
  Makefile
  assets/.gitignore
  assets/archives/map_grand_static/map_grand_static.c
  assets/archives/map_grand_static/map_grand_static.h
  assets/archives/map_i_static/map_i_static.c
  assets/archives/map_i_static/map_i_static.h
  assets/c/.gitignore
  assets/text/message_data.h
  assets/text/message_data_staff.h
  spec
  src/overlays/actors/ovl_En_Thiefbird/z_en_thiefbird.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/extract_assets.py
  tools/progress.py
  tools/text/msgdis.py
Labels: Tooling, Merge-ready

#1710 Player Docs: Misc Rotation
  include/z64player.h
  src/code/z_player_lib.c
  src/overlays/actors/ovl_En_Test3/z_en_test3.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
Labels: documentation, Merge-ready

#1711 Player Docs: FocusActor and Lock-On Cleanup
  assets/xml/objects/gameplay_keep.xml
  include/z64actor.h
  include/z64player.h
  src/code/z_actor.c
  src/code/z_player_lib.c
  src/overlays/actors/ovl_Boss_05/z_boss_05.c
  src/overlays/actors/ovl_En_Aob_01/z_en_aob_01.c
  src/overlays/actors/ovl_En_Elf/z_en_elf.c
  src/overlays/actors/ovl_En_Knight/z_en_knight.c
  src/overlays/actors/ovl_En_Mm3/z_en_mm3.c
  src/overlays/actors/ovl_En_Railgibud/z_en_railgibud.c
  src/overlays/actors/ovl_En_Rd/z_en_rd.c
  src/overlays/actors/ovl_En_Talk_Gibud/z_en_talk_gibud.c
  src/overlays/actors/ovl_En_Tanron2/z_en_tanron2.c
  src/overlays/actors/ovl_En_Test3/z_en_test3.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
  tools/namefixer.py
  tools/sizes/code_functions.csv
Labels: documentation, Merge-ready

#1707 Player Docs: Action Interrupt
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
Labels: documentation, Merge-ready

#1712 Player Docs: Body Shock and Body Burn
  include/z64player.h
  src/overlays/actors/ovl_Boss_01/z_boss_01.c
  src/overlays/actors/ovl_En_Encount3/z_en_encount3.c
  src/overlays/actors/ovl_En_Water_Effect/z_en_water_effect.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
Labels: documentation, Merge-ready

#1714 Colliders Sync Tris Quad Sphere Line
  include/z64actor.h
  include/z64collision_check.h
  src/code/z_actor.c
  src/code/z_collision_check.c
  src/code/z_fireobj.c
  src/overlays/actors/ovl_Arms_Hook/z_arms_hook.c
  src/overlays/actors/ovl_Bg_Spdweb/z_bg_spdweb.c
  src/overlays/actors/ovl_En_Arrow/z_en_arrow.c
  src/overlays/actors/ovl_En_Bat/z_en_bat.c
  src/overlays/actors/ovl_En_Bb/z_en_bb.c
  src/overlays/actors/ovl_En_Death/z_en_death.c
  src/overlays/actors/ovl_En_Firefly/z_en_firefly.c
  src/overlays/actors/ovl_En_Fu_Mato/z_en_fu_mato.c
  src/overlays/actors/ovl_En_Kaizoku/z_en_kaizoku.c
  src/overlays/actors/ovl_En_Mkk/z_en_mkk.c
  src/overlays/actors/ovl_En_Peehat/z_en_peehat.c
  src/overlays/actors/ovl_En_Sw/z_en_sw.c
  src/overlays/actors/ovl_En_Tite/z_en_tite.c
  src/overlays/actors/ovl_Obj_Bell/z_obj_bell.c
  src/overlays/actors/ovl_Obj_Spidertent/z_obj_spidertent.c
  src/overlays/actors/ovl_Obj_Syokudai/z_obj_syokudai.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: documentation, Clean up, Merge-ready

#1716 Target -> Attention (System Rename)
  include/z64actor.h
  src/code/z_actor.c
  src/code/z_parameter.c
  src/overlays/actors/ovl_Boss_05/z_boss_05.c
  src/overlays/actors/ovl_En_Elf/z_en_elf.c
  src/overlays/actors/ovl_En_Knight/z_en_knight.c
  src/overlays/actors/ovl_En_Tanron2/z_en_tanron2.c
  src/overlays/actors/ovl_En_Tk/z_en_tk.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
  tools/namefixer.py
  tools/sizes/code_functions.csv
Labels: documentation, Merge-ready

#1717 Player: ActionChange -> ActionHandler
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: documentation, Merge-ready

#1715 Clean up gitignores
  .gitignore
  tools/.gitignore
  tools/buildtools/.gitignore
Labels: Tooling, Clean up, Merge-ready

#1723 Player Docs: Idle and Fidget
  include/macros.h
  include/regs.h
  include/z64player.h
  src/code/z_player_lib.c
  src/overlays/actors/ovl_En_Test3/z_en_test3.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: documentation, Merge-ready

#1726 Rename gBuildTeam to gBuildCreator
  include/build.h
  src/boot/CIC6105.c
  src/boot/build.c
Labels: documentation, Merge-ready

#1724 Player Docs: speedXZ and yaw
  include/z64player.h
  src/code/z_bg_collect.c
  src/code/z_player_lib.c
  src/overlays/actors/ovl_Bg_Ingate/z_bg_ingate.c
  src/overlays/actors/ovl_Boss_Hakugin/z_boss_hakugin.c
  src/overlays/actors/ovl_En_Dg/z_en_dg.c
  src/overlays/actors/ovl_En_Hakurock/z_en_hakurock.c
  src/overlays/actors/ovl_En_Rg/z_en_rg.c
  src/overlays/actors/ovl_En_Sellnuts/z_en_sellnuts.c
  src/overlays/actors/ovl_En_Test3/z_en_test3.c
  src/overlays/actors/ovl_En_Test6/z_en_test6.c
  src/overlays/actors/ovl_En_Toto/z_en_toto.c
  src/overlays/actors/ovl_En_Wood02/z_en_wood02.c
  src/overlays/actors/ovl_Obj_Hunsui/z_obj_hunsui.c
  src/overlays/actors/ovl_Obj_Nozoki/z_obj_nozoki.c
  src/overlays/actors/ovl_Obj_Switch/z_obj_switch.c
  src/overlays/actors/ovl_Obj_Um/z_obj_um.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: documentation, Merge-ready

#1725 Document `ACTOR_FLAG_THROW_ONLY`
  include/z64actor.h
  src/overlays/actors/ovl_En_Dg/z_en_dg.c
  src/overlays/actors/ovl_En_Ishi/z_en_ishi.c
  src/overlays/actors/ovl_En_Kusa/z_en_kusa.c
  src/overlays/actors/ovl_En_Kusa2/z_en_kusa2.c
  src/overlays/actors/ovl_En_Niw/z_en_niw.c
  src/overlays/actors/ovl_Obj_Grass_Carry/z_obj_grass_carry.c
  src/overlays/actors/ovl_Obj_Snowball2/z_obj_snowball2.c
  src/overlays/actors/ovl_Obj_Tsubo/z_obj_tsubo.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
Labels: documentation, Merge-ready

#1728 Document `Player_Action_TurnInPlace`
  include/z64player.h
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: documentation, Merge-ready

#1730 Document `ACTOR_FLAG_SFX_FOR_PLAYER_BODY_HIT`
  include/z64actor.h
  src/code/z_actor.c
  src/overlays/actors/ovl_En_Am/z_en_am.c
  src/overlays/actors/ovl_En_Bb/z_en_bb.c
  src/overlays/actors/ovl_En_Bbfall/z_en_bbfall.c
  src/overlays/actors/ovl_En_Dekubaba/z_en_dekubaba.c
  src/overlays/actors/ovl_En_Dodongo/z_en_dodongo.c
  src/overlays/actors/ovl_En_Floormas/z_en_floormas.c
  src/overlays/actors/ovl_En_Nutsball/z_en_nutsball.c
  src/overlays/actors/ovl_En_Okuta/z_en_okuta.c
  src/overlays/actors/ovl_En_Peehat/z_en_peehat.c
  src/overlays/actors/ovl_En_Po_Sisters/z_en_po_sisters.c
  src/overlays/actors/ovl_En_Poh/z_en_poh.c
  src/overlays/actors/ovl_En_St/z_en_st.c
  src/overlays/actors/ovl_En_Tite/z_en_tite.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: documentation, Merge-ready

#1734 Update vscode doc
  docs/tutorial/vscode.md
Labels: documentation, Tooling, Merge-ready

#1731 Update Actor Flags for Switches
  include/z64actor.h
  src/code/z_bg_collect.c
  src/code/z_bg_item.c
  src/code/z_player_call.c
  src/overlays/actors/ovl_Dm_Statue/z_dm_statue.c
  src/overlays/actors/ovl_En_Test3/z_en_test3.c
  src/overlays/actors/ovl_En_Torch2/z_en_torch2.c
  src/overlays/actors/ovl_Obj_Armos/z_obj_armos.c
  src/overlays/actors/ovl_Obj_Kibako/z_obj_kibako.c
  src/overlays/actors/ovl_Obj_Oshihiki/z_obj_oshihiki.c
  src/overlays/actors/ovl_Obj_Pzlblock/z_obj_pzlblock.c
  src/overlays/actors/ovl_Obj_Tsubo/z_obj_tsubo.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
  tools/namefixer.py
Labels: documentation, Merge-ready

#1733 Name Talking Related Actor Flags
  include/z64actor.h
  src/code/z_msgevent.c
  src/code/z_sub_s.c
  src/overlays/actors/ovl_Elf_Msg2/z_elf_msg2.c
  src/overlays/actors/ovl_En_Aob_01/z_en_aob_01.c
  src/overlays/actors/ovl_En_Az/z_en_az.c
  src/overlays/actors/ovl_En_Baba/z_en_baba.c
  src/overlays/actors/ovl_En_Bal/z_en_bal.c
  src/overlays/actors/ovl_En_Bigpo/z_en_bigpo.c
  src/overlays/actors/ovl_En_Bji_01/z_en_bji_01.c
  src/overlays/actors/ovl_En_Cow/z_en_cow.c
  src/overlays/actors/ovl_En_Dg/z_en_dg.c
  src/overlays/actors/ovl_En_Elf/z_en_elf.c
  src/overlays/actors/ovl_En_Elfgrp/z_en_elfgrp.c
  src/overlays/actors/ovl_En_Fu/z_en_fu.c
  src/overlays/actors/ovl_En_Gb2/z_en_gb2.c
  src/overlays/actors/ovl_En_Geg/z_en_geg.c
  src/overlays/actors/ovl_En_Gk/z_en_gk.c
  src/overlays/actors/ovl_En_Hs/z_en_hs.c
  src/overlays/actors/ovl_En_In/z_en_in.c
  src/overlays/actors/ovl_En_Invadepoh/z_en_invadepoh.c
  src/overlays/actors/ovl_En_Jgame_Tsn/z_en_jgame_tsn.c
  src/overlays/actors/ovl_En_Js/z_en_js.c
  src/overlays/actors/ovl_En_Kakasi/z_en_kakasi.c
  src/overlays/actors/ovl_En_Kendo_Js/z_en_kendo_js.c
  src/overlays/actors/ovl_En_Kgy/z_en_kgy.c
  src/overlays/actors/ovl_En_Kitan/z_en_kitan.c
  src/overlays/actors/ovl_En_Lift_Nuts/z_en_lift_nuts.c
  src/overlays/actors/ovl_En_Ma4/z_en_ma4.c
  src/overlays/actors/ovl_En_Ma_Yto/z_en_ma_yto.c
  src/overlays/actors/ovl_En_Minifrog/z_en_minifrog.c
  src/overlays/actors/ovl_En_Mk/z_en_mk.c
  src/overlays/actors/ovl_En_Mm3/z_en_mm3.c
  src/overlays/actors/ovl_En_Mnk/z_en_mnk.c
  src/overlays/actors/ovl_En_Ot/z_en_ot.c
  src/overlays/actors/ovl_En_Owl/z_en_owl.c
  src/overlays/actors/ovl_En_Rz/z_en_rz.c
  src/overlays/actors/ovl_En_Sellnuts/z_en_sellnuts.c
  src/overlays/actors/ovl_En_Sth/z_en_sth.c
  src/overlays/actors/ovl_En_Suttari/z_en_suttari.c
  src/overlays/actors/ovl_En_Syateki_Man/z_en_syateki_man.c
  src/overlays/actors/ovl_En_Takaraya/z_en_takaraya.c
  src/overlays/actors/ovl_En_Tk/z_en_tk.c
  src/overlays/actors/ovl_En_Toto/z_en_toto.c
  src/overlays/actors/ovl_En_Yb/z_en_yb.c
  src/overlays/actors/ovl_En_Zob/z_en_zob.c
  src/overlays/actors/ovl_En_Zog/z_en_zog.c
  src/overlays/actors/ovl_En_Zos/z_en_zos.c
  src/overlays/actors/ovl_En_Zot/z_en_zot.c
  src/overlays/actors/ovl_Obj_Nozoki/z_obj_nozoki.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: documentation, Merge-ready

#1735 Document `PLAYER_STATE1_DEAD`
  include/z64player.h
  src/code/z_actor.c
  src/code/z_player_lib.c
  src/overlays/actors/ovl_Arms_Hook/z_arms_hook.c
  src/overlays/actors/ovl_Door_Shutter/z_door_shutter.c
  src/overlays/actors/ovl_Door_Spiral/z_door_spiral.c
  src/overlays/actors/ovl_En_Goroiwa/z_en_goroiwa.c
  src/overlays/actors/ovl_En_Nutsball/z_en_nutsball.c
  src/overlays/actors/ovl_En_Okuta/z_en_okuta.c
  src/overlays/actors/ovl_En_Railgibud/z_en_railgibud.c
  src/overlays/actors/ovl_En_Rd/z_en_rd.c
  src/overlays/actors/ovl_En_Talk_Gibud/z_en_talk_gibud.c
  src/overlays/actors/ovl_Obj_Moon_Stone/z_obj_moon_stone.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: documentation, Merge-ready
