Repository zeldaret/mm, pull requests merged in 2024-01, with the labels that each got.

#1533 Update ZAPD
  include/z64actor.h
  include/z64bgcheck.h
  include/z64curve.h
  include/z64cutscene.h
  include/z64cutscene_commands.h
  include/z64scene.h
  include/z64skin.h
  src/code/PreRender.c
  src/code/z_eventmgr.c
  src/code/z_play.c
  src/overlays/actors/ovl_En_Ma4/z_en_ma4.c
  src/overlays/actors/ovl_En_Test4/z_en_test4.c
  tools/ZAPD/.gitrepo
  tools/ZAPD/ExporterTest/RoomExporter.cpp
  tools/ZAPD/README.md
  tools/ZAPD/ZAPD/GameConfig.cpp
  tools/ZAPD/ZAPD/GameConfig.h
  tools/ZAPD/ZAPD/OtherStructs/CutsceneMM_Commands.cpp
  tools/ZAPD/ZAPD/OtherStructs/CutsceneMM_Commands.h
  tools/ZAPD/ZAPD/OtherStructs/CutsceneOoT_Commands.cpp
  tools/ZAPD/ZAPD/OtherStructs/CutsceneOoT_Commands.h
  tools/ZAPD/ZAPD/OtherStructs/Cutscene_Commands.cpp
  tools/ZAPD/ZAPD/OtherStructs/Cutscene_Commands.h
  tools/ZAPD/ZAPD/OtherStructs/Cutscene_Common.cpp
  tools/ZAPD/ZAPD/OtherStructs/Cutscene_Common.h
  tools/ZAPD/ZAPD/OtherStructs/SkinLimbStructs.cpp
  tools/ZAPD/ZAPD/OtherStructs/SkinLimbStructs.h
  tools/ZAPD/ZAPD/ZAPD.vcxproj
  tools/ZAPD/ZAPD/ZAPD.vcxproj.filters
  tools/ZAPD/ZAPD/ZAnimation.cpp
  tools/ZAPD/ZAPD/ZAnimation.h
  tools/ZAPD/ZAPD/ZCollision.cpp
  tools/ZAPD/ZAPD/ZCutscene.cpp
  tools/ZAPD/ZAPD/ZCutscene.h
  tools/ZAPD/ZAPD/ZLimb.cpp
  tools/ZAPD/ZAPD/ZLimb.h
  tools/ZAPD/ZAPD/ZRoom/Commands/SetCameraSettings.cpp
  tools/ZAPD/ZAPD/ZRoom/Commands/SetCsCamera.cpp
  tools/ZAPD/ZAPD/ZRoom/Commands/SetCsCamera.h
  tools/ZAPD/ZAPD/ZRoom/Commands/SetCutsceneEntryList.cpp
  tools/ZAPD/ZAPD/ZRoom/Commands/SetCutsceneEntryList.h
  tools/ZAPD/ZAPD/ZRoom/Commands/SetCutscenes.cpp
  tools/ZAPD/ZAPD/ZRoom/Commands/SetCutscenes.h
  tools/ZAPD/ZAPD/ZRoom/Commands/SetEntranceList.cpp
  tools/ZAPD/ZAPD/ZRoom/Commands/SetEntranceList.h
  tools/ZAPD/ZAPD/ZRoom/Commands/SetLightingSettings.cpp
  tools/ZAPD/ZAPD/ZRoom/Commands/SetMesh.cpp
  tools/ZAPD/ZAPD/ZRoom/Commands/SetMesh.h
  tools/ZAPD/ZAPD/ZRoom/Commands/SetSpecialObjects.cpp
  tools/ZAPD/ZAPD/ZRoom/Commands/SetWorldMapVisited.cpp
  tools/ZAPD/ZAPD/ZRoom/ZRoom.cpp
  tools/ZAPD/ZAPD/ZSkeleton.cpp
  tools/ZAPD/ZAPDUtils/Utils/Directory.h
  tools/ZAPDConfigs/MM/Config.xml
  tools/ZAPDConfigs/MM/EnumData.xml
Labels: Tooling, Merge-ready

#1532 Allow the mips tool chain to be picked via command argument
  Makefile
Labels: Tooling, Merge-ready, Waiting-for-author

#1526 Dmadata Migration
  Makefile
  include/functions.h
  include/irqmgr.h
  include/tables/dmadata/dmadata_table_us.h
  include/tables/dmadata_table.h
  include/variables.h
  include/yaz0.h
  include/z64dma.h
  include/z64thread.h
  spec
  src/boot/O2/loadfragment.c
  src/boot/O2/loadfragment2.c
  src/boot/idle.c
  src/boot/yaz0.c
  src/boot/z_std_dma.c
  src/code/audio_thread_manager.c
  src/code/graph.c
  src/code/sys_cmpdma.c
  src/code/sys_initial_check.c
  src/code/z_kanfont.c
  src/code/z_kankyo.c
  src/code/z_message.c
  src/code/z_message_nes.c
  src/code/z_message_staff.c
  src/code/z_parameter.c
  src/code/z_play.c
  src/code/z_play_hireso.c
  src/code/z_player_lib.c
  src/code/z_room.c
  src/code/z_scene.c
  src/code/z_skelanime.c
  src/code/z_vr_box.c
  src/dmadata/dmadata.c
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/gamestates/ovl_daytelop/z_daytelop.c
  src/overlays/gamestates/ovl_file_choose/z_file_choose_NES.c
  src/overlays/gamestates/ovl_title/z_title.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_scope_NES.c
  tools/.gitignore
  tools/buildtools/Makefile
  tools/buildtools/mkdmadata.c
  tools/buildtools/spec.c
  tools/buildtools/spec.h
  tools/disasm/functions.txt
  tools/namefixer.py
  tools/sizes/boot_functions.csv
Labels: Tooling, Clean up, Merge-ready

#1534 Skybox Docs
  assets/xml/misc/skyboxes.xml
  include/z64skybox.h
  spec
  src/code/z_play.c
  src/code/z_vr_box.c
  src/code/z_vr_box_draw.c
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_scope_NES.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/sizes/code_functions.csv
Labels: documentation, Asset, Merge-ready

#1539 Add venv to Jenkins
  Jenkinsfile
  tools/Makefile
Labels: Tooling, Needs-lead-approval

#1540 Install GitPython in Jenkins
  Jenkinsfile
Labels: Tooling, Needs-lead-approval, Needs-contributor-approval

#1517 Animation Cleanup: En_S*
  include/z64save.h
  src/code/z_message_nes.c
  src/code/z_parameter.c
  src/overlays/actors/ovl_Bg_Hakugin_Elvpole/z_bg_hakugin_elvpole.c
  src/overlays/actors/ovl_Bg_Kin2_Bombwall/z_bg_kin2_bombwall.c
  src/overlays/actors/ovl_Boss_06/z_boss_06.c
  src/overlays/actors/ovl_Dm_Char03/z_dm_char03.c
  src/overlays/actors/ovl_En_Am/z_en_am.c
  src/overlays/actors/ovl_En_Arrow/z_en_arrow.c
  src/overlays/actors/ovl_En_Bal/z_en_bal.c
  src/overlays/actors/ovl_En_Bigpo/z_en_bigpo.c
  src/overlays/actors/ovl_En_Dnk/z_en_dnk.c
  src/overlays/actors/ovl_En_Fu/z_en_fu.c
  src/overlays/actors/ovl_En_Geg/z_en_geg.c
  src/overlays/actors/ovl_En_Gg/z_en_gg.c
  src/overlays/actors/ovl_En_Goroiwa/z_en_goroiwa.c
  src/overlays/actors/ovl_En_Grasshopper/z_en_grasshopper.c
  src/overlays/actors/ovl_En_Guard_Nuts/z_en_guard_nuts.c
  src/overlays/actors/ovl_En_Kaizoku/z_en_kaizoku.c
  src/overlays/actors/ovl_En_Maruta/z_en_maruta.c
  src/overlays/actors/ovl_En_S_Goro/z_en_s_goro.c
  src/overlays/actors/ovl_En_S_Goro/z_en_s_goro.h
  src/overlays/actors/ovl_En_Sb/z_en_sb.c
  src/overlays/actors/ovl_En_Sb/z_en_sb.h
  src/overlays/actors/ovl_En_Scopenuts/z_en_scopenuts.c
  src/overlays/actors/ovl_En_Scopenuts/z_en_scopenuts.h
  src/overlays/actors/ovl_En_Sellnuts/z_en_sellnuts.c
  src/overlays/actors/ovl_En_Sellnuts/z_en_sellnuts.h
  src/overlays/actors/ovl_En_Shn/z_en_shn.c
  src/overlays/actors/ovl_En_Shn/z_en_shn.h
  src/overlays/actors/ovl_En_Skb/z_en_skb.c
  src/overlays/actors/ovl_En_Skb/z_en_skb.h
  src/overlays/actors/ovl_En_Slime/z_en_slime.c
  src/overlays/actors/ovl_En_Slime/z_en_slime.h
  src/overlays/actors/ovl_En_Sob1/z_en_sob1.c
  src/overlays/actors/ovl_En_Ssh/z_en_ssh.c
  src/overlays/actors/ovl_En_Ssh/z_en_ssh.h
  src/overlays/actors/ovl_En_St/z_en_st.c
  src/overlays/actors/ovl_En_St/z_en_st.h
  src/overlays/actors/ovl_En_Sth/z_en_sth.c
  src/overlays/actors/ovl_En_Stone_heishi/z_en_stone_heishi.c
  src/overlays/actors/ovl_En_Stone_heishi/z_en_stone_heishi.h
  src/overlays/actors/ovl_En_Stop_heishi/z_en_stop_heishi.c
  src/overlays/actors/ovl_En_Stop_heishi/z_en_stop_heishi.h
  src/overlays/actors/ovl_En_Suttari/z_en_suttari.c
  src/overlays/actors/ovl_En_Sw/z_en_sw.c
  src/overlays/actors/ovl_En_Sw/z_en_sw.h
  src/overlays/actors/ovl_En_Syateki_Dekunuts/z_en_syateki_dekunuts.c
  src/overlays/actors/ovl_En_Syateki_Man/z_en_syateki_man.c
  src/overlays/actors/ovl_En_Syateki_Okuta/z_en_syateki_okuta.c
  src/overlays/actors/ovl_En_Syateki_Wf/z_en_syateki_wf.c
  src/overlays/actors/ovl_En_Zoraegg/z_en_zoraegg.c
  src/overlays/actors/ovl_Obj_Hakaisi/z_obj_hakaisi.c
  src/overlays/gamestates/ovl_file_choose/z_file_choose_NES.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_debug.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: Clean up, Merge-ready

#1527 Irqmgr + scheduler Docs
  include/audiomgr.h
  include/functions.h
  include/irqmgr.h
  include/main.h
  include/scheduler.h
  spec
  src/boot/idle.c
  src/boot/irqmgr.c
  src/boot/z_std_dma.c
  src/code/audio_thread_manager.c
  src/code/code_8010C1B0.c
  src/code/graph.c
  src/code/main.c
  src/code/sched.c
  src/code/z_jpeg.c
  src/code/z_nulltask.c
  src/code/z_play.c
  src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_scope_NES.c
  tools/disasm/files.txt
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/sizes/boot_functions.csv
  tools/sizes/code_functions.csv
Labels: documentation, Clean up, Merge-ready

#1528 Framebuffer filter docs
  include/variables.h
  include/z64vis.h
  include/z64viscvg.h
  include/z64vismono.h
  include/z64viszbuf.h
  src/code/game.c
  src/code/z_demo.c
  src/code/z_play.c
  src/code/z_viscvg.c
  src/code/z_vismono.c
  src/code/z_viszbuf.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/sizes/code_functions.csv
Labels: documentation, Merge-ready

#1536 Extract Kanji + some adjacent docs
  assets/xml/interface/kanji.xml
  include/functions.h
  include/kanread.h
  include/variables.h
  spec
  tools/disasm/files.txt
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/sizes/code_functions.csv
Labels: Asset, Merge-ready

#1538 General Cleanup 2
  include/PR/gbi.h
  include/PR/mbi.h
  include/PR/os_cont.h
  include/PR/os_convert.h
  include/PR/os_voice.h
  include/PR/sched.h
  include/PR/sptask.h
  include/fault.h
  include/scheduler.h
  include/variables.h
  include/z64actor.h
  include/z64bgcheck.h
  include/z64bombers_notebook.h
  include/z64message.h
  include/z64speed_meter.h
  include/z64voice.h
  src/audio/lib/load.c
  src/audio/lib/thread.c
  src/audio/voice_internal.c
  src/boot/CIC6105.c
  src/boot/O2/mtxuty-cvt.c
  src/boot/boot_main.c
  src/boot/fault.c
  src/boot/fault_drawer.c
  src/boot/irqmgr.c
  src/code/PreRender.c
  src/code/code_80183070.c
  src/code/graph.c
  src/code/sched.c
  src/code/speed_meter.c
  src/code/su_mtx.c
  src/code/sys_flashrom.c
  src/code/sys_matrix.c
  src/code/z_actor.c
  src/code/z_actor_dlftbls.c
  src/code/z_bgcheck.c
  src/code/z_collision_check.c
  src/code/z_jpeg.c
  src/code/z_message.c
  src/code/z_quake.c
  src/code/z_scene_proc.c
  src/code/z_shrink_window.c
  src/code/z_skin.c
  src/libultra/io/sptask.c
  src/libultra/voice/voicecheckresult.c
  src/libultra/voice/voicecleardictionary.c
  src/libultra/voice/voicecontrolgain.c
  src/libultra/voice/voicegetreaddata.c
  src/libultra/voice/voiceinit.c
  src/libultra/voice/voicemaskdictionary.c
  src/libultra/voice/voicesetword.c
  src/libultra/voice/voicestartreaddata.c
  src/libultra/voice/voicestopread.c
  src/overlays/actors/ovl_En_Fishing/z_en_fishing.c
Labels: Clean up, Merge-ready

#1541 Fix array size in bom_bowl_man
  src/overlays/actors/ovl_En_Bom_Bowl_Man/z_en_bom_bowl_man.c
  src/overlays/actors/ovl_En_Bom_Bowl_Man/z_en_bom_bowl_man.h
Labels: Clean up, Merge-ready

#1543 General Cleanup 3
  include/PR/gbi.h
  include/PR/os_thread.h
  include/PR/os_vi.h
  include/gfxprint.h
  spec
  src/boot/O2/gfxprint.c
  src/boot/fault.c
  src/code/padmgr.c
  src/code/z_actor.c
  src/code/z_en_hy_code.c
  src/code/z_fbdemo.c
  src/code/z_lights.c
  src/code/z_parameter.c
  src/code/z_play.c
  src/code/z_player_lib.c
  src/code/z_rcp.c
  src/code/z_room.c
  src/code/z_scene.c
  src/code/z_vimode.c
  src/libultra/os/thread.c
  src/libultra/voice/voicestopreaddata.c
  src/overlays/actors/ovl_Boss_03/z_boss_03.c
  src/overlays/actors/ovl_Dm_An/z_dm_an.c
  src/overlays/actors/ovl_Dm_Gm/z_dm_gm.c
  src/overlays/actors/ovl_Dm_Stk/z_dm_stk.c
  src/overlays/actors/ovl_En_An/z_en_an.c
  src/overlays/actors/ovl_En_Bba_01/z_en_bba_01.c
  src/overlays/actors/ovl_En_Bigpo/z_en_bigpo.c
  src/overlays/actors/ovl_En_Cne_01/z_en_cne_01.c
  src/overlays/actors/ovl_En_Geg/z_en_geg.c
  src/overlays/actors/ovl_En_Go/z_en_go.c
  src/overlays/actors/ovl_En_Mkk/z_en_mkk.c
  src/overlays/actors/ovl_En_Nwc/z_en_nwc.c
  src/overlays/actors/ovl_En_S_Goro/z_en_s_goro.c
  src/overlays/actors/ovl_En_Slime/z_en_slime.c
  src/overlays/actors/ovl_En_Sob1/z_en_sob1.c
  src/overlays/actors/ovl_En_St/z_en_st.c
  src/overlays/effects/ovl_Effect_En_Ice_Block/z_eff_en_ice_block.c
  src/overlays/effects/ovl_Effect_Ss_D_Fire/z_eff_ss_d_fire.c
  src/overlays/effects/ovl_Effect_Ss_Extra/z_eff_ss_extra.c
  src/overlays/fbdemos/ovl_fbdemo_wipe1/z_fbdemo_wipe1.c
Labels: Clean up, Merge-ready

#1542 Build tools rework
  Makefile
  requirements.txt
  tools/buildtools/Makefile
  tools/buildtools/checksummer.py
  tools/buildtools/elf2rom.c
  tools/buildtools/elf32.c
  tools/buildtools/elf32.h
  tools/buildtools/makeromfs.c
  tools/buildtools/makeyar.c
  tools/buildtools/makeyar.py
  tools/buildtools/n64chksum.c
  tools/buildtools/n64chksum.h
  tools/buildtools/yaz0.c
  tools/buildtools/yaz0.h
  tools/buildtools/yaz0tool.c
  tools/decompress_yars.py
  tools/fixbaserom.py
Labels: Tooling, Merge-ready
