Repository zeldaret/mm, pull requests merged in 2025-02, with the labels that each got.

#1791 GCC Compiler Support
  Makefile
  spec
  src/gcc_fix/missing_gcc_functions.c
  tools/buildtools/mkldscript.c
Labels: Tooling, Merge-ready

#1790 spec -> spec/spec
  Makefile
  spec/spec
  tools/disasm/disasm.py
Labels: Tooling, Merge-ready

#1783 Misc FAKE fixes
  include/z64player.h
  src/code/audio_stop_all_sfx.c
  src/code/cutscene_camera.c
  src/code/sys_math3d.c
  src/code/z_actor.c
  src/code/z_bgcheck.c
  src/code/z_camera.c
  src/code/z_eff_blure.c
  src/code/z_eff_tire_mark.c
  src/code/z_eventmgr.c
  src/code/z_map_disp.c
  src/code/z_play.c
  src/code/z_player_lib.c
  src/overlays/actors/ovl_Bg_Astr_Bombwall/z_bg_astr_bombwall.c
  src/overlays/actors/ovl_En_Invadepoh/z_en_invadepoh.c
  src/overlays/actors/ovl_En_Kakasi/z_en_kakasi.c
  src/overlays/actors/ovl_En_Knight/z_en_knight.c
  src/overlays/actors/ovl_En_Kusa2/z_en_kusa2.c
  src/overlays/actors/ovl_En_Minifrog/z_en_minifrog.c
  src/overlays/actors/ovl_En_Owl/z_en_owl.c
  src/overlays/actors/ovl_En_Po_Sisters/z_en_po_sisters.c
  src/overlays/actors/ovl_En_Test6/z_en_test6.c
  src/overlays/actors/ovl_En_Test7/z_en_test7.c
  src/overlays/actors/ovl_En_Thiefbird/z_en_thiefbird.c
  src/overlays/actors/ovl_En_Time_Tag/z_en_time_tag.c
  src/overlays/actors/ovl_En_Trt/z_en_trt.c
  src/overlays/actors/ovl_En_Zoraegg/z_en_zoraegg.c
  src/overlays/actors/ovl_Obj_Aqua/z_obj_aqua.c
  src/overlays/actors/ovl_Obj_Switch/z_obj_switch.c
  src/overlays/actors/ovl_Obj_Um/z_obj_um.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
Labels: Clean up, Merge-ready

#1794 `EnIshi` documentation pass, and `gameplay_field_keep` assets labeled
  assets/xml/objects/gameplay_field_keep.xml
  src/overlays/actors/ovl_En_Ishi/z_en_ishi.c
  src/overlays/actors/ovl_En_Ishi/z_en_ishi.h
  src/overlays/actors/ovl_Obj_Bombiwa/z_obj_bombiwa.c
  src/overlays/actors/ovl_Obj_Hamishi/z_obj_hamishi.c
  src/overlays/actors/ovl_player_actor/z_player.c
  tools/disasm/functions.txt
Labels: documentation, Overlay, Asset, Merge-ready

#1795 Small sys_flashrom clean up
  include/sys_flashrom.h
  src/code/sys_flashrom.c
  src/code/z_sram_NES.c
  tools/disasm/functions.txt
  tools/sizes/code_functions.csv
Labels: Clean up, Merge-ready

#1797 Small Misc fix cleanups
  src/code/z_map_disp.c
  src/overlays/actors/ovl_Bg_Dblue_Balance/z_bg_dblue_balance.c
  src/overlays/actors/ovl_Bg_Hakugin_Elvpole/z_bg_hakugin_elvpole.c
  src/overlays/actors/ovl_En_Firefly/z_en_firefly.h
Labels: Clean up, Merge-ready

#1760 Remove asm-processor in favor of preprocess.sh
  Makefile
  docs/BUILDING_MACOS.md
  include/prevent_bss_reordering.h
  include/prevent_bss_reordering2.h
  include/z64cutscene_commands.h
  src/audio/lib/effects.c
  src/boot/CIC6105.c
  src/boot/idle.c
  src/boot/z_std_dma.c
  src/buffers/gfxbuffers.c
  src/code/main.c
  src/code/sys_math3d.c
  src/code/z_bgcheck.c
  src/code/z_collision_check.c
  src/code/z_demo.c
  src/code/z_kaleido_scope_call.c
  src/code/z_map_disp.c
  src/code/z_message.c
  src/overlays/actors/ovl_Bg_F40_Switch/z_bg_f40_switch.c
  src/overlays/actors/ovl_Bg_Hakugin_Switch/z_bg_hakugin_switch.c
  src/overlays/actors/ovl_Boss_02/z_boss_02.c
  src/overlays/actors/ovl_Boss_03/z_boss_03.c
  src/overlays/actors/ovl_Boss_06/z_boss_06.c
  src/overlays/actors/ovl_Boss_07/z_boss_07.c
  src/overlays/actors/ovl_Eff_Kamejima_Wave/z_eff_kamejima_wave.c
  src/overlays/actors/ovl_En_Az/z_en_az.c
  src/overlays/actors/ovl_En_Kakasi/z_en_kakasi.c
  src/overlays/actors/ovl_En_Kanban/z_en_kanban.c
  src/overlays/actors/ovl_En_Knight/z_en_knight.c
  src/overlays/actors/ovl_En_Poh/z_en_poh.c
  src/overlays/actors/ovl_En_Rg/z_en_rg.c
  src/overlays/actors/ovl_En_Test3/z_en_test3.c
  src/overlays/actors/ovl_En_Test7/z_en_test7.c
  src/overlays/actors/ovl_En_Thiefbird/z_en_thiefbird.c
  src/overlays/actors/ovl_En_Wood02/z_en_wood02.c
  src/overlays/actors/ovl_Oceff_Wipe3/z_oceff_wipe3.c
  src/overlays/actors/ovl_player_actor/z_player.c
  src/overlays/gamestates/ovl_file_choose/z_file_nameset_NES.c
  tools/.gitignore
  tools/buildtools/Makefile
  tools/buildtools/preprocess.sh
  tools/buildtools/preprocess_pragmas.c
  tools/calc_bss.sh
  tools/extract_assets.py
  tools/fix_bss.py
  tools/ido_block_numbers.py
Labels: Tooling, Merge-ready

#1798 Macroify MML opcodes
  Makefile
  assets/audio/sequences/seq_0.prg.seq
  assets/audio/sequences/seq_1.prg.seq
  include/audio/aseq.h
  src/audio/lib/seqplayer.c
Labels: Audio, Merge-ready

#1788 `En_Kaizoku` and `object_kz` documented: the pirate fighter miniboss
  assets/xml/objects/object_kz.xml
  src/overlays/actors/ovl_En_Kaizoku/z_en_kaizoku.c
  src/overlays/actors/ovl_En_Kaizoku/z_en_kaizoku.h
  src/overlays/actors/ovl_Obj_Boyo/z_obj_boyo.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
Labels: documentation, Overlay, Asset, Merge-ready
