Repository zeldaret/mm, pull requests merged in 2025-03, with the labels that each got.

#1799 EffectSs Sync
  include/z64effect_ss.h
  src/code/z_actor.c
  src/code/z_eff_blure.c
  src/code/z_effect_soft_sprite.c
  src/code/z_effect_soft_sprite_dlftbls.c
  src/code/z_play.c
  src/overlays/effects/ovl_Effect_Ss_Bomb2/z_eff_ss_bomb2.c
  src/overlays/effects/ovl_Effect_Ss_Hitmark/z_eff_ss_hitmark.c
  src/overlays/effects/ovl_Effect_Ss_Lightning/z_eff_ss_lightning.c
  tools/disasm/functions.txt
  tools/disasm/variables.txt
  tools/sizes/code_functions.csv
Labels: documentation, Clean up, Merge-ready

#1796 Document credits dog OOB access
  src/overlays/actors/ovl_En_Dg/z_en_dg.c
Labels: documentation, Merge-ready

#1686 func_80183070 to Sys_Freeze
  include/functions.h
  spec/spec
  src/code/sys_freeze.c
  tools/disasm/files.txt
  tools/sizes/code_functions.csv
Labels: documentation, Merge-ready

#1800 Misc fixes
  assets/xml/boot/gfxprint.xml
  spec/spec
  src/boot/fault.c
  src/boot/fault_drawer.c
  src/boot/libu64/stackcheck.c
  src/boot/rspboot.s
  src/code/rspcode.s
  src/code/rsptext.s
  src/code/z_rumble.c
  src/code/z_skin.c
  src/libultra/gu/position.c
  tools/disasm/disasm.py
  tools/disasm/files.txt
  tools/disasm/functions.txt
  tools/sizes/boot_functions.csv
Labels: Clean up, Merge-ready

#1801 Remove us specific dmadata table
  include/tables/dmadata/dmadata_table_us.h
  include/tables/dmadata_table.h
Labels: Clean up, Merge-ready
