Repository zeldaret/mm, pull requests merged in 2025-08, with the labels that each got.

#1815 Handwritten asm: Register getter/setter functions
  include/PR/R4300.h
  spec/spec
  src/libultra/os/getcause.s
  src/libultra/os/getcompare.s
  src/libultra/os/getconfig.s
  src/libultra/os/getcount.s
  src/libultra/os/getfpccsr.s
  src/libultra/os/getsr.s
  src/libultra/os/getwatchlo.s
  src/libultra/os/setcause.s
  src/libultra/os/setcompare.s
  src/libultra/os/setconfig.s
  src/libultra/os/setfpccsr.s
  src/libultra/os/setsr.s
  src/libultra/os/setwatchlo.s
Labels: boot, Merge-ready

#1820 parameters.s
  linker_scripts/final/hardware_regs.ld
  spec/spec
  src/libultra/os/parameters.s
Labels: boot, Merge-ready

#1818 Handwritten asm: fp
  spec/spec
  src/boot/libc64/fp.s
Labels: boot, Merge-ready

#1819 Handwritten asm: exceptasm, get/setintmask
  include/PR/os.h
  include/PR/os_exception.h
  include/PR/os_internal.h
  include/PR/os_message.h
  include/PR/os_thread.h
  include/PR/rcp.h
  include/PR/rdp.h
  include/PR/ultratypes.h
  include/PR/version.h
  include/macro.inc
  spec/spec
  src/libultra/io/si.c
  src/libultra/io/sirawdma.c
  src/libultra/os/exceptasm.s
  src/libultra/os/getintmask.s
  src/libultra/os/setintmask.s
  tools/warnings_count/warnings_build_current.txt
Labels: boot, Merge-ready

#1816 Handwritten asm: gu and mgu
  spec/spec
  src/libultra/gu/sqrtf.s
  src/libultra/mgu/mtxf2l.s
  src/libultra/mgu/mtxident.s
  src/libultra/mgu/mtxidentf.s
  src/libultra/mgu/mtxl2f.s
  src/libultra/mgu/normalize.s
  src/libultra/mgu/scale.s
  src/libultra/mgu/translate.s
Labels: boot, Waiting-for-author, Needs-second-approval

#1821 Handwritten asm: OS functions, libm_vals
  include/PR/rdb.h
  linker_scripts/final/hardware_regs.ld
  spec/spec
  src/libultra/gu/libm_vals.s
  src/libultra/os/getintmask.s
  src/libultra/os/interrupt.s
  src/libultra/os/invaldcache.s
  src/libultra/os/invalicache.s
  src/libultra/os/maptlbrdb.s
  src/libultra/os/probetlb.s
  src/libultra/os/unmaptlball.s
  src/libultra/os/writebackdcache.s
  src/libultra/os/writebackdcacheall.s
  tools/warnings_count/warnings_build_current.txt
Labels: boot, Merge-ready

#1822 Switch to spimdisasm
  Jenkinsfile
  Makefile
  include/macro.inc
  requirements.txt
  tools/disasm/disasm.py
  tools/disasm/dma_filenames.txt
  tools/disasm/do_disasm.sh
  tools/disasm/file_addresses.py
  tools/disasm/files.txt
  tools/disasm/functions.txt
  tools/disasm/n64-us/file_addresses.csv
  tools/disasm/n64-us/files_boot.csv
  tools/disasm/n64-us/files_code.csv
  tools/disasm/n64-us/files_ovl_file_choose.csv
  tools/disasm/n64-us/files_ovl_kaleido_scope.csv
  tools/disasm/n64-us/functions.txt
  tools/disasm/n64-us/variables.txt
  tools/disasm/sym_info.py
  tools/disasm/variables.txt
Labels: Tooling, Needs-second-approval
