Repository zeldaret/mm, pull requests merged in 2025-01, with the labels that each got.

#1784 Sync soundfont_compiler.c with recent OoT change, give automatic names to sequence 0 channels that implement sfx
  assets/audio/sequences/seq_0.prg.seq
  include/audio/soundfont.h
  include/tables/sfx/enemybank_table.h
  include/tables/sfx/environmentbank_table.h
  include/tables/sfx/itembank_table.h
  include/tables/sfx/ocarinabank_table.h
  include/tables/sfx/playerbank_table.h
  include/tables/sfx/systembank_table.h
  include/tables/sfx/voicebank_table.h
  src/overlays/actors/ovl_En_Tanron2/z_en_tanron2.c
  tools/audio/soundfont_compiler.c
Labels: Audio, Merge-ready

#1786 Document original player animation names in `gameplay_keep`
  assets/xml/objects/gameplay_keep.xml
Labels: Asset, Merge-ready

#1787 Add makefile rule to build sample blobs out of assets/
  Makefile
Labels: Tooling, Audio, Merge-ready

#1785 Provide AVOID_UB for some bugs found in GCC compiler testing
  include/z64player.h
  src/boot/yaz0.c
  src/code/z_message_nes.c
  src/code/z_player_lib.c
  src/overlays/actors/ovl_En_Dnq/z_en_dnq.c
  src/overlays/actors/ovl_player_actor/z_player.c
Labels: Clean up, Merge-ready

#1792 `En_Syokudai`: label one arrow type enum
  src/overlays/actors/ovl_Obj_Syokudai/z_obj_syokudai.c
Labels: Clean up, Merge-ready

#1789 GCC Testing Vanilla bugs
  src/overlays/actors/ovl_En_Go/z_en_go.c
  src/overlays/actors/ovl_En_Pr/z_en_pr.c
  src/overlays/actors/ovl_En_Rr/z_en_rr.c
  src/overlays/actors/ovl_En_Sb/z_en_sb.c
  src/overlays/actors/ovl_En_Tubo_Trap/z_en_tubo_trap.c
Labels: documentation, Merge-ready

#1793 Fix /bin/bash -> /usr/bin/env bash
  Dockerfile
  Makefile
  docs/BUILDING_DOCKER.md
  tools/asm-processor/compile-test.sh
  tools/calc_bss.sh
  tools/check_format.sh
  tools/reloc_spec_check.sh
  tools/rename_sym.sh
  tools/warnings_count/check_new_warnings.sh
  tools/warnings_count/compare_warnings.sh
  tools/warnings_count/update_current_warnings.sh
Labels: Tooling, Merge-ready
